// Screen text for stage 6: work board, calendar and appointments, deferred work (English / Bahasa Indonesia).
export const boardEn = {
  // Work board
  'board.sub': 'Every job still in the shop. Drag a card to move it along; invoicing and payments move it to Invoiced and Paid.',
  'board.view': 'Board view', 'board.kanban': 'Kanban', 'board.list': 'List',
  'board.search': 'Search job, company, plate or contact', 'board.technician': 'Technician',
  'board.allTechs': 'All technicians', 'board.noTech': 'No technician yet', 'board.allAdvisors': 'All advisors', 'board.allPriorities': 'All priorities',
  'board.clearFilters': 'Clear filters',
  'board.empty': 'No jobs in the shop', 'board.emptyText': 'Open estimates and invoiced jobs not yet picked up show here. Start a job to see it on the board.',
  'board.noneMatch': 'No jobs match the filters', 'board.noneHere': 'Nothing here',
  'board.moved': 'Job #{no} moved to {status}', 'board.pickedUp': 'Job #{no} marked as picked up',
  'board.todayAt': 'Today {time}', 'board.tomorrowAt': 'Tomorrow {time}',
  'board.openJob': 'Open job', 'board.moveTo': 'Move to {status}', 'board.book': 'Book appointment',
  'board.printEstimate': 'Print estimate', 'board.printInvoice': 'Print invoice',
  'board.cardLabel': 'Job #{no}, {company}, {plate}', 'board.cardMenu': 'More for job #{no}',
  'board.ageTitle': 'Days since the job was opened', 'board.days': '{n} d',
  'board.pending': '{n} awaiting approval', 'board.pendingTitle': 'Services still waiting for the company’s approval', 'board.approved': 'Approved',
  'board.noTechShort': 'No technician',
  'board.servicesTitle': 'Approved services done / all services', 'board.inspTitle': 'Inspections', 'board.hoursTitle': 'Labour hours on the job', 'board.h': 'h',
  'board.col.invoice': 'Invoice', 'board.col.approval': 'Approval', 'board.col.appt': 'Appointment', 'board.col.hours': 'Hours',
  'board.listTotal': '{n} jobs · {amount}',

  // Opening hours
  'settings.nav.hours': 'Opening hours',
  'hours.hint': 'Bookings can only be made while the shop is open, and the calendar shows these hours. Bookings already made keep their times if you change this.',
  'hours.open': 'Open', 'hours.closed': 'Closed', 'hours.closedAllDay': 'Closed all day', 'hours.copyMon': 'Copy Monday to Tuesday–Friday',
  'hours.opensOn': '{day} opens', 'hours.closesOn': '{day} closes', 'hours.badDay': '{day}: closing time must be after opening time', 'hours.noOpenDay': 'Open at least one day of the week.', 'hours.startAfterClose': 'That is after the shop closes ({time}).',
  'hours.day.mon': 'Monday', 'hours.day.tue': 'Tuesday', 'hours.day.wed': 'Wednesday', 'hours.day.thu': 'Thursday', 'hours.day.fri': 'Friday', 'hours.day.sat': 'Saturday', 'hours.day.sun': 'Sunday',
  'hours.closedDay': 'The shop is closed on {day}', 'hours.beforeOpen': 'The shop opens at {time}', 'hours.afterClose': 'The shop closes at {time}',
  'hours.endClosedDay': 'The shop is closed on {day}, when this booking ends', 'hours.endOutside': 'On the last day the shop is open {from}–{to}',
  'hours.openFromTo': 'Open {from}–{to}',
  'board.cancelBookingTitle': 'Cancel the booking too?', 'board.cancelBookingYes': 'Cancel the booking', 'board.keepBooking': 'Keep the booking',
  'board.cancelBookingText': 'Job #{no} is booked for {when}. Moving it back to Estimate: should that booking be cancelled as well?',
  'db:The shop is closed on that day': 'The shop is closed on that day (see Settings → Opening hours).',
  'db:That is before the shop opens': 'That is before the shop opens (see Settings → Opening hours).',
  'db:That is after the shop closes': 'That is after the shop closes (see Settings → Opening hours).',
  'db:The shop is closed on the day the booking ends': 'The shop is closed on the day the booking ends.',

  // Mileage check
  'common.confirm': 'Confirm',
  'km.lowerTitle': 'Lower mileage than before', 'km.yes': 'Yes, it is correct', 'km.no': 'Let me fix it',
  'km.lowerText': 'You entered {km}, but this vehicle already had {last} recorded{where}. Odometers don\u2019t go back, so please check the number. Is {km} correct?',
  'km.outBelowInNo': 'Km out ({out}) can\'t be lower than km in ({in}). If the km in is wrong, correct it first.',
  'km.onJob': ' on job #{no}', 'km.outBelowIn': 'Odometer out ({out}) is lower than odometer in ({in}). Is it correct?',

  // Calendar
  'cal.sub': 'Bookings on the shop clock. Click an empty slot to book; drag a booking to move it.',
  'cal.newAppt': 'Appointment', 'cal.prev': 'Previous', 'cal.next': 'Next', 'cal.today': 'Today', 'cal.view': 'Calendar view',
  'cal.day': 'Day', 'cal.week': 'Week', 'cal.month': 'Month',
  'cal.search': 'Search company, plate or job', 'cal.showCancelled': 'Show cancelled', 'cal.allHours': 'All hours',
  'cal.requests': 'Requests', 'cal.hideRequests': 'Hide requests', 'cal.showRequests': 'Show requests',
  'cal.noRequests': 'No booking requests waiting. Bookings with the status “Requested” show here until they are confirmed.',
  'cal.emptyRange': 'No bookings in this period.',
  'cal.newAt': 'New booking {when} {who}', 'cal.newOn': 'New booking on {day}', 'cal.more': '+{n} more',
  'cal.moved': 'Moved to {when}', 'cal.allDay': 'All day',

  // Appointments
  'appt.new': 'New appointment', 'appt.edit': 'Appointment', 'appt.view': 'Appointment',
  'appt.readOnly': 'You can see bookings but not change them.',
  'appt.title': 'Title (optional)', 'appt.titleHint': 'e.g. 10.000 km service, or a block such as “Shop meeting”',
  'appt.start': 'Starts', 'appt.end': 'Ends', 'appt.startTime': 'Start time', 'appt.endTime': 'End time',
  'appt.change': 'Change', 'appt.blockHint': 'Leave the company empty for a block of time (training, a day off) and give it a title.',
  'appt.noVehicle': 'No particular vehicle', 'appt.job': 'Job', 'appt.noJob': 'No job yet', 'appt.pickVehicleFirst': 'Pick a vehicle first',
  'appt.newJob': '+ Create a new estimate', 'appt.newJobMade': 'New estimate #{no} (already created)',
  'appt.openJob': 'Open job #{no}', 'appt.jobHint': 'Linking a job moves it to Scheduled on the board, and to Arrived when the vehicle arrives.',
  'appt.concerns': 'What the driver reported (one per line)', 'appt.concernsHint': 'Saved as the new estimate’s concerns.',
  'appt.unassigned': 'Unassigned', 'appt.status': 'Status', 'appt.notes': 'Notes', 'appt.notesHint': 'e.g. Driver drops off the night before; key at security',
  'appt.st.requested': 'Requested', 'appt.st.scheduled': 'Scheduled', 'appt.st.confirmed': 'Confirmed', 'appt.st.arrived': 'Arrived', 'appt.st.cancelled': 'Cancelled', 'appt.st.no_show': 'No-show',
  'appt.stHint.requested': 'Asked for, not yet agreed. Listed under Requests; the job stays an Estimate.',
  'appt.stHint.scheduled': 'Booked. A linked job moves to Scheduled.',
  'appt.stHint.confirmed': 'The company confirmed the time. A linked job moves to Scheduled.',
  'appt.stHint.arrived': 'The vehicle is here. A linked job moves to Arrived.',
  'appt.stHint.cancelled': 'Called off. Hidden unless “Show cancelled” is ticked.',
  'appt.stHint.no_show': 'The vehicle didn’t come.',
  'appt.clash': '{name} already has a booking at {when}.',
  'appt.badTime': 'Enter a date and time', 'appt.endAfterStart': 'Must be after the start', 'appt.tooLong': 'A booking can be at most {n} days',
  'appt.needWho': 'Pick a company, or give the booking a title', 'appt.needVehicle': 'Pick the vehicle for the new estimate', 'appt.tooLongText': 'Too long',
  'appt.jobKept': 'Estimate #{no} was created; it is kept.',
  'appt.book': 'Book', 'appt.booked': 'Appointment booked', 'appt.saved': 'Appointment saved', 'appt.deleted': 'Appointment deleted',
  'appt.delete': 'Delete', 'appt.deleteYes': 'Yes, delete it', 'appt.linkedJob': 'linked',
  'appt.histCreated': 'Booked', 'appt.histDeleted': 'Deleted',
  'appt.f.title': 'Title', 'appt.f.start_time': 'Starts', 'appt.f.end_time': 'Ends', 'appt.f.customer_id': 'Company', 'appt.f.vehicle_id': 'Vehicle',
  'appt.f.ro_id': 'Job', 'appt.f.technician_id': 'Technician', 'appt.f.status': 'Status', 'appt.f.notes': 'Notes',

  // Job page
  'job.appointments': 'Appointments', 'job.noAppointments': 'Not booked yet.', 'job.moreAppointments': '+{n} more',
  'job.act.appt': 'Appointment', 'job.act.apptBooked': 'Appointment booked', 'job.act.apptRemoved': 'Appointment removed',
  'job.act.apptMoved': 'Moved', 'job.act.apptNotes': 'Title or notes changed',
  'job.act.deferredDismissed': 'Deferred work dismissed', 'job.act.deferredRestored': 'Deferred work back on the list',

  // Deferred work
  'def.banner': 'This vehicle has {n} deferred service(s) from earlier jobs.', 'def.review': 'Review and add',
  'def.carryTitle': 'Add deferred work to #{no}', 'def.carryYes': 'Add {n}',
  'def.carryText': 'Each service is copied with its lines at the price quoted then, as work awaiting approval. The earlier job is not changed.',
  'def.carried': '{n} service(s) added to #{no}',
  'def.addToJob': 'Add to a job…', 'def.addTitle': 'Add “{name}” to a job', 'def.addYes': 'Add', 'def.open': 'Open', 'def.newEstimate': 'A new estimate',
  'def.dismiss': 'Dismiss…', 'def.dismissTitle': 'Dismiss “{name}”', 'def.dismissYes': 'Dismiss',
  'def.dismissText': 'Takes it off the Deferred list without doing the work. You can bring it back later.',
  'def.reason': 'Reason (optional)', 'def.reasonHint': 'e.g. Company had it done elsewhere', 'def.dismissed': 'Dismissed',
  'def.restore': 'Bring back', 'def.actions': 'Actions', 'def.actionsFor': 'Actions for {name}',
  'def.carriedInto': 'Carried into', 'def.onOpenJob': 'Deferred on an estimate that is still open; approve it there if the company agrees.', 'def.dismissedOn': 'Dismissed {date}',
  'def.f.open': 'Waiting', 'def.f.carried': 'Carried over', 'def.f.dismissed': 'Dismissed',
}

export const boardId = {
  // Papan kerja
  'board.sub': 'Semua pekerjaan yang masih di bengkel. Seret kartu untuk memindahkannya; invoice dan pembayaran memindahkannya ke Invoice dan Lunas.',
  'board.view': 'Tampilan papan', 'board.kanban': 'Kanban', 'board.list': 'Daftar',
  'board.search': 'Cari pekerjaan, perusahaan, plat atau kontak', 'board.technician': 'Mekanik',
  'board.allTechs': 'Semua mekanik', 'board.noTech': 'Belum ada mekanik', 'board.allAdvisors': 'Semua service advisor', 'board.allPriorities': 'Semua prioritas',
  'board.clearFilters': 'Hapus filter',
  'board.empty': 'Tidak ada pekerjaan di bengkel', 'board.emptyText': 'Estimasi terbuka dan pekerjaan ber-invoice yang belum diambil tampil di sini. Buat pekerjaan untuk melihatnya di papan.',
  'board.noneMatch': 'Tidak ada pekerjaan yang cocok', 'board.noneHere': 'Kosong',
  'board.moved': 'Pekerjaan #{no} dipindah ke {status}', 'board.pickedUp': 'Pekerjaan #{no} ditandai sudah diambil',
  'board.todayAt': 'Hari ini {time}', 'board.tomorrowAt': 'Besok {time}',
  'board.openJob': 'Buka pekerjaan', 'board.moveTo': 'Pindah ke {status}', 'board.book': 'Buat janji',
  'board.printEstimate': 'Cetak estimasi', 'board.printInvoice': 'Cetak invoice',
  'board.cardLabel': 'Pekerjaan #{no}, {company}, {plate}', 'board.cardMenu': 'Lainnya untuk pekerjaan #{no}',
  'board.ageTitle': 'Hari sejak pekerjaan dibuka', 'board.days': '{n} hr',
  'board.pending': '{n} menunggu persetujuan', 'board.pendingTitle': 'Servis yang masih menunggu persetujuan perusahaan', 'board.approved': 'Disetujui',
  'board.noTechShort': 'Belum ada mekanik',
  'board.servicesTitle': 'Servis disetujui yang selesai / semua servis', 'board.inspTitle': 'Inspeksi', 'board.hoursTitle': 'Jam kerja di pekerjaan ini', 'board.h': 'jam',
  'board.col.invoice': 'Invoice', 'board.col.approval': 'Persetujuan', 'board.col.appt': 'Janji', 'board.col.hours': 'Jam',
  'board.listTotal': '{n} pekerjaan · {amount}',

  // Jam buka
  'settings.nav.hours': 'Jam buka',
  'hours.hint': 'Janji hanya bisa dibuat saat bengkel buka, dan kalender menampilkan jam ini. Janji yang sudah dibuat tetap pada jamnya jika ini diubah.',
  'hours.open': 'Buka', 'hours.closed': 'Tutup', 'hours.closedAllDay': 'Tutup seharian', 'hours.copyMon': 'Salin Senin ke Selasa–Jumat',
  'hours.opensOn': '{day} buka', 'hours.closesOn': '{day} tutup', 'hours.badDay': '{day}: jam tutup harus setelah jam buka', 'hours.noOpenDay': 'Buka minimal satu hari dalam seminggu.', 'hours.startAfterClose': 'Itu setelah bengkel tutup ({time}).',
  'hours.day.mon': 'Senin', 'hours.day.tue': 'Selasa', 'hours.day.wed': 'Rabu', 'hours.day.thu': 'Kamis', 'hours.day.fri': 'Jumat', 'hours.day.sat': 'Sabtu', 'hours.day.sun': 'Minggu',
  'hours.closedDay': 'Bengkel tutup pada hari {day}', 'hours.beforeOpen': 'Bengkel buka pukul {time}', 'hours.afterClose': 'Bengkel tutup pukul {time}',
  'hours.endClosedDay': 'Bengkel tutup pada hari {day}, saat janji ini berakhir', 'hours.endOutside': 'Di hari terakhir bengkel buka {from}–{to}',
  'hours.openFromTo': 'Buka {from}–{to}',
  'board.cancelBookingTitle': 'Batalkan janjinya juga?', 'board.cancelBookingYes': 'Batalkan janji', 'board.keepBooking': 'Biarkan janji',
  'board.cancelBookingText': 'Pekerjaan #{no} punya janji pada {when}. Pekerjaan dikembalikan ke Estimasi: apakah janji itu juga dibatalkan?',
  'db:The shop is closed on that day': 'Bengkel tutup pada hari itu (lihat Pengaturan → Jam buka).',
  'db:That is before the shop opens': 'Itu sebelum bengkel buka (lihat Pengaturan → Jam buka).',
  'db:That is after the shop closes': 'Itu setelah bengkel tutup (lihat Pengaturan → Jam buka).',
  'db:The shop is closed on the day the booking ends': 'Bengkel tutup pada hari janji ini berakhir.',
  'db:Only an open estimate can be booked': 'Hanya estimasi yang masih terbuka yang bisa dibuatkan janji.',
  'db:The appointment must have the same vehicle and company as its job': 'Janji harus memakai kendaraan dan perusahaan yang sama dengan pekerjaannya.',
  'db:That vehicle belongs to another company': 'Kendaraan itu milik perusahaan lain.',
  'db:Deferred work can only go into an open estimate': 'Servis tertunda hanya bisa dimasukkan ke estimasi yang masih terbuka.',
  'db:Only deferred work from an invoiced or closed job can be carried over': 'Hanya servis tertunda dari pekerjaan yang sudah di-invoice atau ditutup yang bisa dipindahkan.',
  'db:Only deferred work from an invoiced or closed job can be dismissed': 'Hanya servis tertunda dari pekerjaan yang sudah di-invoice atau ditutup yang bisa diabaikan.',
  'db:That deferred work is for another vehicle': 'Servis tertunda itu untuk kendaraan lain.',
  'db:That deferred work has already been carried over': 'Servis tertunda itu sudah dipindahkan.',
  'db:That deferred work was dismissed': 'Servis tertunda itu sudah diabaikan.',
  'db:That work is already on this job': 'Servis itu sudah ada di pekerjaan ini.',

  // Cek kilometer
  'common.confirm': 'Konfirmasi',
  'km.lowerTitle': 'Kilometer lebih rendah dari sebelumnya', 'km.yes': 'Ya, sudah benar', 'km.no': 'Perbaiki dulu',
  'km.lowerText': 'Anda mengisi {km}, padahal kendaraan ini sudah tercatat {last}{where}. Odometer tidak bisa mundur, jadi periksa lagi angkanya. Apakah {km} sudah benar?',
  'km.outBelowInNo': 'Km keluar ({out}) tidak boleh lebih rendah dari km masuk ({in}). Jika km masuk yang salah, perbaiki dulu.',
  'km.onJob': ' di pekerjaan #{no}', 'km.outBelowIn': 'Odometer keluar ({out}) lebih rendah dari odometer masuk ({in}). Apakah sudah benar?',

  // Kalender
  'cal.sub': 'Janji servis menurut jam bengkel. Klik slot kosong untuk membuat janji; seret janji untuk memindahkannya.',
  'cal.newAppt': 'Janji', 'cal.prev': 'Sebelumnya', 'cal.next': 'Berikutnya', 'cal.today': 'Hari ini', 'cal.view': 'Tampilan kalender',
  'cal.day': 'Hari', 'cal.week': 'Minggu', 'cal.month': 'Bulan',
  'cal.search': 'Cari perusahaan, plat atau pekerjaan', 'cal.showCancelled': 'Tampilkan yang batal', 'cal.allHours': 'Semua jam',
  'cal.requests': 'Permintaan', 'cal.hideRequests': 'Sembunyikan permintaan', 'cal.showRequests': 'Tampilkan permintaan',
  'cal.noRequests': 'Tidak ada permintaan janji. Janji berstatus “Diminta” tampil di sini sampai dikonfirmasi.',
  'cal.emptyRange': 'Tidak ada janji di periode ini.',
  'cal.newAt': 'Janji baru {when} {who}', 'cal.newOn': 'Janji baru pada {day}', 'cal.more': '+{n} lagi',
  'cal.moved': 'Dipindah ke {when}', 'cal.allDay': 'Sepanjang hari',

  // Janji
  'appt.new': 'Janji baru', 'appt.edit': 'Janji', 'appt.view': 'Janji',
  'appt.readOnly': 'Anda bisa melihat janji tetapi tidak bisa mengubahnya.',
  'appt.title': 'Judul (opsional)', 'appt.titleHint': 'mis. Servis 10.000 km, atau blok seperti “Rapat bengkel”',
  'appt.start': 'Mulai', 'appt.end': 'Selesai', 'appt.startTime': 'Jam mulai', 'appt.endTime': 'Jam selesai',
  'appt.change': 'Ganti', 'appt.blockHint': 'Kosongkan perusahaan untuk blok waktu (pelatihan, libur) dan beri judul.',
  'appt.noVehicle': 'Tanpa kendaraan tertentu', 'appt.job': 'Pekerjaan', 'appt.noJob': 'Belum ada pekerjaan', 'appt.pickVehicleFirst': 'Pilih kendaraan dulu',
  'appt.newJob': '+ Buat estimasi baru', 'appt.newJobMade': 'Estimasi baru #{no} (sudah dibuat)',
  'appt.openJob': 'Buka pekerjaan #{no}', 'appt.jobHint': 'Menautkan pekerjaan memindahkannya ke Terjadwal di papan, dan ke Tiba saat kendaraan datang.',
  'appt.concerns': 'Keluhan pengemudi (satu per baris)', 'appt.concernsHint': 'Disimpan sebagai keluhan di estimasi baru.',
  'appt.unassigned': 'Belum ditugaskan', 'appt.status': 'Status', 'appt.notes': 'Catatan', 'appt.notesHint': 'mis. Pengemudi mengantar malam sebelumnya; kunci di pos satpam',
  'appt.st.requested': 'Diminta', 'appt.st.scheduled': 'Terjadwal', 'appt.st.confirmed': 'Dikonfirmasi', 'appt.st.arrived': 'Tiba', 'appt.st.cancelled': 'Batal', 'appt.st.no_show': 'Tidak datang',
  'appt.stHint.requested': 'Diminta, belum disepakati. Tampil di Permintaan; pekerjaan tetap Estimasi.',
  'appt.stHint.scheduled': 'Sudah dijadwalkan. Pekerjaan yang ditautkan pindah ke Terjadwal.',
  'appt.stHint.confirmed': 'Perusahaan sudah mengonfirmasi jamnya. Pekerjaan yang ditautkan pindah ke Terjadwal.',
  'appt.stHint.arrived': 'Kendaraan sudah datang. Pekerjaan yang ditautkan pindah ke Tiba.',
  'appt.stHint.cancelled': 'Dibatalkan. Disembunyikan kecuali “Tampilkan yang batal” dicentang.',
  'appt.stHint.no_show': 'Kendaraan tidak datang.',
  'appt.clash': '{name} sudah punya janji pada {when}.',
  'appt.badTime': 'Isi tanggal dan jam', 'appt.endAfterStart': 'Harus setelah jam mulai', 'appt.tooLong': 'Janji paling lama {n} hari',
  'appt.needWho': 'Pilih perusahaan, atau beri judul janji', 'appt.needVehicle': 'Pilih kendaraan untuk estimasi baru', 'appt.tooLongText': 'Terlalu panjang',
  'appt.jobKept': 'Estimasi #{no} sudah dibuat dan tetap disimpan.',
  'appt.book': 'Buat janji', 'appt.booked': 'Janji dibuat', 'appt.saved': 'Janji disimpan', 'appt.deleted': 'Janji dihapus',
  'appt.delete': 'Hapus', 'appt.deleteYes': 'Ya, hapus', 'appt.linkedJob': 'ditautkan',
  'appt.histCreated': 'Dibuat', 'appt.histDeleted': 'Dihapus',
  'appt.f.title': 'Judul', 'appt.f.start_time': 'Mulai', 'appt.f.end_time': 'Selesai', 'appt.f.customer_id': 'Perusahaan', 'appt.f.vehicle_id': 'Kendaraan',
  'appt.f.ro_id': 'Pekerjaan', 'appt.f.technician_id': 'Mekanik', 'appt.f.status': 'Status', 'appt.f.notes': 'Catatan',

  // Halaman pekerjaan
  'job.appointments': 'Janji', 'job.noAppointments': 'Belum ada janji.', 'job.moreAppointments': '+{n} lagi',
  'job.act.appt': 'Janji', 'job.act.apptBooked': 'Janji dibuat', 'job.act.apptRemoved': 'Janji dihapus',
  'job.act.apptMoved': 'Dipindah', 'job.act.apptNotes': 'Judul atau catatan diubah',
  'job.act.deferredDismissed': 'Servis tertunda diabaikan', 'job.act.deferredRestored': 'Servis tertunda dikembalikan ke daftar',

  // Servis tertunda
  'def.banner': 'Kendaraan ini punya {n} servis tertunda dari pekerjaan sebelumnya.', 'def.review': 'Lihat dan tambahkan',
  'def.carryTitle': 'Tambahkan servis tertunda ke #{no}', 'def.carryYes': 'Tambahkan {n}',
  'def.carryText': 'Setiap servis disalin beserta barisnya dengan harga yang ditawarkan saat itu, sebagai pekerjaan yang menunggu persetujuan. Pekerjaan sebelumnya tidak berubah.',
  'def.carried': '{n} servis ditambahkan ke #{no}',
  'def.addToJob': 'Tambahkan ke pekerjaan…', 'def.addTitle': 'Tambahkan “{name}” ke pekerjaan', 'def.addYes': 'Tambahkan', 'def.open': 'Buka', 'def.newEstimate': 'Estimasi baru',
  'def.dismiss': 'Abaikan…', 'def.dismissTitle': 'Abaikan “{name}”', 'def.dismissYes': 'Abaikan',
  'def.dismissText': 'Menghapusnya dari daftar Tertunda tanpa mengerjakannya. Bisa dikembalikan nanti.',
  'def.reason': 'Alasan (opsional)', 'def.reasonHint': 'mis. Perusahaan sudah mengerjakannya di tempat lain', 'def.dismissed': 'Diabaikan',
  'def.restore': 'Kembalikan', 'def.actions': 'Tindakan', 'def.actionsFor': 'Tindakan untuk {name}',
  'def.carriedInto': 'Dipindah ke', 'def.onOpenJob': 'Ditunda di estimasi yang masih terbuka; setujui di sana jika perusahaan setuju.', 'def.dismissedOn': 'Diabaikan {date}',
  'def.f.open': 'Menunggu', 'def.f.carried': 'Sudah dipindah', 'def.f.dismissed': 'Diabaikan',
}
