// All screen text in English and Bahasa Indonesia. Missing Indonesian keys fall back to English.
import { customersEn, customersId } from './strings-customers.js'

const base = {
  en: {
    'common.cancel': 'Cancel', 'common.close': 'Close', 'common.save': 'Save', 'common.delete': 'Delete', 'common.edit': 'Edit',
    'common.remove': 'Remove', 'common.loading': 'Loading…', 'common.soon': 'Soon', 'common.days': 'days',

    'err.permission': 'You do not have permission to do this.',
    'err.duplicate': 'That value is already in use.',
    'err.network': 'Cannot reach the server. Check your connection and try again.',

    'nav.dashboard': 'Dashboard', 'nav.board': 'Work Board', 'nav.calendar': 'Calendar', 'nav.customers': 'Customers',
    'nav.catalog': 'Catalog', 'nav.inventory': 'Inventory', 'nav.reports': 'Reports', 'nav.settings': 'Settings',
    'nav.vehicles': 'Vehicles', 'nav.jobs': 'Jobs', 'nav.search': 'Search customers, vehicles & jobs',
    'nav.notifications': 'Notifications', 'nav.account': 'My account',

    'create.title': 'Create new', 'create.job': 'New job', 'create.customer': 'New customer', 'create.vehicle': 'New vehicle',
    'create.appointment': 'New appointment', 'create.po': 'New purchase order',

    'notif.title': 'Notifications', 'notif.markAll': 'Mark all as read', 'notif.empty': 'You are all caught up.',

    'role.Owner': 'Owner', 'role.Admin': 'Admin', 'role.Service advisor': 'Service advisor', 'role.Technician': 'Technician',
    'role.Viewer': 'Viewer', 'role.Fleet manager': 'Fleet manager',

    'auth.signInTitle': 'Sign in', 'auth.username': 'Username or email', 'auth.password': 'Password', 'auth.signIn': 'Sign in',
    'auth.signOut': 'Sign out', 'auth.forgot': 'Forgot your password?', 'auth.fillBoth': 'Enter your username and password.',
    'auth.badLogin': 'That username or password is not right.', 'auth.inviteOnly': 'Accounts are created by your shop admin.',
    'auth.linkInvalid': 'That link has expired or was already used. Sign in, or ask for a new link.',
    'auth.forgotTitle': 'Reset your password', 'auth.forgotText': 'Enter the email address on your account and we will send you a link to choose a new password.',
    'auth.email': 'Email', 'auth.enterEmail': 'Enter your email address.', 'auth.sendLink': 'Send reset link',
    'auth.checkEmail': 'Check your email', 'auth.resetSent': 'If {email} has an account, a link to reset the password is on its way.',
    'auth.backToLogin': 'Back to sign in',
    'auth.setTitle': 'Choose your password', 'auth.setText': 'Choose a password for your account.',
    'auth.setTextUser': 'Choose a password. You will sign in with the username {username}.',
    'auth.newPassword': 'New password', 'auth.confirmPassword': 'Repeat password', 'auth.savePassword': 'Save password',
    'auth.pwTooShort': 'Use at least 8 characters.', 'auth.pwMismatch': 'The two passwords are not the same.',

    'pending.invited.title': 'Waiting for approval', 'pending.invited.text': 'Your account was created, but a shop admin still has to activate it. You will be able to use Axle as soon as they do.',
    'pending.disabled.title': 'Account switched off', 'pending.disabled.text': 'This account has been disabled. Ask a shop admin if you think this is a mistake.',
    'pending.fleet.title': 'No access yet', 'pending.fleet.text': 'Fleet manager accounts can\'t open Axle yet. Approving your own company\'s work is planned for a later stage.',
    'pending.missing.title': 'Account not set up', 'pending.missing.text': 'We couldn\'t find a profile for this login. Ask a shop admin to check your account.',
    'pending.signedInAs': 'Signed in as {who}', 'pending.check': 'Check again',

    'profile.title': 'My profile', 'profile.name': 'Name', 'profile.username': 'Username', 'profile.usernameHint': 'Ask an admin to change it.',
    'profile.phone': 'Phone', 'profile.language': 'Language', 'profile.languageShop': 'Shop default', 'profile.changePassword': 'Change password',
    'profile.passwordHint': 'Leave empty to keep your current password.', 'profile.nameRequired': 'Enter your name.',

    'stage.foundations': 'Foundations: sign-in, app layout, settings', 'stage.customers': 'Customers & vehicles', 'stage.catalog': 'Catalog',
    'stage.jobs': 'Jobs, estimates, invoices & payments', 'stage.print': 'Printed invoices & estimates', 'stage.board': 'Work board & calendar',
    'stage.inventory': 'Inventory & purchase orders', 'stage.schedules': 'Service schedules', 'stage.reports': 'Dashboard & reports',
    'soon.title': 'Coming in a later stage', 'soon.text': 'This screen is built in stage {stage}: {name}.',

    'dash.hello': 'Welcome, {name}', 'dash.sub': 'Axle v2 preview, connected to the staging database',
    'dash.buildTitle': 'What is built so far', 'dash.buildText': 'Axle is being built in stages. The dashboard fills in at the last stage, once there are jobs and invoices to show.',
    'dash.ready': 'ready to try', 'dash.startHere': 'Start by filling in your shop details in',

    'search.title': 'Search', 'search.for': 'Results for "{q}"', 'search.soon': 'Search covers customers, vehicles and jobs, so it arrives with those screens.',
    'notFound.title': 'Page not found', 'notFound.text': 'That address doesn\'t match any page in Axle.', 'notFound.home': 'Go to the dashboard',

    'settings.sub': 'Changes apply to all users', 'settings.readOnly': 'Only an owner or admin can change these settings',
    'settings.save': 'Save changes', 'settings.saved': 'Settings saved', 'settings.discard': 'Discard', 'settings.unsaved': 'You have unsaved changes',
    'settings.fixErrors': 'Some fields need fixing first.', 'settings.notLoaded': 'Shop settings could not be loaded. Refresh the page; if it keeps happening, the database may not be set up yet.',
    'settings.required': 'Required', 'settings.badNumber': 'Enter a number of 0 or more', 'settings.max100': 'Can\'t be more than 100',
    'settings.minMax': 'The maximum must be at least the minimum', 'settings.badEmail': 'That email address does not look right.',
    'settings.nav.shop': 'Shop profile', 'settings.nav.language': 'Language & printing', 'settings.nav.numbering': 'Invoices & numbering',
    'settings.nav.fees': 'Fees & tax', 'settings.nav.labor': 'Labor rates', 'settings.nav.users': 'Users & access',
    'settings.uploadLogo': 'Upload logo', 'settings.replaceLogo': 'Replace logo', 'settings.logoHint': 'PNG, SVG, JPG or WebP up to 2 MB · shown in the app header and on printed documents',
    'settings.logoType': 'Use a PNG, SVG, JPG or WebP image.', 'settings.logoSize': 'The logo must be 2 MB or smaller.', 'settings.logoSaved': 'Logo updated',
    'settings.shopName': 'Shop name (app & documents)', 'settings.legalName': 'Legal name', 'settings.phone': 'Phone', 'settings.address': 'Address',
    'settings.email': 'Email', 'settings.bank': 'Bank account for invoices', 'settings.npwpHint': '15 or 16 digits',
    'settings.pkp': 'PKP status', 'settings.pkp.unknown': 'Not set', 'settings.pkp.pkp': 'PKP (charges PPN)', 'settings.pkp.non_pkp': 'Non-PKP (no PPN)',
    'settings.pkpHint': 'PPN works as normal until set; Non-PKP turns PPN off',
    'settings.appLang': 'App language (default for new users)', 'settings.printLang': 'Default print language', 'settings.timezone': 'Shop time zone',
    'settings.langHint': 'Each user can switch EN / ID from the top bar. The print language can be changed each time you print. Due dates and "service due" use the shop time zone.',
    'settings.terms': 'Terms & disclaimer (printed under the signature)',
    'settings.nextJob': 'Next job #', 'settings.nextInvoice': 'Next invoice # (one sequence, all companies)', 'settings.nextStockPo': 'Next stock PO #',
    'settings.numberingHint': 'Numbers are given out by the database and only move forward. Job POs use the job number (100042-101, -102…). Voided invoice numbers are kept and never reused.',
    'settings.defaults': 'Defaults', 'settings.terms_days': 'Default payment terms', 'settings.dueSoonDays': 'Service due-soon warning', 'settings.dueSoonKm': 'Service due-soon distance',
    'settings.defaultsHint': 'Each company can have its own payment terms; this is used when it has none.',
    'settings.shopSupplies': 'Shop supplies fee', 'settings.ssEnabled': 'Add a shop supplies fee to every new job', 'settings.ssType': 'Type',
    'settings.ssPercent': 'Percentage', 'settings.ssFixed': 'Fixed amount', 'settings.ssRate': 'Rate', 'settings.ssAmount': 'Amount',
    'settings.ssBase': 'Calculated on', 'settings.base.parts_labor': 'Parts + labor, after line discounts', 'settings.base.parts': 'Parts only', 'settings.base.labor': 'Labor only',
    'settings.ssMin': 'Minimum', 'settings.ssMax': 'Maximum', 'settings.ssTaxable': 'Shop supplies fee is taxable',
    'settings.ssHint': 'New jobs copy this rate; it can be changed on each job. Open estimates still on the old default follow a change here.',
    'settings.ssExample': 'Example: on {base} of parts and labor, {rate}% gives {fee}.',
    'settings.tax': 'Tax', 'settings.taxName': 'Tax name', 'settings.taxRate': 'Rate', 'settings.newItems': 'New catalog items',
    'settings.notTaxable': 'Not taxable', 'settings.taxable': 'Taxable',
    'settings.nonPkpNote': 'The shop is set to Non-PKP, so no PPN is charged on any job, whatever the rate above.',
    'tz.Asia/Jakarta': 'WIB · Asia/Jakarta', 'tz.Asia/Makassar': 'WITA · Asia/Makassar', 'tz.Asia/Jayapura': 'WIT · Asia/Jayapura',

    'labor.add': 'Add rate', 'labor.edit': 'Edit labor rate', 'labor.none': 'No labor rates yet.', 'labor.default': 'Default', 'labor.inactive': 'Off',
    'labor.perHour': '{amount} / hour', 'labor.name': 'Name', 'labor.namePh': 'e.g. Standard', 'labor.rate': 'Rate per hour', 'labor.hour': '/ hour',
    'labor.makeDefault': 'Default rate for new labor items', 'labor.activeLabel': 'Available on new items',
    'labor.nameRequired': 'Enter a name.', 'labor.rateRequired': 'Enter a rate of 0 or more.', 'labor.defaultActive': 'The default rate must be available.',
    'labor.saved': 'Labor rate saved', 'labor.deleted': 'Labor rate deleted',
    'labor.inUse': 'This rate is used by catalog items, so it can\'t be deleted. Switch off "Available on new items" instead.',
    'labor.hint': 'Labor items in the catalog use one of these rates. Changing a rate affects new lines only.',

    'users.invite': 'Invite user', 'users.sendInvite': 'Send invite', 'users.person': 'Person', 'users.username': 'Username', 'users.role': 'Role', 'users.status': 'Status',
    'users.status.active': 'Active', 'users.status.invited': 'Waiting', 'users.status.disabled': 'Disabled',
    'users.activate': 'Activate', 'users.disable': 'Disable', 'users.you': 'you', 'users.updated': '{name} updated',
    'users.rolesTitle': 'What each role can do',
    'users.desc.owner': 'Everything, including settings, users, voiding invoices, issuing and refunding credits, changing payments on issued invoices, and making or removing Owners',
    'users.desc.admin': 'The same as an Owner, except they can\'t change, disable or remove an Owner, or make someone an Owner',
    'users.desc.advisor': 'Jobs, invoices, payments, customers, catalog and inventory',
    'users.desc.technician': 'View only (assigned on jobs and the calendar)',
    'users.desc.viewer': 'View only',
    'users.desc.fleet': 'No access yet (planned: approve their own company\'s work)',
    'users.hint': 'Detailed per-permission settings come later. People are invited by an admin; public sign-up is off. You can\'t change your own role or status.',
    'users.fullName': 'Full name', 'users.email': 'Email', 'users.phone': 'Phone (optional)', 'users.pickRole': 'Choose a role…',
    'users.usernameHint': 'Used to sign in. Letters, numbers, dot, dash or underscore.',
    'users.usernameRule': 'Usernames are 3–30 characters: letters, numbers, dot, dash or underscore.',
    'users.inviteRequired': 'Fill in name, email, username and role.',
    'users.inviteHint': 'They get an email with a link to choose their password, then sign in with their username.',
    'users.invited': 'Invite sent to {email}',
    'settings.badAmount': 'Enter an amount like 10.000, or leave empty',
    'labor.confirmDelete': 'Yes, delete this rate',
    'users.lastOwner': 'This is the only active Owner. Make someone else an Owner first.',
    'users.confirmTitle': 'Please confirm', 'users.confirmYes': 'Yes, continue',
    'users.confirmDisable': '{name} will be signed out of Axle and can\'t sign in again until someone activates the account.',
    'users.confirmOwner': '{name} will become an Owner, with full access to everything including users and settings.',
    'nav.language': 'Language', 'nav.main': 'Main menu',
    'users.remove': 'Remove', 'users.removeWho': 'Remove {name}',
    'users.confirmRemove': '{name} will be removed from Axle completely and can\'t sign in again. This only works for people with no work recorded yet; otherwise disable them instead.',
    'users.confirmRemoveYes': 'Yes, remove', 'users.removed': '{name} removed',
  },

  id: {
    'common.cancel': 'Batal', 'common.close': 'Tutup', 'common.save': 'Simpan', 'common.delete': 'Hapus', 'common.edit': 'Ubah',
    'common.remove': 'Hapus', 'common.loading': 'Memuat…', 'common.soon': 'Segera', 'common.days': 'hari',

    'err.permission': 'Anda tidak punya izin untuk melakukan ini.',
    'err.duplicate': 'Nilai itu sudah dipakai.',
    'err.network': 'Tidak dapat terhubung ke server. Periksa koneksi lalu coba lagi.',

    'nav.dashboard': 'Dasbor', 'nav.board': 'Papan Kerja', 'nav.calendar': 'Kalender', 'nav.customers': 'Pelanggan',
    'nav.catalog': 'Katalog', 'nav.inventory': 'Inventaris', 'nav.reports': 'Laporan', 'nav.settings': 'Pengaturan',
    'nav.vehicles': 'Kendaraan', 'nav.jobs': 'Pekerjaan', 'nav.search': 'Cari pelanggan, kendaraan & pekerjaan',
    'nav.notifications': 'Notifikasi', 'nav.account': 'Akun saya',

    'create.title': 'Buat baru', 'create.job': 'Pekerjaan baru', 'create.customer': 'Pelanggan baru', 'create.vehicle': 'Kendaraan baru',
    'create.appointment': 'Janji servis baru', 'create.po': 'Purchase order baru',

    'notif.title': 'Notifikasi', 'notif.markAll': 'Tandai semua sudah dibaca', 'notif.empty': 'Tidak ada notifikasi baru.',

    'role.Owner': 'Pemilik', 'role.Admin': 'Admin', 'role.Service advisor': 'Service advisor', 'role.Technician': 'Teknisi',
    'role.Viewer': 'Hanya lihat', 'role.Fleet manager': 'Fleet manager',

    'auth.signInTitle': 'Masuk', 'auth.username': 'Username atau email', 'auth.password': 'Kata sandi', 'auth.signIn': 'Masuk',
    'auth.signOut': 'Keluar', 'auth.forgot': 'Lupa kata sandi?', 'auth.fillBoth': 'Masukkan username dan kata sandi.',
    'auth.badLogin': 'Username atau kata sandi salah.', 'auth.inviteOnly': 'Akun dibuat oleh admin bengkel.',
    'auth.linkInvalid': 'Tautan sudah kedaluwarsa atau sudah dipakai. Silakan masuk, atau minta tautan baru.',
    'auth.forgotTitle': 'Atur ulang kata sandi', 'auth.forgotText': 'Masukkan alamat email akun Anda, dan kami akan mengirim tautan untuk membuat kata sandi baru.',
    'auth.email': 'Email', 'auth.enterEmail': 'Masukkan alamat email Anda.', 'auth.sendLink': 'Kirim tautan',
    'auth.checkEmail': 'Periksa email Anda', 'auth.resetSent': 'Jika {email} terdaftar, tautan untuk mengatur ulang kata sandi sedang dikirim.',
    'auth.backToLogin': 'Kembali ke halaman masuk',
    'auth.setTitle': 'Buat kata sandi', 'auth.setText': 'Buat kata sandi untuk akun Anda.',
    'auth.setTextUser': 'Buat kata sandi. Anda akan masuk dengan username {username}.',
    'auth.newPassword': 'Kata sandi baru', 'auth.confirmPassword': 'Ulangi kata sandi', 'auth.savePassword': 'Simpan kata sandi',
    'auth.pwTooShort': 'Gunakan minimal 8 karakter.', 'auth.pwMismatch': 'Kedua kata sandi tidak sama.',

    'pending.invited.title': 'Menunggu persetujuan', 'pending.invited.text': 'Akun Anda sudah dibuat, tetapi masih harus diaktifkan oleh admin bengkel. Anda bisa memakai Axle setelah diaktifkan.',
    'pending.disabled.title': 'Akun dinonaktifkan', 'pending.disabled.text': 'Akun ini telah dinonaktifkan. Hubungi admin bengkel jika menurut Anda ini keliru.',
    'pending.fleet.title': 'Belum ada akses', 'pending.fleet.text': 'Akun fleet manager belum bisa membuka Axle. Persetujuan pekerjaan untuk perusahaan sendiri direncanakan di tahap berikutnya.',
    'pending.missing.title': 'Akun belum disiapkan', 'pending.missing.text': 'Profil untuk login ini tidak ditemukan. Minta admin bengkel memeriksa akun Anda.',
    'pending.signedInAs': 'Masuk sebagai {who}', 'pending.check': 'Periksa lagi',

    'profile.title': 'Profil saya', 'profile.name': 'Nama', 'profile.username': 'Username', 'profile.usernameHint': 'Minta admin untuk mengubahnya.',
    'profile.phone': 'Telepon', 'profile.language': 'Bahasa', 'profile.languageShop': 'Sesuai bengkel', 'profile.changePassword': 'Ganti kata sandi',
    'profile.passwordHint': 'Kosongkan jika tidak ingin mengganti kata sandi.', 'profile.nameRequired': 'Masukkan nama Anda.',

    'stage.foundations': 'Fondasi: masuk, tata letak aplikasi, pengaturan', 'stage.customers': 'Pelanggan & kendaraan', 'stage.catalog': 'Katalog',
    'stage.jobs': 'Pekerjaan, estimasi, invoice & pembayaran', 'stage.print': 'Cetak invoice & estimasi', 'stage.board': 'Papan kerja & kalender',
    'stage.inventory': 'Inventaris & purchase order', 'stage.schedules': 'Jadwal servis berkala', 'stage.reports': 'Dasbor & laporan',
    'soon.title': 'Hadir di tahap berikutnya', 'soon.text': 'Layar ini dibangun di tahap {stage}: {name}.',

    'dash.hello': 'Selamat datang, {name}', 'dash.sub': 'Pratinjau Axle v2, terhubung ke database staging',
    'dash.buildTitle': 'Yang sudah dibangun', 'dash.buildText': 'Axle dibangun bertahap. Dasbor diisi di tahap terakhir, setelah ada pekerjaan dan invoice untuk ditampilkan.',
    'dash.ready': 'siap dicoba', 'dash.startHere': 'Mulai dengan mengisi data bengkel di',

    'search.title': 'Pencarian', 'search.for': 'Hasil untuk "{q}"', 'search.soon': 'Pencarian mencakup pelanggan, kendaraan, dan pekerjaan, jadi hadir bersama layar-layar itu.',
    'notFound.title': 'Halaman tidak ditemukan', 'notFound.text': 'Alamat itu tidak cocok dengan halaman mana pun di Axle.', 'notFound.home': 'Ke dasbor',

    'settings.sub': 'Perubahan berlaku untuk semua pengguna', 'settings.readOnly': 'Hanya pemilik atau admin yang bisa mengubah pengaturan ini',
    'settings.save': 'Simpan perubahan', 'settings.saved': 'Pengaturan disimpan', 'settings.discard': 'Batalkan', 'settings.unsaved': 'Ada perubahan yang belum disimpan',
    'settings.fixErrors': 'Beberapa isian perlu diperbaiki dulu.', 'settings.notLoaded': 'Pengaturan bengkel tidak dapat dimuat. Muat ulang halaman; jika terus terjadi, database mungkin belum disiapkan.',
    'settings.required': 'Wajib diisi', 'settings.badNumber': 'Masukkan angka 0 atau lebih', 'settings.max100': 'Tidak boleh lebih dari 100',
    'settings.minMax': 'Maksimum harus sama atau lebih besar dari minimum', 'settings.badEmail': 'Alamat email tidak valid.',
    'settings.nav.shop': 'Profil bengkel', 'settings.nav.language': 'Bahasa & cetak', 'settings.nav.numbering': 'Invoice & penomoran',
    'settings.nav.fees': 'Biaya & pajak', 'settings.nav.labor': 'Tarif jasa', 'settings.nav.users': 'Pengguna & akses',
    'settings.uploadLogo': 'Unggah logo', 'settings.replaceLogo': 'Ganti logo', 'settings.logoHint': 'PNG, SVG, JPG atau WebP maks. 2 MB · tampil di header aplikasi dan dokumen cetak',
    'settings.logoType': 'Gunakan gambar PNG, SVG, JPG atau WebP.', 'settings.logoSize': 'Ukuran logo maksimal 2 MB.', 'settings.logoSaved': 'Logo diperbarui',
    'settings.shopName': 'Nama bengkel (aplikasi & dokumen)', 'settings.legalName': 'Nama badan usaha', 'settings.phone': 'Telepon', 'settings.address': 'Alamat',
    'settings.email': 'Email', 'settings.bank': 'Rekening bank untuk invoice', 'settings.npwpHint': '15 atau 16 digit',
    'settings.pkp': 'Status PKP', 'settings.pkp.unknown': 'Belum diatur', 'settings.pkp.pkp': 'PKP (memungut PPN)', 'settings.pkp.non_pkp': 'Non-PKP (tanpa PPN)',
    'settings.pkpHint': 'PPN berjalan normal sampai diatur; Non-PKP mematikan PPN',
    'settings.appLang': 'Bahasa aplikasi (bawaan pengguna baru)', 'settings.printLang': 'Bahasa cetak bawaan', 'settings.timezone': 'Zona waktu bengkel',
    'settings.langHint': 'Setiap pengguna bisa memilih EN / ID di bilah atas. Bahasa cetak bisa diganti setiap kali mencetak. Jatuh tempo dan "servis jatuh tempo" memakai zona waktu bengkel.',
    'settings.terms': 'Syarat & ketentuan (dicetak di bawah tanda tangan)',
    'settings.nextJob': 'No. pekerjaan berikutnya', 'settings.nextInvoice': 'No. invoice berikutnya (satu urutan, semua perusahaan)', 'settings.nextStockPo': 'No. PO stok berikutnya',
    'settings.numberingHint': 'Nomor diberikan oleh database dan hanya maju. PO pekerjaan memakai nomor pekerjaan (100042-101, -102…). Nomor invoice yang dibatalkan disimpan dan tidak dipakai lagi.',
    'settings.defaults': 'Bawaan', 'settings.terms_days': 'Termin pembayaran bawaan', 'settings.dueSoonDays': 'Peringatan servis segera', 'settings.dueSoonKm': 'Jarak peringatan servis',
    'settings.defaultsHint': 'Setiap perusahaan bisa punya termin sendiri; ini dipakai jika tidak ada.',
    'settings.shopSupplies': 'Biaya bahan habis pakai', 'settings.ssEnabled': 'Tambahkan biaya bahan habis pakai ke setiap pekerjaan baru', 'settings.ssType': 'Jenis',
    'settings.ssPercent': 'Persentase', 'settings.ssFixed': 'Jumlah tetap', 'settings.ssRate': 'Tarif', 'settings.ssAmount': 'Jumlah',
    'settings.ssBase': 'Dihitung dari', 'settings.base.parts_labor': 'Suku cadang + jasa, setelah diskon baris', 'settings.base.parts': 'Suku cadang saja', 'settings.base.labor': 'Jasa saja',
    'settings.ssMin': 'Minimum', 'settings.ssMax': 'Maksimum', 'settings.ssTaxable': 'Biaya bahan habis pakai kena pajak',
    'settings.ssHint': 'Pekerjaan baru menyalin tarif ini; bisa diubah per pekerjaan. Estimasi terbuka yang masih memakai tarif lama ikut berubah.',
    'settings.ssExample': 'Contoh: dari {base} suku cadang dan jasa, {rate}% menjadi {fee}.',
    'settings.tax': 'Pajak', 'settings.taxName': 'Nama pajak', 'settings.taxRate': 'Tarif', 'settings.newItems': 'Item katalog baru',
    'settings.notTaxable': 'Tidak kena pajak', 'settings.taxable': 'Kena pajak',
    'settings.nonPkpNote': 'Bengkel diatur sebagai Non-PKP, jadi tidak ada PPN di pekerjaan mana pun, berapa pun tarif di atas.',

    'labor.add': 'Tambah tarif', 'labor.edit': 'Ubah tarif jasa', 'labor.none': 'Belum ada tarif jasa.', 'labor.default': 'Bawaan', 'labor.inactive': 'Nonaktif',
    'labor.perHour': '{amount} / jam', 'labor.name': 'Nama', 'labor.namePh': 'mis. Standar', 'labor.rate': 'Tarif per jam', 'labor.hour': '/ jam',
    'labor.makeDefault': 'Tarif bawaan untuk item jasa baru', 'labor.activeLabel': 'Tersedia untuk item baru',
    'labor.nameRequired': 'Masukkan nama.', 'labor.rateRequired': 'Masukkan tarif 0 atau lebih.', 'labor.defaultActive': 'Tarif bawaan harus tersedia.',
    'labor.saved': 'Tarif jasa disimpan', 'labor.deleted': 'Tarif jasa dihapus',
    'labor.inUse': 'Tarif ini dipakai item katalog, jadi tidak bisa dihapus. Matikan "Tersedia untuk item baru" sebagai gantinya.',
    'labor.hint': 'Item jasa di katalog memakai salah satu tarif ini. Perubahan tarif hanya berlaku untuk baris baru.',

    'users.invite': 'Undang pengguna', 'users.sendInvite': 'Kirim undangan', 'users.person': 'Nama', 'users.username': 'Username', 'users.role': 'Peran', 'users.status': 'Status',
    'users.status.active': 'Aktif', 'users.status.invited': 'Menunggu', 'users.status.disabled': 'Nonaktif',
    'users.activate': 'Aktifkan', 'users.disable': 'Nonaktifkan', 'users.you': 'Anda', 'users.updated': '{name} diperbarui',
    'users.rolesTitle': 'Hak setiap peran',
    'users.desc.owner': 'Semuanya, termasuk pengaturan, pengguna, membatalkan invoice, menerbitkan dan mengembalikan kredit, mengubah pembayaran pada invoice terbit, serta menambah atau menghapus Pemilik',
    'users.desc.admin': 'Sama seperti Pemilik, kecuali tidak bisa mengubah, menonaktifkan atau menghapus Pemilik, atau menjadikan seseorang Pemilik',
    'users.desc.advisor': 'Pekerjaan, invoice, pembayaran, pelanggan, katalog dan inventaris',
    'users.desc.technician': 'Hanya lihat (ditugaskan di pekerjaan dan kalender)',
    'users.desc.viewer': 'Hanya lihat',
    'users.desc.fleet': 'Belum ada akses (rencana: menyetujui pekerjaan perusahaannya sendiri)',
    'users.hint': 'Pengaturan izin terperinci menyusul. Pengguna diundang oleh admin; pendaftaran umum dimatikan. Anda tidak bisa mengubah peran atau status Anda sendiri.',
    'users.fullName': 'Nama lengkap', 'users.email': 'Email', 'users.phone': 'Telepon (opsional)', 'users.pickRole': 'Pilih peran…',
    'users.usernameHint': 'Dipakai untuk masuk. Huruf, angka, titik, tanda hubung atau garis bawah.',
    'users.usernameRule': 'Username 3–30 karakter: huruf, angka, titik, tanda hubung atau garis bawah.',
    'users.inviteRequired': 'Isi nama, email, username dan peran.',
    'users.inviteHint': 'Mereka akan menerima email berisi tautan untuk membuat kata sandi, lalu masuk dengan username.',
    'users.invited': 'Undangan dikirim ke {email}',
    'settings.badAmount': 'Masukkan jumlah seperti 10.000, atau kosongkan',
    'labor.confirmDelete': 'Ya, hapus tarif ini',
    'users.lastOwner': 'Ini satu-satunya Pemilik yang aktif. Jadikan orang lain Pemilik terlebih dahulu.',
    'users.confirmTitle': 'Mohon konfirmasi', 'users.confirmYes': 'Ya, lanjutkan',
    'users.confirmDisable': '{name} akan dikeluarkan dari Axle dan tidak bisa masuk lagi sampai akunnya diaktifkan.',
    'users.confirmOwner': '{name} akan menjadi Pemilik, dengan akses penuh termasuk pengguna dan pengaturan.',
    'nav.language': 'Bahasa', 'nav.main': 'Menu utama',
    'users.remove': 'Hapus', 'users.removeWho': 'Hapus {name}',
    'users.confirmRemove': '{name} akan dihapus sepenuhnya dari Axle dan tidak bisa masuk lagi. Ini hanya bisa untuk orang yang belum punya catatan pekerjaan; jika sudah, nonaktifkan saja.',
    'users.confirmRemoveYes': 'Ya, hapus', 'users.removed': '{name} dihapus',
  },
}

export const dict = {
  en: { ...base.en, ...customersEn },
  id: { ...base.id, ...customersId },
}
