// Screen text for stage 3: Catalog, plus the Appearance (colour theme) settings (English / Bahasa Indonesia).
export const catalogEn = {
  // Appearance
  'settings.nav.appearance': 'Appearance',
  'theme.intro': 'Choose the colour used for the top bar, buttons and links. Everyone in the shop sees the same colours.',
  'theme.teal': 'Teal', 'theme.ocean': 'Ocean', 'theme.indigo': 'Indigo', 'theme.purple': 'Purple', 'theme.crimson': 'Crimson',
  'theme.orange': 'Orange', 'theme.forest': 'Forest', 'theme.graphite': 'Graphite', 'theme.custom': 'Custom',
  'theme.pick': 'Pick a colour', 'theme.hex': 'Colour code',
  'theme.hint': 'You see the new colours straight away; they are kept for everyone once you save.',
  'theme.lowContrast': 'This colour is quite light, so white text on it may be hard to read. A darker shade works better.',
  'theme.badHex': 'Enter a colour code like #0E9F7E.',
  'theme.tooLight': 'This colour is too light for white text. Pick a darker shade.',
  'create.part': 'New part',

  // Tabs
  'cat.tab.labor': 'Labor', 'cat.tab.parts': 'Parts', 'cat.tab.fees': 'Fees', 'cat.tab.flat-rate': 'Flat rate items', 'cat.tab.discounts': 'Discounts',
  'cat.tab.bundles': 'Service bundles', 'cat.tab.inspections': 'Inspections', 'cat.tab.checklists': 'Checklists', 'cat.tab.categories': 'Categories',
  'cat.tab.suppliers': 'Suppliers',
  'cat.sub.labor': 'Labor operations priced by hours × labor rate',
  'cat.sub.parts': 'Parts you sell; tires are a part category',
  'cat.sub.fees': 'Charges such as disposal fees, added by hand or automatically with an item',
  'cat.sub.flat-rate': 'A set of labor and parts sold for one fixed price',
  'cat.sub.discounts': 'Ready-made discounts for whole jobs or single services',
  'cat.sub.bundles': 'A set of labor and parts added together, each charged at its own price',
  'cat.sub.inspections': 'Points a technician checks, with ready-made notes',
  'cat.sub.checklists': 'Ordered sets of inspection points',
  'cat.sub.categories': 'Groups for labor, parts and fees; used for filtering and reports',
  'cat.sub.suppliers': 'Where parts come from, and outside shops for sublet work',
  'cat.add.labor': 'Labor', 'cat.add.parts': 'Part', 'cat.add.fees': 'Fee', 'cat.add.flat-rate': 'Flat rate item', 'cat.add.discounts': 'Discount',
  'cat.add.bundles': 'Bundle', 'cat.add.inspections': 'Inspection point', 'cat.add.checklists': 'Checklist', 'cat.add.categories': 'Category',
  'cat.add.suppliers': 'Supplier',
  'cat.new.labor': 'New labor', 'cat.new.part': 'New part', 'cat.new.fee': 'New fee', 'cat.new.flat': 'New flat rate item', 'cat.new.bundle': 'New service bundle',
  'cat.new.discount': 'New discount', 'cat.new.inspection': 'New inspection point', 'cat.new.checklist': 'New checklist', 'cat.new.category': 'New category',
  'cat.new.supplier': 'New supplier',
  'cat.search.labor': 'Search labor name or code', 'cat.search.parts': 'Search part name or number', 'cat.search.fees': 'Search fees',
  'cat.search.templates': 'Search name or tag', 'cat.search.discounts': 'Search discounts', 'cat.search.inspections': 'Search inspection points',
  'cat.search.checklists': 'Search checklists', 'cat.search.categories': 'Search categories', 'cat.search.suppliers': 'Search name, contact, phone or account #',
  'cat.empty.labor': 'No labor yet', 'cat.empty.parts': 'No parts yet', 'cat.empty.fees': 'No fees yet', 'cat.empty.flat-rate': 'No flat rate items yet',
  'cat.empty.discounts': 'No discounts yet', 'cat.empty.bundles': 'No service bundles yet', 'cat.empty.inspections': 'No inspection points yet',
  'cat.empty.checklists': 'No checklists yet', 'cat.empty.categories': 'No categories yet', 'cat.empty.suppliers': 'No suppliers yet',
  'cat.emptyText.labor': 'Add the jobs you do often, such as "Oil change" or "Brake pad replacement", so they can be added to estimates in one click.',
  'cat.emptyText.parts': 'Add the parts you stock or order often. Their price, cost and stock are kept here.',
  'cat.emptyText.fees': 'Add charges such as a battery disposal fee. A fee can be added automatically whenever a part or labor is used.',
  'cat.emptyText.flat-rate': 'Combine labor and parts into one package with a fixed price, such as "Minor service".',
  'cat.emptyText.discounts': 'Save the discounts you give often, such as a fleet discount, so they can be picked on a job.',
  'cat.emptyText.bundles': 'Group labor and parts that usually go together, so they can be added to a job in one go.',
  'cat.emptyText.inspections': 'Add the points a technician checks, such as "Front brake pads", with ready-made notes for good, soon and urgent.',
  'cat.emptyText.checklists': 'Put inspection points in order to make a checklist, such as "30-point inspection". Add inspection points first.',
  'cat.emptyText.categories': 'Categories group labor, parts and fees, such as "Engine › Filters".',
  'cat.emptyText.suppliers': 'Add the shops you buy parts from, and outside workshops you send sublet work to.',
  'cat.listHint.labor': 'Labor rates are set in Settings → Labor rates.',
  'cat.listHint.parts': 'Red stock means it is at or below the reorder point.',
  'cat.listHint.fees': 'Percent fees are worked out from the job when they are added.',
  'cat.listHint.flat-rate': 'The job shows one price; the lines inside are kept for stock and reports.',
  'cat.listHint.bundles': 'Each line keeps its own price on the job and can still be changed there.',
  'cat.listHint.discounts': 'Discounts are picked on a job; changing one here doesn\'t change jobs that already use it.',
  'cat.listHint.inspections': 'Green means good, yellow means needed soon, red means needed now.',
  'cat.listHint.checklists': 'A checklist can be attached to a service bundle or flat rate item.',
  'cat.listHint.categories': 'A category can sit under another one, such as Engine › Filters.',
  'cat.listHint.suppliers': 'Parts suppliers are used on purchase orders; sublet shops do outside work for you.',

  // Shared
  'cat.name': 'Name', 'cat.code': 'Code', 'cat.partNo': 'Part #', 'cat.category': 'Category', 'cat.categoryAll': 'Category: all', 'cat.supplier': 'Supplier',
  'cat.brand': 'Brand', 'cat.description': 'Description', 'cat.descriptionHint': 'Shown on the estimate and invoice under the name.',
  'cat.cost': 'Cost', 'cat.price': 'Price', 'cat.core': 'Core', 'cat.onHand': 'On hand', 'cat.tax': 'Tax', 'cat.yes': 'Yes', 'cat.no': 'No',
  'cat.hours': 'Hours', 'cat.hoursShort': 'h', 'cat.rate': 'Rate', 'cat.value': 'Value', 'cat.feeKind': 'Type', 'cat.feeKind.fixed': 'Fixed amount',
  'cat.feeKind.percent': 'Percent of job', 'cat.autoAddedTo': 'Auto-added to', 'cat.itemsCount': '{n} items', 'cat.status': 'Status',
  'cat.statusActive': 'Active', 'cat.statusInactive': 'Inactive', 'cat.statusAll': 'All', 'cat.inactive': 'Inactive', 'cat.activeLabel': 'Active (can be added to jobs)',
  'cat.notFound': 'This record no longer exists', 'cat.viewOnly': 'You can view the catalog but not change it.',
  'cat.create': 'Create', 'cat.confirmDelete': 'Yes, delete', 'cat.saved': '{name} saved', 'cat.deleted': '{name} deleted',
  'cat.inUse': 'This is used on jobs, orders or other catalog records, so it can\'t be deleted. Switch off "Active" to hide it instead.',
  'cat.loadFailed': 'Part of the catalog couldn\'t be loaded: {error}', 'cat.settings': 'Settings', 'cat.notes': 'Internal notes',
  'cat.notesHint': 'Only staff see these.', 'cat.dupName': 'This name is already used.', 'cat.dupCode': 'Also used by {name}.',
  'cat.moveUp': 'Move {name} up', 'cat.moveDown': 'Move {name} down', 'cat.removeRow': 'Remove {name}', 'cat.total': 'Total',

  // Items
  'cat.pricing': 'Pricing', 'cat.laborRate': 'Labor rate', 'cat.hoursTimesRate': 'Hours × rate.', 'cat.differsFromRate': 'Hours × rate would be {amount}.',
  'cat.pickRate': 'Pick a rate and hours to work out the price.', 'cat.costOptional': 'Cost (optional)', 'cat.laborCostHint': 'What the work costs the shop, for profit reports.',
  'cat.markup': 'Markup', 'cat.markupHint': 'Change cost or markup and the price follows.', 'cat.margin': 'Margin {pct}%', 'cat.defaultQty': 'Default qty',
  'cat.amount': 'Amount', 'cat.percent': 'Percent', 'cat.percentFeeHint': 'Of the job\'s labor and parts.',
  'cat.hasCore': 'Has a core charge', 'cat.coreCharge': 'Core charge', 'cat.coreHint': 'Billed with the part and refunded by the supplier when the old core is returned.',
  'cat.tireSize': 'Tire size (optional)', 'cat.tireHint': 'Fill in for tires so they can be found by size.',
  'cat.autoFees': 'Auto-added fees', 'cat.noFees': 'No fees yet. Add them in the Fees tab.', 'cat.autoFeesHint': 'These fees are added to the job with this item, with the same quantity.',
  'cat.inventory': 'Inventory', 'cat.trackInventory': 'Track stock for this part', 'cat.trackLocked': 'Stock tracking stays on while there is stock on hand.',
  'cat.openingStock': 'Opening stock', 'cat.onEstimates': 'On estimates', 'cat.available': 'Available', 'cat.reorderAt': 'Reorder at',
  'cat.openingHint': 'How many you have now. Later changes go through purchase orders and stock adjustments.',
  'cat.stockHint': 'Stock changes through jobs, purchase orders and returns. Owners and Admins can correct the count with Adjust stock.',
  'cat.openingNote': 'Opening stock', 'cat.openingFailed': 'The part was saved but its opening stock wasn\'t: {error}',
  'cat.taxable': 'Taxable ({tax} {rate}%)', 'cat.showOnInvoice': 'Show on estimate & invoice', 'cat.showQtyPrice': 'Show qty and unit price',
  'cat.showHoursRate': 'Show hours and rate', 'cat.markupRule': 'Between -100 and 1000%.', 'cat.qtyRule': 'From 0,01 up to 10.000.', 'cat.hoursRule': 'Between 0 and 1000 hours.',

  // Flat rate items & bundles
  'cat.tags': 'Tags', 'cat.tagsHint': 'Separate with commas, e.g. "service, 10.000 km".', 'cat.lines': 'Lines', 'cat.linesN': '{n} lines',
  'cat.itemsValue': 'Lines value', 'cat.flatPrice': 'Flat price', 'cat.interval': 'Repeat every', 'cat.monthsN': '{n} months', 'cat.monthsShort': 'months',
  'cat.noLines': 'No lines yet. Pick labor or parts below.', 'cat.addLine': '+ Add labor, part or fee…', 'cat.catalogPrice': 'catalog {amount}',
  'cat.qty': 'Qty', 'cat.qtyFor': 'Quantity for {name}', 'cat.priceFor': 'Price for {name} (blank = catalog price)',
  'cat.flatSaves': 'Customer saves', 'cat.flatAbove': 'Above the lines value by',
  'cat.flatHint': 'The job shows the flat price; it is spread over the lines for reports.',
  'cat.bundleHint': 'Leave a price blank to use the catalog price at the time it is added.',
  'cat.afterService': 'Checklist and reminders', 'cat.checklist': 'Inspection checklist', 'cat.noChecklist': 'No checklist',
  'cat.checklistHint': 'Added to the job with this service for the technician to fill in.',
  'cat.everyKm': 'Repeat every (km)', 'cat.everyMonths': 'Repeat every (months)',
  'cat.intervalHint': 'Suggested service schedule for the vehicle once this is done. Leave blank for none.',
  'cat.kmRule': 'Whole kilometres, 1 to 1.000.000.', 'cat.monthsRule': 'Whole months, 1 to 120.', 'cat.needLine': 'Add at least one line.',
  'cat.linesFailed': 'Saved, but the lines couldn\'t all be saved: {error}',

  // Discounts
  'cat.appliesTo': 'Applies to', 'cat.level.job': 'Whole job', 'cat.level.service': 'One service',
  'cat.levelHint.job': 'Taken off the job total.', 'cat.levelHint.service': 'Taken off one service on the job.',
  'cat.discountKind': 'Type', 'cat.kind.percent': 'Percent', 'cat.kind.amount': 'Fixed amount', 'cat.maxDiscount': 'Max',
  'cat.maxDiscountOptional': 'Maximum (optional)', 'cat.maxHint': 'The discount never goes over this amount.', 'cat.valid': 'Valid',
  'cat.validFrom': 'From', 'cat.validTo': 'Until', 'cat.validHint': 'Leave blank to use it any time.', 'cat.always': 'Any time',
  'cat.state.running': 'Active', 'cat.state.scheduled': 'Not started', 'cat.state.expired': 'Ended', 'cat.state.inactive': 'Off',
  'cat.percentRule': 'More than 0 and up to 100.', 'cat.dateOrder': 'Must be on or after the start date.', 'cat.discountExample': 'e.g. Fleet discount 10%',

  // Inspections
  'cat.group': 'Group', 'cat.groupAll': 'Group: all', 'cat.groupExample': 'e.g. Brakes', 'cat.groupHint': 'Points in the same group are shown together.',
  'cat.noGroup': 'No group', 'cat.cannedNotes': 'Ready-made notes', 'cat.inChecklists': 'In checklists', 'cat.inspExample': 'e.g. Front brake pads',
  'cat.flag.green': 'Good', 'cat.flag.yellow': 'Soon', 'cat.flag.red': 'Now', 'cat.flagFor': 'Colour for note {note}',
  'cat.notePlaceholder.green': 'e.g. Pads in good condition', 'cat.notePlaceholder.yellow': 'e.g. Pads at 30%, replace soon',
  'cat.notePlaceholder.red': 'e.g. Pads worn out, replace now', 'cat.noteN': 'Note {n}', 'cat.noNotes': 'No notes yet.', 'cat.addNote': 'Add note',
  'cat.notesHint2': 'The technician picks one of these instead of typing. Empty notes are left out.',
  'cat.notesFailed': 'Saved, but the notes couldn\'t all be saved: {error}', 'cat.deleteRemoves': 'Deleting this point also removes it from these checklists.',

  // Checklists
  'cat.points': 'Points', 'cat.pointsN': '{n} points', 'cat.pointsTitle': 'Inspection points ({n})', 'cat.usedByBundles': 'Used by',
  'cat.noPoints': 'No points yet.', 'cat.addPoint': '+ Add inspection point…', 'cat.addGroup': '+ Add a whole group…',
  'cat.noInspItems': 'Add inspection points in the Inspections tab first.', 'cat.needPoint': 'Add at least one inspection point.',
  'cat.checklistExample': 'e.g. 30-point inspection',

  // Categories
  'cat.usedFor': 'Used for', 'cat.usedForAll': 'Used for: all', 'cat.applies.part': 'Parts', 'cat.applies.labor': 'Labor', 'cat.applies.fee': 'Fees',
  'cat.applies.any': 'Anything', 'cat.itemsCol': 'Items', 'cat.subcategories': 'Subcategories', 'cat.subsCount': '{n} subcategories',
  'cat.parent': 'Inside', 'cat.topLevel': 'Top level', 'cat.parentHint': 'Put it inside another category, e.g. Filters inside Engine.',
  'cat.categoryExample': 'e.g. Filters', 'cat.categoryInUse': 'Categories with items or subcategories can\'t be deleted; move those first.',
  'cat.appliesMismatch': 'This category has items of another type ({n}). Choose "Anything" or move them first.',

  // Suppliers
  'cat.supplierType': 'Type', 'cat.typeAll': 'Type: all', 'cat.stype.internal': 'Parts supplier', 'cat.stype.sublet': 'Sublet shop',
  'cat.stypeHint.internal': 'You buy parts from them.', 'cat.stypeHint.sublet': 'They do outside work for you, e.g. machining.',
  'cat.contact': 'Contact', 'cat.contactName': 'Contact person', 'cat.partsCol': 'Parts', 'cat.cod': 'Cash', 'cat.daysN': '{n} days',
  'cat.termsDays': 'Payment terms', 'cat.termsCol': 'Terms', 'cat.termsHint': '0 means cash on delivery.', 'cat.accountNo': 'Our account #',
  'cat.accountHint': 'The account number they gave your shop.', 'cat.pinnedNotes': 'Pinned note',
  'cat.pinnedHint': 'Shown at the top whenever this supplier is opened, e.g. "Order before 2 pm for same-day delivery".',
  'cat.suppliedParts': 'Parts from this supplier ({n})',
  // Update 3: history, stock adjustment, copying notes
  'cat.hist.section': 'History', 'cat.hist.title': 'Edit history', 'cat.hist.show': 'Show edit history', 'cat.hist.hide': 'Hide',
  'cat.hist.none': 'No changes recorded yet.', 'cat.hist.system': 'System', 'cat.hist.created': 'Created', 'cat.hist.deleted': 'Deleted',
  'cat.hist.lineAdd': 'Added', 'cat.hist.lineRemove': 'Removed', 'cat.hist.lineUpdate': 'Changed', 'cat.hist.reordered': 'Moved',
  'cat.hist.hiddenChange': 'Changed details you don\'t have access to.', 'cat.hist.latest100': 'Showing the latest 100 changes.', 'cat.hist.stock': 'stock',
  'cat.reason.opening': 'Opening stock', 'cat.reason.po_delivery': 'Delivered on a purchase order', 'cat.reason.used_on_job': 'Used on a job',
  'cat.reason.return': 'Returned to supplier', 'cat.reason.adjustment': 'Stock adjustment', 'cat.reason.job_reversal': 'Put back from a job',
  'cat.position': 'Order', 'cat.note': 'Note', 'cat.line': 'Item',
  'cat.adjust.button': 'Adjust stock', 'cat.adjust.who': 'Owners and Admins only. Use it after a stock count.',
  'cat.adjust.saveFirst': 'Save or cancel your other changes first.', 'cat.adjust.title': 'Adjust live stock',
  'cat.adjust.intro': 'There are {n} on hand right now. Enter the number you actually counted; the difference is recorded with your name and reason.',
  'cat.adjust.newCount': 'Counted on hand', 'cat.adjust.reason': 'Reason', 'cat.adjust.reasonExample': 'e.g. Monthly stock count, 1 damaged',
  'cat.adjust.change': 'Change: {d}', 'cat.adjust.confirm': 'Confirm new stock count', 'cat.adjust.countRule': 'A number from 0 to 1.000.000.',
  'cat.adjust.same': 'This is the same as the current stock.', 'cat.adjust.done': 'Stock for {name} set to {n}',
  'cat.copyNotes': 'Copy notes from another point…', 'cat.copiedNotes': 'Copied {n} notes from {name}', 'cat.copiedNone': '{name} has no notes that aren\'t here already',
}

export const catalogId = {
  // Appearance
  'settings.nav.appearance': 'Tampilan',
  'theme.intro': 'Pilih warna untuk bilah atas, tombol, dan tautan. Semua orang di bengkel melihat warna yang sama.',
  'theme.teal': 'Hijau toska', 'theme.ocean': 'Biru laut', 'theme.indigo': 'Nila', 'theme.purple': 'Ungu', 'theme.crimson': 'Merah tua',
  'theme.orange': 'Oranye', 'theme.forest': 'Hijau hutan', 'theme.graphite': 'Grafit', 'theme.custom': 'Kustom',
  'theme.pick': 'Pilih warna', 'theme.hex': 'Kode warna',
  'theme.hint': 'Warna baru langsung terlihat oleh Anda; disimpan untuk semua orang setelah Anda menekan Simpan.',
  'theme.lowContrast': 'Warna ini cukup terang, jadi teks putih di atasnya bisa sulit dibaca. Warna yang lebih gelap lebih baik.',
  'theme.badHex': 'Masukkan kode warna seperti #0E9F7E.',
  'theme.tooLight': 'Warna ini terlalu terang untuk teks putih. Pilih warna yang lebih gelap.',
  'create.part': 'Part baru',

  // Tabs
  'cat.tab.labor': 'Jasa', 'cat.tab.parts': 'Part', 'cat.tab.fees': 'Biaya', 'cat.tab.flat-rate': 'Paket harga tetap', 'cat.tab.discounts': 'Diskon',
  'cat.tab.bundles': 'Paket servis', 'cat.tab.inspections': 'Inspeksi', 'cat.tab.checklists': 'Daftar periksa', 'cat.tab.categories': 'Kategori',
  'cat.tab.suppliers': 'Pemasok',
  'cat.sub.labor': 'Pekerjaan jasa dengan harga jam × tarif jasa',
  'cat.sub.parts': 'Part yang Anda jual; ban termasuk kategori part',
  'cat.sub.fees': 'Biaya seperti biaya pembuangan, ditambahkan manual atau otomatis bersama item',
  'cat.sub.flat-rate': 'Kumpulan jasa dan part yang dijual dengan satu harga tetap',
  'cat.sub.discounts': 'Diskon siap pakai untuk seluruh pekerjaan atau satu servis',
  'cat.sub.bundles': 'Kumpulan jasa dan part yang ditambahkan bersama, masing-masing dengan harganya sendiri',
  'cat.sub.inspections': 'Poin yang diperiksa teknisi, dengan catatan siap pakai',
  'cat.sub.checklists': 'Kumpulan poin inspeksi yang berurutan',
  'cat.sub.categories': 'Kelompok untuk jasa, part, dan biaya; dipakai untuk filter dan laporan',
  'cat.sub.suppliers': 'Asal part, dan bengkel luar untuk pekerjaan sublet',
  'cat.add.labor': 'Jasa', 'cat.add.parts': 'Part', 'cat.add.fees': 'Biaya', 'cat.add.flat-rate': 'Paket harga tetap', 'cat.add.discounts': 'Diskon',
  'cat.add.bundles': 'Paket', 'cat.add.inspections': 'Poin inspeksi', 'cat.add.checklists': 'Daftar periksa', 'cat.add.categories': 'Kategori',
  'cat.add.suppliers': 'Pemasok',
  'cat.new.labor': 'Jasa baru', 'cat.new.part': 'Part baru', 'cat.new.fee': 'Biaya baru', 'cat.new.flat': 'Paket harga tetap baru', 'cat.new.bundle': 'Paket servis baru',
  'cat.new.discount': 'Diskon baru', 'cat.new.inspection': 'Poin inspeksi baru', 'cat.new.checklist': 'Daftar periksa baru', 'cat.new.category': 'Kategori baru',
  'cat.new.supplier': 'Pemasok baru',
  'cat.search.labor': 'Cari nama atau kode jasa', 'cat.search.parts': 'Cari nama atau nomor part', 'cat.search.fees': 'Cari biaya',
  'cat.search.templates': 'Cari nama atau tag', 'cat.search.discounts': 'Cari diskon', 'cat.search.inspections': 'Cari poin inspeksi',
  'cat.search.checklists': 'Cari daftar periksa', 'cat.search.categories': 'Cari kategori', 'cat.search.suppliers': 'Cari nama, kontak, telepon, atau no. akun',
  'cat.empty.labor': 'Belum ada jasa', 'cat.empty.parts': 'Belum ada part', 'cat.empty.fees': 'Belum ada biaya', 'cat.empty.flat-rate': 'Belum ada paket harga tetap',
  'cat.empty.discounts': 'Belum ada diskon', 'cat.empty.bundles': 'Belum ada paket servis', 'cat.empty.inspections': 'Belum ada poin inspeksi',
  'cat.empty.checklists': 'Belum ada daftar periksa', 'cat.empty.categories': 'Belum ada kategori', 'cat.empty.suppliers': 'Belum ada pemasok',
  'cat.emptyText.labor': 'Tambahkan pekerjaan yang sering dilakukan, seperti "Ganti oli" atau "Ganti kampas rem", agar bisa ditambahkan ke estimasi dengan sekali klik.',
  'cat.emptyText.parts': 'Tambahkan part yang Anda stok atau sering dipesan. Harga, modal, dan stoknya disimpan di sini.',
  'cat.emptyText.fees': 'Tambahkan biaya seperti biaya pembuangan aki. Biaya bisa ditambahkan otomatis setiap kali part atau jasa dipakai.',
  'cat.emptyText.flat-rate': 'Gabungkan jasa dan part menjadi satu paket dengan harga tetap, seperti "Servis ringan".',
  'cat.emptyText.discounts': 'Simpan diskon yang sering diberikan, seperti diskon armada, agar bisa dipilih di pekerjaan.',
  'cat.emptyText.bundles': 'Kelompokkan jasa dan part yang biasanya bersamaan, agar bisa ditambahkan ke pekerjaan sekaligus.',
  'cat.emptyText.inspections': 'Tambahkan poin yang diperiksa teknisi, seperti "Kampas rem depan", dengan catatan siap pakai untuk baik, segera, dan mendesak.',
  'cat.emptyText.checklists': 'Urutkan poin inspeksi menjadi daftar periksa, seperti "Inspeksi 30 poin". Tambahkan poin inspeksi terlebih dahulu.',
  'cat.emptyText.categories': 'Kategori mengelompokkan jasa, part, dan biaya, seperti "Mesin › Filter".',
  'cat.emptyText.suppliers': 'Tambahkan toko tempat Anda membeli part, dan bengkel luar untuk pekerjaan sublet.',
  'cat.listHint.labor': 'Tarif jasa diatur di Pengaturan → Tarif jasa.',
  'cat.listHint.parts': 'Stok merah berarti sudah mencapai atau di bawah batas pesan ulang.',
  'cat.listHint.fees': 'Biaya persen dihitung dari pekerjaan saat ditambahkan.',
  'cat.listHint.flat-rate': 'Pekerjaan menampilkan satu harga; baris di dalamnya tetap dicatat untuk stok dan laporan.',
  'cat.listHint.bundles': 'Setiap baris memakai harganya sendiri di pekerjaan dan masih bisa diubah di sana.',
  'cat.listHint.discounts': 'Diskon dipilih di pekerjaan; mengubahnya di sini tidak mengubah pekerjaan yang sudah memakainya.',
  'cat.listHint.inspections': 'Hijau berarti baik, kuning berarti perlu segera, merah berarti perlu sekarang.',
  'cat.listHint.checklists': 'Daftar periksa bisa dipasang pada paket servis atau paket harga tetap.',
  'cat.listHint.categories': 'Kategori bisa berada di dalam kategori lain, seperti Mesin › Filter.',
  'cat.listHint.suppliers': 'Pemasok part dipakai di purchase order; bengkel sublet mengerjakan pekerjaan luar untuk Anda.',

  // Shared
  'cat.name': 'Nama', 'cat.code': 'Kode', 'cat.partNo': 'No. part', 'cat.category': 'Kategori', 'cat.categoryAll': 'Kategori: semua', 'cat.supplier': 'Pemasok',
  'cat.brand': 'Merek', 'cat.description': 'Deskripsi', 'cat.descriptionHint': 'Ditampilkan di estimasi dan invoice di bawah nama.',
  'cat.cost': 'Modal', 'cat.price': 'Harga', 'cat.core': 'Core', 'cat.onHand': 'Stok', 'cat.tax': 'Pajak', 'cat.yes': 'Ya', 'cat.no': 'Tidak',
  'cat.hours': 'Jam', 'cat.hoursShort': 'jam', 'cat.rate': 'Tarif', 'cat.value': 'Nilai', 'cat.feeKind': 'Jenis', 'cat.feeKind.fixed': 'Jumlah tetap',
  'cat.feeKind.percent': 'Persen dari pekerjaan', 'cat.autoAddedTo': 'Otomatis pada', 'cat.itemsCount': '{n} item', 'cat.status': 'Status',
  'cat.statusActive': 'Aktif', 'cat.statusInactive': 'Nonaktif', 'cat.statusAll': 'Semua', 'cat.inactive': 'Nonaktif', 'cat.activeLabel': 'Aktif (bisa ditambahkan ke pekerjaan)',
  'cat.notFound': 'Data ini sudah tidak ada', 'cat.viewOnly': 'Anda bisa melihat katalog tetapi tidak bisa mengubahnya.',
  'cat.create': 'Buat', 'cat.confirmDelete': 'Ya, hapus', 'cat.saved': '{name} disimpan', 'cat.deleted': '{name} dihapus',
  'cat.inUse': 'Data ini dipakai di pekerjaan, pesanan, atau data katalog lain, jadi tidak bisa dihapus. Matikan "Aktif" untuk menyembunyikannya.',
  'cat.loadFailed': 'Sebagian katalog tidak bisa dimuat: {error}', 'cat.settings': 'Pengaturan', 'cat.notes': 'Catatan internal',
  'cat.notesHint': 'Hanya staf yang melihatnya.', 'cat.dupName': 'Nama ini sudah dipakai.', 'cat.dupCode': 'Juga dipakai oleh {name}.',
  'cat.moveUp': 'Pindahkan {name} ke atas', 'cat.moveDown': 'Pindahkan {name} ke bawah', 'cat.removeRow': 'Hapus {name}', 'cat.total': 'Total',

  // Items
  'cat.pricing': 'Harga', 'cat.laborRate': 'Tarif jasa', 'cat.hoursTimesRate': 'Jam × tarif.', 'cat.differsFromRate': 'Jam × tarif menjadi {amount}.',
  'cat.pickRate': 'Pilih tarif dan jam untuk menghitung harga.', 'cat.costOptional': 'Modal (opsional)', 'cat.laborCostHint': 'Biaya pekerjaan bagi bengkel, untuk laporan laba.',
  'cat.markup': 'Markup', 'cat.markupHint': 'Ubah modal atau markup dan harga mengikuti.', 'cat.margin': 'Margin {pct}%', 'cat.defaultQty': 'Jumlah bawaan',
  'cat.amount': 'Jumlah', 'cat.percent': 'Persen', 'cat.percentFeeHint': 'Dari jasa dan part pada pekerjaan.',
  'cat.hasCore': 'Ada biaya core', 'cat.coreCharge': 'Biaya core', 'cat.coreHint': 'Ditagihkan bersama part dan dikembalikan pemasok saat core lama dikembalikan.',
  'cat.tireSize': 'Ukuran ban (opsional)', 'cat.tireHint': 'Isi untuk ban agar bisa dicari berdasarkan ukuran.',
  'cat.autoFees': 'Biaya otomatis', 'cat.noFees': 'Belum ada biaya. Tambahkan di tab Biaya.', 'cat.autoFeesHint': 'Biaya ini ditambahkan ke pekerjaan bersama item ini, dengan jumlah yang sama.',
  'cat.inventory': 'Inventaris', 'cat.trackInventory': 'Lacak stok part ini', 'cat.trackLocked': 'Pelacakan stok tetap aktif selama masih ada stok.',
  'cat.openingStock': 'Stok awal', 'cat.onEstimates': 'Di estimasi', 'cat.available': 'Tersedia', 'cat.reorderAt': 'Pesan ulang di',
  'cat.openingHint': 'Jumlah yang Anda punya sekarang. Perubahan berikutnya lewat purchase order dan penyesuaian stok.',
  'cat.stockHint': 'Stok berubah lewat pekerjaan, purchase order, dan retur. Pemilik dan Admin bisa mengoreksi jumlahnya dengan Sesuaikan stok.',
  'cat.openingNote': 'Stok awal', 'cat.openingFailed': 'Part disimpan tetapi stok awalnya tidak: {error}',
  'cat.taxable': 'Kena pajak ({tax} {rate}%)', 'cat.showOnInvoice': 'Tampilkan di estimasi & invoice', 'cat.showQtyPrice': 'Tampilkan jumlah dan harga satuan',
  'cat.showHoursRate': 'Tampilkan jam dan tarif', 'cat.markupRule': 'Antara -100 dan 1000%.', 'cat.qtyRule': 'Dari 0,01 sampai 10.000.', 'cat.hoursRule': 'Antara 0 dan 1000 jam.',

  // Flat rate items & bundles
  'cat.tags': 'Tag', 'cat.tagsHint': 'Pisahkan dengan koma, mis. "servis, 10.000 km".', 'cat.lines': 'Baris', 'cat.linesN': '{n} baris',
  'cat.itemsValue': 'Nilai baris', 'cat.flatPrice': 'Harga tetap', 'cat.interval': 'Ulangi setiap', 'cat.monthsN': '{n} bulan', 'cat.monthsShort': 'bulan',
  'cat.noLines': 'Belum ada baris. Pilih jasa atau part di bawah.', 'cat.addLine': '+ Tambah jasa, part, atau biaya…', 'cat.catalogPrice': 'katalog {amount}',
  'cat.qty': 'Jml', 'cat.qtyFor': 'Jumlah untuk {name}', 'cat.priceFor': 'Harga untuk {name} (kosong = harga katalog)',
  'cat.flatSaves': 'Pelanggan hemat', 'cat.flatAbove': 'Di atas nilai baris sebesar',
  'cat.flatHint': 'Pekerjaan menampilkan harga tetap; harga ini dibagi ke baris-baris untuk laporan.',
  'cat.bundleHint': 'Kosongkan harga untuk memakai harga katalog saat ditambahkan.',
  'cat.afterService': 'Daftar periksa dan pengingat', 'cat.checklist': 'Daftar periksa inspeksi', 'cat.noChecklist': 'Tanpa daftar periksa',
  'cat.checklistHint': 'Ditambahkan ke pekerjaan bersama servis ini untuk diisi teknisi.',
  'cat.everyKm': 'Ulangi setiap (km)', 'cat.everyMonths': 'Ulangi setiap (bulan)',
  'cat.intervalHint': 'Saran jadwal servis kendaraan setelah ini selesai. Kosongkan jika tidak ada.',
  'cat.kmRule': 'Kilometer bulat, 1 sampai 1.000.000.', 'cat.monthsRule': 'Bulan bulat, 1 sampai 120.', 'cat.needLine': 'Tambahkan minimal satu baris.',
  'cat.linesFailed': 'Tersimpan, tetapi tidak semua baris bisa disimpan: {error}',

  // Discounts
  'cat.appliesTo': 'Berlaku untuk', 'cat.level.job': 'Seluruh pekerjaan', 'cat.level.service': 'Satu servis',
  'cat.levelHint.job': 'Dipotong dari total pekerjaan.', 'cat.levelHint.service': 'Dipotong dari satu servis di pekerjaan.',
  'cat.discountKind': 'Jenis', 'cat.kind.percent': 'Persen', 'cat.kind.amount': 'Jumlah tetap', 'cat.maxDiscount': 'Maks',
  'cat.maxDiscountOptional': 'Maksimum (opsional)', 'cat.maxHint': 'Diskon tidak pernah melebihi jumlah ini.', 'cat.valid': 'Berlaku',
  'cat.validFrom': 'Dari', 'cat.validTo': 'Sampai', 'cat.validHint': 'Kosongkan agar bisa dipakai kapan saja.', 'cat.always': 'Kapan saja',
  'cat.state.running': 'Aktif', 'cat.state.scheduled': 'Belum mulai', 'cat.state.expired': 'Berakhir', 'cat.state.inactive': 'Mati',
  'cat.percentRule': 'Lebih dari 0 dan paling banyak 100.', 'cat.dateOrder': 'Harus pada atau setelah tanggal mulai.', 'cat.discountExample': 'mis. Diskon armada 10%',

  // Inspections
  'cat.group': 'Grup', 'cat.groupAll': 'Grup: semua', 'cat.groupExample': 'mis. Rem', 'cat.groupHint': 'Poin dalam grup yang sama ditampilkan bersama.',
  'cat.noGroup': 'Tanpa grup', 'cat.cannedNotes': 'Catatan siap pakai', 'cat.inChecklists': 'Di daftar periksa', 'cat.inspExample': 'mis. Kampas rem depan',
  'cat.flag.green': 'Baik', 'cat.flag.yellow': 'Segera', 'cat.flag.red': 'Sekarang', 'cat.flagFor': 'Warna untuk catatan {note}',
  'cat.notePlaceholder.green': 'mis. Kampas dalam kondisi baik', 'cat.notePlaceholder.yellow': 'mis. Kampas tinggal 30%, segera ganti',
  'cat.notePlaceholder.red': 'mis. Kampas habis, ganti sekarang', 'cat.noteN': 'Catatan {n}', 'cat.noNotes': 'Belum ada catatan.', 'cat.addNote': 'Tambah catatan',
  'cat.notesHint2': 'Teknisi memilih salah satu catatan ini alih-alih mengetik. Catatan kosong diabaikan.',
  'cat.notesFailed': 'Tersimpan, tetapi tidak semua catatan bisa disimpan: {error}', 'cat.deleteRemoves': 'Menghapus poin ini juga menghapusnya dari daftar periksa ini.',

  // Checklists
  'cat.points': 'Poin', 'cat.pointsN': '{n} poin', 'cat.pointsTitle': 'Poin inspeksi ({n})', 'cat.usedByBundles': 'Dipakai oleh',
  'cat.noPoints': 'Belum ada poin.', 'cat.addPoint': '+ Tambah poin inspeksi…', 'cat.addGroup': '+ Tambah satu grup…',
  'cat.noInspItems': 'Tambahkan poin inspeksi di tab Inspeksi terlebih dahulu.', 'cat.needPoint': 'Tambahkan minimal satu poin inspeksi.',
  'cat.checklistExample': 'mis. Inspeksi 30 poin',

  // Categories
  'cat.usedFor': 'Dipakai untuk', 'cat.usedForAll': 'Dipakai untuk: semua', 'cat.applies.part': 'Part', 'cat.applies.labor': 'Jasa', 'cat.applies.fee': 'Biaya',
  'cat.applies.any': 'Apa saja', 'cat.itemsCol': 'Item', 'cat.subcategories': 'Subkategori', 'cat.subsCount': '{n} subkategori',
  'cat.parent': 'Di dalam', 'cat.topLevel': 'Tingkat atas', 'cat.parentHint': 'Letakkan di dalam kategori lain, mis. Filter di dalam Mesin.',
  'cat.categoryExample': 'mis. Filter', 'cat.categoryInUse': 'Kategori yang punya item atau subkategori tidak bisa dihapus; pindahkan dulu.',
  'cat.appliesMismatch': 'Ada {n} item jenis lain di kategori ini. Pilih "Apa saja" atau pindahkan item tersebut dulu.',

  // Suppliers
  'cat.supplierType': 'Jenis', 'cat.typeAll': 'Jenis: semua', 'cat.stype.internal': 'Pemasok part', 'cat.stype.sublet': 'Bengkel sublet',
  'cat.stypeHint.internal': 'Anda membeli part dari mereka.', 'cat.stypeHint.sublet': 'Mereka mengerjakan pekerjaan luar untuk Anda, mis. bubut.',
  'cat.contact': 'Kontak', 'cat.contactName': 'Nama kontak', 'cat.partsCol': 'Part', 'cat.cod': 'Tunai', 'cat.daysN': '{n} hari',
  'cat.termsDays': 'Termin pembayaran', 'cat.termsCol': 'Termin', 'cat.termsHint': '0 berarti bayar saat barang datang.', 'cat.accountNo': 'No. akun kami',
  'cat.accountHint': 'Nomor akun yang mereka berikan untuk bengkel Anda.', 'cat.pinnedNotes': 'Catatan disematkan',
  'cat.pinnedHint': 'Ditampilkan di atas setiap kali pemasok ini dibuka, mis. "Pesan sebelum jam 14.00 untuk kirim di hari yang sama".',
  'cat.suppliedParts': 'Part dari pemasok ini ({n})',
  // Update 3: history, stock adjustment, copying notes
  'cat.hist.section': 'Riwayat', 'cat.hist.title': 'Riwayat perubahan', 'cat.hist.show': 'Lihat riwayat perubahan', 'cat.hist.hide': 'Sembunyikan',
  'cat.hist.none': 'Belum ada perubahan yang tercatat.', 'cat.hist.system': 'Sistem', 'cat.hist.created': 'Dibuat', 'cat.hist.deleted': 'Dihapus',
  'cat.hist.lineAdd': 'Ditambahkan', 'cat.hist.lineRemove': 'Dihapus', 'cat.hist.lineUpdate': 'Diubah', 'cat.hist.reordered': 'Dipindah',
  'cat.hist.hiddenChange': 'Mengubah detail yang tidak bisa Anda lihat.', 'cat.hist.latest100': 'Menampilkan 100 perubahan terakhir.', 'cat.hist.stock': 'stok',
  'cat.reason.opening': 'Stok awal', 'cat.reason.po_delivery': 'Diterima dari purchase order', 'cat.reason.used_on_job': 'Dipakai di pekerjaan',
  'cat.reason.return': 'Dikembalikan ke pemasok', 'cat.reason.adjustment': 'Penyesuaian stok', 'cat.reason.job_reversal': 'Dikembalikan dari pekerjaan',
  'cat.position': 'Urutan', 'cat.note': 'Catatan', 'cat.line': 'Item',
  'cat.adjust.button': 'Sesuaikan stok', 'cat.adjust.who': 'Hanya Pemilik dan Admin. Pakai setelah hitung stok.',
  'cat.adjust.saveFirst': 'Simpan atau batalkan perubahan lain terlebih dahulu.', 'cat.adjust.title': 'Sesuaikan stok saat ini',
  'cat.adjust.intro': 'Stok saat ini {n}. Masukkan jumlah yang benar-benar Anda hitung; selisihnya dicatat dengan nama dan alasan Anda.',
  'cat.adjust.newCount': 'Jumlah hasil hitung', 'cat.adjust.reason': 'Alasan', 'cat.adjust.reasonExample': 'mis. Hitung stok bulanan, 1 rusak',
  'cat.adjust.change': 'Perubahan: {d}', 'cat.adjust.confirm': 'Konfirmasi jumlah stok baru', 'cat.adjust.countRule': 'Angka dari 0 sampai 1.000.000.',
  'cat.adjust.same': 'Jumlah ini sama dengan stok saat ini.', 'cat.adjust.done': 'Stok {name} diubah menjadi {n}',
  'cat.copyNotes': 'Salin catatan dari poin lain…', 'cat.copiedNotes': '{n} catatan disalin dari {name}', 'cat.copiedNone': '{name} tidak punya catatan yang belum ada di sini',
}
