// Screen text for stage 9a: dashboard and the first reports (English / Bahasa Indonesia).
export const reportsEn = {
  // Dashboard
  'dash.today': 'Today', 'dash.money': 'Money', 'dash.attention': 'Needs attention',
  'dash.bookings': 'Bookings today', 'dash.requests': '{n} booking request(s) waiting', 'dash.noRequests': 'No requests waiting',
  'dash.inShop': 'In the shop', 'dash.nothingInShop': 'No open jobs in progress',
  'dash.waitingParts': 'Waiting on parts', 'dash.waitingPartsNote': 'Open jobs with parts ordered that haven\'t all arrived',
  'dash.readyInv': 'Ready to invoice', 'dash.readyNote': 'Work completed, not invoiced yet',
  'dash.invoicedMtd': 'Invoiced this month', 'dash.nInvoices': '{n} invoice(s)', 'dash.vsLast': '{pct} vs last month to date ({amount})',
  'dash.receivedMtd': 'Received this month', 'dash.receivedNote': 'Payments minus refunds',
  'dash.owed': 'Owed by companies', 'dash.openInvoices': '{n} invoice(s) not fully paid',
  'dash.overdue': 'Overdue', 'dash.overdueNote': '{n} invoice(s) · {amount} over 90 days', 'dash.noneOverdue': 'Nothing past its due date',
  'dash.service': 'Service due', 'dash.serviceDetail': '{over} overdue · {soon} due soon',
  'dash.lowStock': 'Parts low or out', 'dash.lowStockDetail': 'At or below the reorder point',
  'dash.bills': 'Supplier bills', 'dash.billsDetail': '{overdue} overdue · {soon} due in 7 days',
  'dash.cores': 'Cores', 'dash.coresDetail': '{take} to take off vehicles · {send} to send back',
  'dash.returns': 'Returns to suppliers', 'dash.returnsDetail': 'Not refunded yet',
  'dash.estimates': 'Open estimates', 'dash.estimatesDetail': 'Not scheduled or started yet',
  'dash.allClear': 'All clear',
  'dash.chartTitle': 'Last 6 months', 'dash.invoiced': 'Invoiced', 'dash.received': 'Received', 'dash.month': 'Month',
  'dash.showTable': 'Show figures', 'dash.hideTable': 'Hide figures', 'dash.chartEmpty': 'No invoices or payments in the last 6 months yet.',
  'dash.chartHint': 'Invoiced = invoices issued in the month (voided ones left out). Received = payments in the month minus refunds.',
  // Reports area
  'rep.tab.sales': 'Sales', 'rep.tab.aging': 'Receivables aging', 'rep.tab.payments': 'Payments received',
  'rep.noAccessTitle': 'Reports are for managers', 'rep.noAccessText': 'Your role doesn\'t include reports. An Owner or Admin can change this in Settings → Users & access.',
  'rep.moreSoon': 'More reports (profit, technicians, fleet spend, inventory, service compliance) arrive in stage 9b.',
  'rep.period': 'Period', 'rep.from': 'From', 'rep.to': 'To', 'rep.company': 'Company', 'rep.allCompanies': 'All companies',
  'rep.p.this_month': 'This month', 'rep.p.last_month': 'Last month', 'rep.p.last_30': 'Last 30 days', 'rep.p.this_year': 'This year',
  'rep.p.last_year': 'Last year', 'rep.p.custom': 'Choose dates…',
  'rep.groupBy': 'Group by', 'rep.g.auto': 'By day or month', 'rep.g.day': 'Day', 'rep.g.month': 'Month', 'rep.g.company': 'Company',
  'rep.g.invoices': 'Each invoice', 'rep.g.method': 'Method', 'rep.g.list': 'Each payment',
  'rep.csv': 'Download CSV', 'rep.empty': 'Nothing in this period', 'rep.total': 'Total', 'rep.jobNo': 'Job {no}', 'rep.paidUp': 'Paid',
  'rep.m.parts': 'Parts', 'rep.m.labor': 'Labor', 'rep.m.sublet': 'Sublet', 'rep.m.fees': 'Fees', 'rep.m.discounts': 'Discounts',
  'rep.m.subtotal': 'Before tax', 'rep.m.tax': 'Tax', 'rep.m.total': 'Total',
  'rep.col.invoice': 'Invoice', 'rep.col.date': 'Date', 'rep.col.job': 'Job', 'rep.col.company': 'Company', 'rep.col.plate': 'Plate',
  'rep.col.paid': 'Paid', 'rep.col.balance': 'Still owed', 'rep.col.invoices': 'Invoices', 'rep.col.due': 'Due', 'rep.col.daysOverdue': 'Days past due',
  'rep.col.bucket': 'Aging', 'rep.col.owed': 'Owed', 'rep.col.kind': 'Type', 'rep.col.method': 'Method', 'rep.col.reference': 'Reference',
  'rep.col.amount': 'Amount', 'rep.col.entries': 'Entries',
  // Sales
  'rep.sales.title': 'Sales', 'rep.sales.sub': 'Invoices issued in the period, split into parts, labor, sublet, fees and discounts.',
  'rep.sales.total': 'Total invoiced', 'rep.sales.nInvoices': '{n} invoice(s)', 'rep.sales.beforeTax': 'Parts + labor + sublet + fees − discounts',
  'rep.sales.emptyText': 'No invoices were issued in this period. Try a longer period or another company.',
  'rep.sales.hint': 'Counted on the invoice date (shop time). Voided invoices are left out, so a past month can go down if one of its invoices is voided later; a re-issued invoice counts on its new date. Parts include core charges. Line discounts are already taken off parts and labor; the Discounts column is service and job discounts.',
  'rep.sales.voids': '{n} invoice(s) worth {amount} were voided in this period and are not counted.', 'rep.sales.voidedOn': 'voided {date} (issued {issued})',
  'rep.show': 'Show', 'rep.hide': 'Hide', 'rep.aging.creditOnly': 'Nothing owed, credit only',
  // Aging
  'rep.aging.title': 'Receivables aging', 'rep.aging.sub': 'What each company still owes today, by how long it is past its due date.',
  'rep.aging.owed': 'Owed in total', 'rep.aging.nInvoices': '{n} invoice(s)', 'rep.aging.overdue': 'Past due', 'rep.aging.share': '{pct}% of what is owed',
  'rep.aging.credit': 'Unused credit', 'rep.aging.creditNote': 'Can be applied to these invoices',
  'rep.aging.noneTitle': 'Nothing owed', 'rep.aging.noneText': 'Every invoice is paid in full.',
  'rep.aging.showInvoices': 'Show invoices for {name}', 'rep.aging.daysOver': '{n} days past due', 'rep.aging.dueOn': 'due {date}', 'rep.aging.ofTotal': 'of {total}',
  'rep.aging.hint': 'As of today. Days past due count from the invoice\'s due date (invoice date + the company\'s payment terms). Click a company to see its invoices.',
  'rep.b.current': 'Not yet due', 'rep.b.d1_30': '1–30 days', 'rep.b.d31_60': '31–60 days', 'rep.b.d61_90': '61–90 days', 'rep.b.d90': 'Over 90 days',
  // Payments
  'rep.pay.title': 'Payments received', 'rep.pay.sub': 'Money in from companies, and money paid back to them, in the period.',
  'rep.pay.allMethods': 'All methods', 'rep.pay.net': 'Net received', 'rep.pay.in': 'Received', 'rep.pay.out': 'Paid back',
  'rep.pay.nEntries': '{n} entries', 'rep.pay.outNote': 'Refunds and credit paid back as money',
  'rep.pay.emptyText': 'No payments or refunds in this period.', 'rep.pay.fromCredit': 'Company credit',
  'rep.pay.hint': 'Counted on the payment date (shop time). When an invoice is voided its payments move to company credit; that move isn\'t money, so it isn\'t listed.',
  'rep.kind.payment': 'Payment', 'rep.kind.refund': 'Refund', 'rep.kind.credit_refund': 'Credit paid back',
}

export const reportsId = {
  'dash.today': 'Hari ini', 'dash.money': 'Keuangan', 'dash.attention': 'Perlu perhatian',
  'dash.bookings': 'Janji servis hari ini', 'dash.requests': '{n} permintaan janji menunggu', 'dash.noRequests': 'Tidak ada permintaan menunggu',
  'dash.inShop': 'Di bengkel', 'dash.nothingInShop': 'Tidak ada pekerjaan yang sedang berjalan',
  'dash.waitingParts': 'Menunggu part', 'dash.waitingPartsNote': 'Pekerjaan terbuka dengan part dipesan yang belum semua datang',
  'dash.readyInv': 'Siap dibuatkan invoice', 'dash.readyNote': 'Pekerjaan selesai, belum ada invoice',
  'dash.invoicedMtd': 'Invoice bulan ini', 'dash.nInvoices': '{n} invoice', 'dash.vsLast': '{pct} dibanding bulan lalu sampai tanggal yang sama ({amount})',
  'dash.receivedMtd': 'Diterima bulan ini', 'dash.receivedNote': 'Pembayaran dikurangi refund',
  'dash.owed': 'Piutang perusahaan', 'dash.openInvoices': '{n} invoice belum lunas',
  'dash.overdue': 'Lewat jatuh tempo', 'dash.overdueNote': '{n} invoice · {amount} lebih dari 90 hari', 'dash.noneOverdue': 'Tidak ada yang lewat jatuh tempo',
  'dash.service': 'Servis jatuh tempo', 'dash.serviceDetail': '{over} terlambat · {soon} segera',
  'dash.lowStock': 'Part menipis atau habis', 'dash.lowStockDetail': 'Di atau di bawah titik pesan ulang',
  'dash.bills': 'Tagihan supplier', 'dash.billsDetail': '{overdue} lewat jatuh tempo · {soon} jatuh tempo 7 hari',
  'dash.cores': 'Core', 'dash.coresDetail': '{take} masih di kendaraan · {send} siap dikirim balik',
  'dash.returns': 'Retur ke supplier', 'dash.returnsDetail': 'Belum direfund',
  'dash.estimates': 'Estimasi terbuka', 'dash.estimatesDetail': 'Belum dijadwalkan atau dimulai',
  'dash.allClear': 'Aman',
  'dash.chartTitle': '6 bulan terakhir', 'dash.invoiced': 'Invoice', 'dash.received': 'Diterima', 'dash.month': 'Bulan',
  'dash.showTable': 'Tampilkan angka', 'dash.hideTable': 'Sembunyikan angka', 'dash.chartEmpty': 'Belum ada invoice atau pembayaran dalam 6 bulan terakhir.',
  'dash.chartHint': 'Invoice = invoice yang terbit di bulan itu (yang dibatalkan tidak dihitung). Diterima = pembayaran di bulan itu dikurangi refund.',
  'rep.tab.sales': 'Penjualan', 'rep.tab.aging': 'Umur piutang', 'rep.tab.payments': 'Pembayaran diterima',
  'rep.noAccessTitle': 'Laporan untuk manajer', 'rep.noAccessText': 'Peran Anda tidak termasuk laporan. Pemilik atau Admin bisa mengubahnya di Pengaturan → Pengguna & akses.',
  'rep.moreSoon': 'Laporan lain (laba, teknisi, biaya armada, inventaris, kepatuhan servis) hadir di tahap 9b.',
  'rep.period': 'Periode', 'rep.from': 'Dari', 'rep.to': 'Sampai', 'rep.company': 'Perusahaan', 'rep.allCompanies': 'Semua perusahaan',
  'rep.p.this_month': 'Bulan ini', 'rep.p.last_month': 'Bulan lalu', 'rep.p.last_30': '30 hari terakhir', 'rep.p.this_year': 'Tahun ini',
  'rep.p.last_year': 'Tahun lalu', 'rep.p.custom': 'Pilih tanggal…',
  'rep.groupBy': 'Kelompokkan', 'rep.g.auto': 'Per hari atau bulan', 'rep.g.day': 'Hari', 'rep.g.month': 'Bulan', 'rep.g.company': 'Perusahaan',
  'rep.g.invoices': 'Per invoice', 'rep.g.method': 'Metode', 'rep.g.list': 'Per pembayaran',
  'rep.csv': 'Unduh CSV', 'rep.empty': 'Tidak ada data di periode ini', 'rep.total': 'Total', 'rep.jobNo': 'Pekerjaan {no}', 'rep.paidUp': 'Lunas',
  'rep.m.parts': 'Part', 'rep.m.labor': 'Jasa', 'rep.m.sublet': 'Sublet', 'rep.m.fees': 'Biaya', 'rep.m.discounts': 'Diskon',
  'rep.m.subtotal': 'Sebelum pajak', 'rep.m.tax': 'Pajak', 'rep.m.total': 'Total',
  'rep.col.invoice': 'Invoice', 'rep.col.date': 'Tanggal', 'rep.col.job': 'Pekerjaan', 'rep.col.company': 'Perusahaan', 'rep.col.plate': 'Plat',
  'rep.col.paid': 'Dibayar', 'rep.col.balance': 'Sisa tagihan', 'rep.col.invoices': 'Invoice', 'rep.col.due': 'Jatuh tempo', 'rep.col.daysOverdue': 'Hari terlambat',
  'rep.col.bucket': 'Umur', 'rep.col.owed': 'Piutang', 'rep.col.kind': 'Jenis', 'rep.col.method': 'Metode', 'rep.col.reference': 'Referensi',
  'rep.col.amount': 'Jumlah', 'rep.col.entries': 'Transaksi',
  'rep.sales.title': 'Penjualan', 'rep.sales.sub': 'Invoice yang terbit di periode ini, dipisah menjadi part, jasa, sublet, biaya, dan diskon.',
  'rep.sales.total': 'Total invoice', 'rep.sales.nInvoices': '{n} invoice', 'rep.sales.beforeTax': 'Part + jasa + sublet + biaya − diskon',
  'rep.sales.emptyText': 'Tidak ada invoice yang terbit di periode ini. Coba periode lebih panjang atau perusahaan lain.',
  'rep.sales.hint': 'Dihitung pada tanggal invoice (waktu bengkel). Invoice yang dibatalkan tidak dihitung, jadi angka bulan lalu bisa turun bila salah satu invoicenya dibatalkan kemudian; invoice yang diterbitkan ulang dihitung pada tanggal barunya. Part termasuk biaya core. Diskon per baris sudah dikurangkan dari part dan jasa; kolom Diskon adalah diskon servis dan pekerjaan.',
  'rep.sales.voids': '{n} invoice senilai {amount} dibatalkan di periode ini dan tidak dihitung.', 'rep.sales.voidedOn': 'dibatalkan {date} (terbit {issued})',
  'rep.show': 'Lihat', 'rep.hide': 'Sembunyikan', 'rep.aging.creditOnly': 'Tidak ada piutang, hanya kredit',
  'rep.aging.title': 'Umur piutang', 'rep.aging.sub': 'Sisa tagihan tiap perusahaan hari ini, menurut berapa lama lewat jatuh tempo.',
  'rep.aging.owed': 'Total piutang', 'rep.aging.nInvoices': '{n} invoice', 'rep.aging.overdue': 'Lewat jatuh tempo', 'rep.aging.share': '{pct}% dari piutang',
  'rep.aging.credit': 'Kredit belum dipakai', 'rep.aging.creditNote': 'Bisa dipakai untuk invoice ini',
  'rep.aging.noneTitle': 'Tidak ada piutang', 'rep.aging.noneText': 'Semua invoice sudah lunas.',
  'rep.aging.showInvoices': 'Tampilkan invoice {name}', 'rep.aging.daysOver': 'terlambat {n} hari', 'rep.aging.dueOn': 'jatuh tempo {date}', 'rep.aging.ofTotal': 'dari {total}',
  'rep.aging.hint': 'Per hari ini. Hari terlambat dihitung dari jatuh tempo invoice (tanggal invoice + termin perusahaan). Klik perusahaan untuk melihat invoicenya.',
  'rep.b.current': 'Belum jatuh tempo', 'rep.b.d1_30': '1–30 hari', 'rep.b.d31_60': '31–60 hari', 'rep.b.d61_90': '61–90 hari', 'rep.b.d90': 'Lebih dari 90 hari',
  'rep.pay.title': 'Pembayaran diterima', 'rep.pay.sub': 'Uang masuk dari perusahaan, dan uang yang dikembalikan ke mereka, di periode ini.',
  'rep.pay.allMethods': 'Semua metode', 'rep.pay.net': 'Diterima bersih', 'rep.pay.in': 'Diterima', 'rep.pay.out': 'Dikembalikan',
  'rep.pay.nEntries': '{n} transaksi', 'rep.pay.outNote': 'Refund dan kredit yang dikembalikan sebagai uang',
  'rep.pay.emptyText': 'Tidak ada pembayaran atau refund di periode ini.', 'rep.pay.fromCredit': 'Kredit perusahaan',
  'rep.pay.hint': 'Dihitung pada tanggal pembayaran (waktu bengkel). Saat invoice dibatalkan, pembayarannya pindah ke kredit perusahaan; perpindahan itu bukan uang, jadi tidak dicantumkan.',
  'rep.kind.payment': 'Pembayaran', 'rep.kind.refund': 'Refund', 'rep.kind.credit_refund': 'Kredit dikembalikan',
  'db:Choose a start and end date': 'Pilih tanggal mulai dan selesai.',
  'db:The end date is before the start date': 'Tanggal selesai sebelum tanggal mulai.',
  'db:Choose a period of at most 5 years': 'Pilih periode paling lama 5 tahun.',
}
