// Screen text for stage 4: jobs, estimates, invoices and payments (English / Bahasa Indonesia).
export const jobsEn = {
  // New job
  'job.newTitle': 'New job', 'job.newSub': 'Pick the company and vehicle; services are added on the job page.',
  'job.company': 'Company', 'job.searchCompany': 'Search company name or plate', 'job.vehicle': 'Vehicle', 'job.pickVehicle': 'Pick a vehicle',
  'job.noVehicles': 'This company has no vehicles', 'job.pickCompanyFirst': 'Pick a company first', 'job.addVehicleFirst': 'Add a vehicle to this company first',
  'job.alreadyOpen': 'This vehicle already has an open job:', 'job.odometerIn': 'Odometer in', 'job.odometerOut': 'Odometer out',
  'job.lastKnown': 'Last known: {km}', 'job.lowerThanLast': 'Lower than the last known reading ({km}). Check the number.',
  'job.priority': 'Priority', 'job.advisor': 'Service advisor', 'job.concern': 'Customer concern',
  'job.concernExample': 'e.g. Brakes squeal when stopping', 'job.concernHint': 'What the driver or fleet manager reported. More can be added later.',
  'job.create': 'Create job', 'job.created': 'Job #{no} created', 'job.noCustomers': 'No companies yet', 'job.noCustomersText': 'Add a company and its vehicles first.',
  'job.pri.low': 'Low', 'job.pri.medium': 'Medium', 'job.pri.high': 'High', 'job.pri.urgent': 'Urgent',

  // Job page header
  'job.jobNo': 'Job #{no}', 'job.estimate': 'Estimate', 'job.invoice': 'Invoice', 'job.closed': 'Closed', 'job.notFound': 'This job no longer exists',
  'job.backToList': 'Back to repair orders', 'job.print': 'Print', 'job.printSoon': 'Printing comes in stage 5', 'job.more': 'More actions',
  'job.customer': 'Customer', 'job.attn': 'Attn. {name}', 'job.odoIn': 'In', 'job.odoOut': 'Out', 'job.customerConcern': 'Customer concern',
  'job.noConcerns': 'No concerns written down yet.', 'job.editConcerns': 'Edit concerns', 'job.addConcern': 'Add a concern',
  'job.shopNotes': 'Shop notes (internal)', 'job.shopNotesHint': 'Only staff see these, e.g. parts on order, ETA.',
  'job.recommendations': 'Recommendations (printed)', 'job.recommendationsHint': 'Advice for the next visit, printed on the invoice.',
  'job.closedNotice': 'This job was closed without an invoice: {reason}. Reopen it to make changes.',
  'job.invoicedNotice': 'This job is invoiced, so its work, prices, concerns and inspections are locked. Payments, technicians and work status can still change. Void the invoice to correct it.',
  'job.pickedUpBadge': 'Picked up', 'job.closeNoInvoice': 'Close without invoice', 'job.reopen': 'Reopen job', 'job.reopened': 'Job reopened',
  'job.deleteEstimate': 'Delete estimate', 'job.deleteText': 'Job #{no} and everything on it will be deleted. This can\'t be undone. Jobs with payments or invoices can\'t be deleted.',
  'job.deleteYes': 'Yes, delete', 'job.closeText': 'Use this for an estimate that won\'t go ahead, e.g. the company declined all work. It leaves the board and can be reopened. Jobs with approved work or money on them can\'t be closed.',
  'job.closeYes': 'Close job', 'job.closedToast': 'Job closed', 'job.reason': 'Reason',
  'job.tab.services': 'Services', 'job.tab.concerns': 'Concerns', 'job.tab.inspections': 'Inspections', 'job.tab.activity': 'Activity',

  // Services
  'job.searchBundles': 'Add a service bundle or flat rate item…', 'job.flat': 'Flat rate', 'job.bundle': 'Bundle', 'job.addService': 'Add service',
  'job.serviceName': 'Service name', 'job.add': 'Add', 'job.serviceAdded': '{name} added', 'job.noServices': 'No services yet',
  'job.noServicesText': 'Add a bundle or flat rate item above, or start an empty service and add labor and parts to it.',
  'job.technician': 'Technician', 'job.noTechnician': 'No technician', 'job.workStatus': 'Work status', 'job.serviceMenu': 'Actions for {name}',
  'job.moveUp': 'Move up', 'job.moveDown': 'Move down', 'job.serviceDiscount': 'Service discount…', 'job.removeFlat': 'Remove flat price',
  'job.makeFlat': 'Make it a flat price', 'job.deleteService': 'Delete service', 'job.deleteServiceYes': 'Yes, delete',
  'job.deleteServiceText': '"{name}" and its {n} lines will be removed from this job.',
  'job.serviceNotes': 'Service notes (printed on invoice)', 'job.checklist': 'Checklist', 'job.nextDue': 'On completion: next due {when}',
  'job.forConcern': 'Concern this service is for', 'job.noConcernLink': 'Not linked to a concern', 'job.forConcernX': 'For: {text}',
  'job.col.type': 'Type', 'job.col.qty': 'Qty / hrs', 'job.col.amount': 'Amount', 'job.col.discount': 'Discount', 'job.col.net': 'Net', 'job.col.status': 'Status', 'job.col.actions': 'Actions',
  'job.type.labor': 'Labor', 'job.type.part': 'Part', 'job.type.fee': 'Fee', 'job.type.sublet': 'Sublet',
  'job.newLine.labor': 'Labor', 'job.newLine.part': 'Part', 'job.newLine.fee': 'Fee', 'job.newLine.sublet': 'Sublet (outside work)',
  'job.noLines': 'No lines yet. Search the catalog below or add a custom line.', 'job.rateHint': '{name} {amount}/h', 'job.coreHint': 'core {amount}',
  'job.removeLine': 'Remove {name}', 'job.searchItems': 'Add labor, part or fee from the catalog…', 'job.customLine': '+ Custom line…',
  'job.flatPrice': 'Flat price', 'job.linesWorth': 'lines worth {amount}', 'job.serviceTotal': 'Service total', 'job.serviceNet': 'Service net',
  'job.outHint.declined': 'Declined: not billed and not counted in the totals.', 'job.outHint.deferred': 'Deferred: not billed now; it appears in the Deferred list for a later visit.',
  'job.qtyRule': 'A quantity from 0 to 100.000.', 'job.discountRule': 'Type a percentage like 10% or an amount like 50.000.',
  'job.worked': 'Worked', 'job.hoursWorked': 'Hours worked', 'job.hoursWorkedHint': 'Hours actually worked, entered by the service advisor, for the technician report.',
  'job.stock.taken': 'Taken from stock', 'job.stock.in': 'In stock', 'job.stock.only': 'Only {n} in stock', 'job.stock.out': 'Out of stock', 'job.stockN': '{n} in stock',
  'job.serviceDiscountFor': 'Discount on {name}', 'job.discountValue': 'Discount', 'job.discountHint': 'Type 10% for a percentage or 50.000 for an amount. Leave empty for none.',
  'job.appr.pending': 'Pending', 'job.appr.approved': 'Approved', 'job.appr.deferred': 'Deferred', 'job.appr.declined': 'Declined',
  'job.work.todo': 'To do', 'job.work.in_progress': 'In progress', 'job.work.completed': 'Completed',

  // Approvals
  'job.recordApproval': 'Record approval', 'job.approvals': 'Approvals', 'job.services': 'Services', 'job.decision': 'Decision',
  'job.decide.approved': 'Approve', 'job.decide.deferred': 'Defer', 'job.decide.declined': 'Decline', 'job.decide.pending': 'Back to pending',
  'job.decideHint.approved': 'Approved work is billed when the job is invoiced.', 'job.decideHint.deferred': 'Put off for a later visit; not billed now.',
  'job.decideHint.declined': 'The company doesn\'t want this work; not billed.', 'job.decideHint.pending': 'Undo a decision; the service waits for approval again.',
  'job.method': 'How', 'job.approvedBy': 'Decided by', 'job.canApprove': 'can approve', 'job.someoneElse': 'Someone else…', 'job.approverName': 'Name',
  'job.optional': 'Optional', 'job.note': 'Note', 'job.approvalNoteExample': 'e.g. Approved by phone, PO to follow',
  'job.saveDecision': 'Save decision', 'job.approvalSaved': 'Decision saved for {n} service(s)', 'job.pickServices': 'Pick at least one service.',
  'job.whoApproved': 'Say who made the decision.',
  'job.via.in_person': 'In person', 'job.via.phone': 'Phone', 'job.via.whatsapp': 'WhatsApp', 'job.via.email': 'Email', 'job.via.internal': 'Internal',

  // Status card
  'job.orderStatus': 'Order status', 'job.createInvoice': 'Create invoice', 'job.createInvoiceYes': 'Create invoice', 'job.dueDate': 'Due date',
  'job.fakturNo': 'Faktur pajak no.', 'job.voidInvoice': 'Void invoice', 'job.closedOn': 'Closed on {date}: {reason}', 'job.workflow': 'Workflow',
  'job.pickedUp': 'Picked up {date}', 'job.undo': 'Undo', 'job.markPickedUp': 'Mark picked up', 'job.payment': 'Payment',
  'job.termsCash': 'Cash on delivery', 'job.termsNet': 'Terms Net {n}',
  'job.wf.estimate': 'Estimate', 'job.wf.scheduled': 'Scheduled', 'job.wf.arrived': 'Arrived', 'job.wf.in_progress': 'In progress',
  'job.wf.waiting_parts': 'Waiting for parts', 'job.wf.completed': 'Completed', 'job.wf.invoiced': 'Invoiced', 'job.wf.paid': 'Paid',
  'job.ps.unpaid': 'Unpaid', 'job.ps.partial': 'Part paid', 'job.ps.paid': 'Paid',
  'job.state.estimate': 'Estimate', 'job.state.closed': 'Closed', 'job.state.paid': 'Paid', 'job.state.overdue': 'Overdue', 'job.state.partial': 'Part paid', 'job.state.unpaid': 'Unpaid',

  // Invoice
  'job.stillPending': '{n} service(s) still need a decision: {names}. Record approval first.', 'job.noneApproved': 'Approve at least one service before invoicing.',
  'job.billTo': 'Bill to', 'job.approvedServices': 'Approved services', 'job.total': 'Total', 'job.netDays': 'Net {n}',
  'job.invoiceHint': 'The invoice gets the next invoice number and is locked. Approved parts come off stock. Declined and deferred work isn\'t billed.',
  'job.voidText': '{no} will be kept as VOID with your reason, and the job goes back to an estimate so it can be corrected and invoiced again under a new number. Payments become a company credit and are applied again. Only Owners and Admins can do this.',
  'job.voidYes': 'Void invoice', 'job.voidedToast': 'Invoice voided', 'job.voidLine': '{no} voided on {date} by {who}: {reason}',

  // Totals
  'job.totals': 'Totals', 'job.parts': 'Parts', 'job.labor': 'Labor', 'job.sublet': 'Sublet', 'job.itemDiscount': 'Item discounts', 'job.serviceFees': 'Service fees',
  'job.serviceDiscounts': 'Service discounts', 'job.shopSupplies': 'Shop supplies', 'job.shopSuppliesRate': 'Shop supplies rate', 'job.removeX': 'Remove {name}',
  'job.fee': 'Fee', 'job.discount': 'Discount', 'job.subtotal': 'Subtotal', 'job.taxLine': '{tax} {rate}% (taxable {base})', 'job.taxExempt': '{tax} (tax exempt)',
  'job.paidToDate': 'Paid to date', 'job.ofWhichCredit': 'of which credit', 'job.balance': 'Balance', 'job.credit': 'Credit',
  'job.receiptX': 'receipt {no}', 'job.deletePayment': 'Delete payment', 'job.paymentDeleted': 'Payment deleted',
  'job.profit': 'Expected profit', 'job.grossProfit': 'Gross profit', 'job.hoursBilledWorked': 'Hours billed / worked',
  'job.profitHint': 'Line prices minus cost, before service and job discounts. Declined and deferred work is left out.',

  // Payments and credits
  'job.recordPayment': 'Record payment', 'job.recordRefund': 'Record refund', 'job.kind': 'Type', 'job.kind.payment': 'Payment', 'job.kind.refund': 'Refund',
  'job.payMethod': 'Method', 'job.payDate': 'Date', 'job.reference': 'Reference', 'job.referenceExample': 'e.g. Transfer BCA 06/10', 'job.receiptNo': 'Receipt no.',
  'job.depositNote': 'This job isn\'t invoiced yet, so this is recorded as a deposit.', 'job.amountRule': 'Enter an amount above 0.',
  'job.overBalance': 'That is more than the balance due ({amount}).', 'job.overPaid': 'A refund can\'t be more than what was paid ({amount}).',
  'job.balanceIs': 'Balance due: {amount}', 'job.paymentSaved': 'Payment of {amount} saved', 'job.refundSaved': 'Refund of {amount} saved',
  'job.pay.transfer': 'Bank transfer', 'job.pay.cash': 'Cash', 'job.pay.card': 'Card', 'job.pay.giro': 'Giro', 'job.pay.other': 'Other',
  'job.credits': 'Company credits', 'job.appliedHere': 'Applied to this job', 'job.noAppliedCredits': 'No credits applied.', 'job.availableCredits': 'Available to apply',
  'job.noAvailableCredits': 'This company has no unused credit.', 'job.applyAmount': 'Amount to apply', 'job.apply': 'Apply', 'job.unapply': 'Take off',
  'job.creditApplied': 'Credit applied', 'job.creditUnapplied': 'Credit taken off', 'job.creditHint': 'Leave the amount empty to apply as much as is due ({amount}).',
  'job.issueCredit': 'Issue a new credit', 'job.issueCreditYes': 'Issue credit', 'job.issueCreditFor': 'Issue credit to {name}', 'job.creditIssued': 'Credit of {amount} issued',
  'job.creditReasonExample': 'e.g. Goodwill for repeat visit', 'job.issueHint': 'The credit belongs to {name} and can be applied to any of its jobs.',
  'job.addFee': 'Add job fee', 'job.fromCatalog': 'From the catalog', 'job.customFee': 'Custom fee', 'job.taxableFee': 'Taxable', 'job.feeAdded': 'Fee added',
  'job.addDiscount': 'Add job discount', 'job.customDiscount': 'Custom discount', 'job.discountAdded': 'Discount added',

  // Concerns
  'job.concerns': 'Concerns', 'job.concernsHint': 'What the driver or fleet manager reported, in their words. Printed on the estimate and invoice.', 'job.concernN': 'Concern {n}',

  // Inspections
  'job.startFor': 'Start {name} ({service})', 'job.startInspection': 'Start inspection', 'job.start': 'Start', 'job.inspStarted': 'Inspection started',
  'job.noInspections': 'No inspections yet', 'job.noInspectionsText': 'Start one from a checklist. Services from a bundle with a checklist show a start button here.',
  'job.emptyInspection': 'Empty (add points one by one)', 'job.forService': 'For service', 'job.inspection': 'Inspection', 'job.inspStatus': 'Inspection status',
  'job.inspMenu': 'Inspection actions', 'job.deleteInspection': 'Delete inspection', 'job.noPointsYet': 'No points yet.', 'job.pickNote': 'Ready-made note…',
  'job.inspNote': 'Note', 'job.inspNoteFor': 'Note for {name}', 'job.isConcern': 'Added as concern', 'job.addAsConcern': 'Add as concern', 'job.addedAsConcern': 'Added to the concerns',

  // Activity
  'job.act.created': 'Job created', 'job.act.invoiced': 'Invoiced as {no}', 'job.act.voided': '{no} voided', 'job.act.closed': 'Closed without invoice',
  'job.act.reopened': 'Reopened', 'job.act.serviceAdded': 'Service added', 'job.act.serviceRemoved': 'Service removed', 'job.act.lineAdded': 'Line added',
  'job.act.lineRemoved': 'Line removed', 'job.act.added': 'added', 'job.act.removed': 'removed', 'job.act.approvalRemoved': 'Decision removed',
  'job.act.payment': 'Payment', 'job.act.refund': 'Refund', 'job.act.paymentDeleted': 'Payment deleted', 'job.act.creditApplied': 'Credit applied',
  'job.act.creditUnapplied': 'Credit taken off',
  'job.f.workflow_status': 'Workflow', 'job.f.priority': 'Priority', 'job.f.odometer_in': 'Odometer in', 'job.f.odometer_out': 'Odometer out',
  'job.f.shop_notes': 'Shop notes', 'job.f.service_advisor_id': 'Service advisor', 'job.f.recommendations': 'Recommendations', 'job.f.archived_at': 'Picked up',
  'job.f.faktur_pajak_number': 'Faktur pajak no.', 'job.f.due_date': 'Due date', 'job.f.name': 'Name', 'job.f.notes_external': 'Service notes',
  'job.f.technician_id': 'Technician', 'job.f.work_status': 'Work status', 'job.f.discount_pct': 'Discount %', 'job.f.discount_amount': 'Discount',
  'job.f.flat_price': 'Flat price', 'job.f.concern_id': 'Concern', 'job.f.price': 'Price', 'job.f.qty': 'Qty', 'job.f.cost': 'Cost', 'job.f.taxable': 'Taxable',
  'job.f.description': 'Description', 'job.f.item_type': 'Type', 'job.f.hours_worked': 'Hours worked', 'job.f.value': 'Value', 'job.f.kind': 'Type',
  'job.f.amount': 'Amount', 'job.f.method': 'Method', 'job.f.reference': 'Reference', 'job.f.receipt_number': 'Receipt no.', 'job.f.paid_at': 'Date',
  'job.f.decision': 'Decision', 'job.f.note': 'Note', 'job.f.approved_by_name': 'Decided by', 'job.f.customer_id': 'Company', 'job.f.vehicle_id': 'Vehicle',
  'job.f.tags': 'Tags', 'job.f.checklist_id': 'Checklist', 'job.f.max_amount': 'Maximum', 'job.f.core_charge': 'Core charge', 'job.f.show_qty_price': 'Show qty and price',
  'job.f.manual_override': 'Typed amount', 'job.f.order_status': 'Order status', 'job.f.invoice_number': 'Invoice no.', 'job.f.invoiced_at': 'Invoiced',

  // Lists
  'jobs.roSub': 'Estimates that aren\'t invoiced yet', 'jobs.search': 'Search job #, company or plate', 'jobs.f.open': 'Open', 'jobs.f.closed': 'Closed',
  'jobs.noEstimates': 'No repair orders yet', 'jobs.noEstimatesText': 'Create a job from the + button, or from a company or vehicle.',
  'jobs.col.job': 'Job #', 'jobs.col.created': 'Created', 'jobs.roTotal': '{n} jobs · {amount} in estimates',
  'jobs.invSub': 'Invoices and what is still owed', 'jobs.searchInv': 'Search invoice #, job #, company or plate', 'jobs.f.unpaid': 'Not fully paid',
  'jobs.noInvoices': 'No invoices yet', 'jobs.noInvoicesText': 'Invoices appear here when an estimate is invoiced.',
  'jobs.col.invoice': 'Invoice #', 'jobs.col.date': 'Date', 'jobs.invTotal': '{n} invoices · {amount} outstanding · {overdue} overdue',
  'jobs.paySub': 'Payments and refunds recorded on jobs', 'jobs.searchPay': 'Search company, job #, invoice # or reference',
  'jobs.noPayments': 'No payments yet', 'jobs.noPaymentsText': 'Payments are recorded on the job page.', 'jobs.col.forJob': 'Job / invoice', 'jobs.payTotal': '{n} entries · {amount} received',
  'jobs.defSub': 'Work the companies put off, to offer again on a later visit', 'jobs.searchDef': 'Search service, company, plate or job #',
  'jobs.noDeferred': 'Nothing deferred', 'jobs.noDeferredText': 'Services marked Deferred on a job appear here.', 'jobs.col.service': 'Service', 'jobs.col.deferredOn': 'Deferred on',
  'jobs.noJobsYet': 'No jobs yet', 'jobs.noJobsYetText': 'Jobs for this company or vehicle appear here.',
  'jobs.noVehicleInsp': 'No inspections yet', 'jobs.noVehicleInspText': 'Inspection results from this vehicle\'s jobs appear here.',
  'search.jobs': 'Jobs',
  'job.inspLocked': 'This job is invoiced, so its inspections are locked. Void the invoice to correct them.',
  'job.act.concernAdded': 'Concern added', 'job.act.concernRemoved': 'Concern removed', 'job.act.concernChanged': 'Concern changed', 'job.act.concernsReordered': 'Concerns reordered',
  'job.act.inspStarted': 'Inspection started', 'job.act.inspDeleted': 'Inspection deleted', 'job.act.pointsAdded': '{n} inspection points added', 'job.act.pointAdded': 'Inspection point added',
  'job.act.pointRemoved': 'Inspection point removed', 'job.act.stockTaken': 'taken from stock', 'job.act.stockBack': 'put back in stock', 'job.f.inspection_status': 'Inspection status',
  'job.discountTooBig': 'The discount is more than the line amount.', 'job.itemDiscountIncl': 'incl. line discounts', 'job.deletePaymentYes': 'Yes, delete',
  'job.deletePaymentText': 'Delete the {method} payment of {amount} from {date}? The balance goes up again.', 'jobs.movedToCredit': 'Moved to credit',
  'err.inUse': 'This is still used elsewhere, so it can\'t be removed.',
  // Printing (labels follow the print language)
  'pr.back': 'Back to job', 'pr.estimateUi': 'Estimate', 'pr.invoiceUi': 'Invoice', 'pr.notInvoiced': 'This job isn\'t invoiced yet',
  'pr.estimate': 'ESTIMATE', 'pr.invoice': 'INVOICE', 'pr.invoiceNo': 'Invoice no.', 'pr.estimateNo': 'Estimate no.', 'pr.jobNo': 'Job no.', 'pr.date': 'Date',
  'pr.due': 'Due date', 'pr.faktur': 'Faktur pajak no.', 'pr.billTo': 'Bill to', 'pr.customer': 'Customer', 'pr.attn': 'Attn. {name}', 'pr.vehicle': 'Vehicle',
  'pr.odometer': 'Odometer', 'pr.concerns': 'Customer concerns', 'pr.description': 'Description', 'pr.qty': 'Qty', 'pr.unitPrice': 'Unit price',
  'pr.discount': 'Discount', 'pr.amount': 'Amount', 'pr.awaiting': 'Awaiting approval', 'pr.hrs': 'h', 'pr.coreCharge': 'Core charge · {name}',
  'pr.serviceDiscount': 'Service discount', 'pr.flatPrice': 'Package price', 'pr.serviceTotal': 'Service total', 'pr.noWork': 'No work on this document yet.',
  'pr.recommendations': 'Recommendations', 'pr.notIncluded': 'Not included in this estimate', 'pr.st.declined': 'declined', 'pr.st.deferred': 'deferred',
  'pr.payTo': 'Payment to', 'pr.nonPkp': 'The shop is not a PKP, so no PPN is charged.', 'pr.parts': 'Parts', 'pr.labor': 'Labor', 'pr.sublet': 'Sublet',
  'pr.fees': 'Fees', 'pr.serviceDiscounts': 'Service discounts', 'pr.shopSupplies': 'Shop supplies', 'pr.subtotal': 'Subtotal', 'pr.tax': '{tax} {rate}% (taxable {base})',
  'pr.total': 'Total', 'pr.paid': 'Paid', 'pr.deposit': 'Deposit received', 'pr.balance': 'Balance due', 'pr.receivedBy': 'Received by', 'pr.approvedBy': 'Approved by',
  'pr.shopSign': 'For the workshop', 'pr.estimateFoot': 'This estimate is not an invoice. Prices may change if more work is found.', 'pr.invoiceFoot': 'Please quote the invoice number with your payment.',
}

export const jobsId = {
  // New job
  'job.newTitle': 'Pekerjaan baru', 'job.newSub': 'Pilih perusahaan dan kendaraan; servis ditambahkan di halaman pekerjaan.',
  'job.company': 'Perusahaan', 'job.searchCompany': 'Cari nama perusahaan atau pelat', 'job.vehicle': 'Kendaraan', 'job.pickVehicle': 'Pilih kendaraan',
  'job.noVehicles': 'Perusahaan ini belum punya kendaraan', 'job.pickCompanyFirst': 'Pilih perusahaan dulu', 'job.addVehicleFirst': 'Tambahkan kendaraan ke perusahaan ini dulu',
  'job.alreadyOpen': 'Kendaraan ini sudah punya pekerjaan terbuka:', 'job.odometerIn': 'Odometer masuk', 'job.odometerOut': 'Odometer keluar',
  'job.lastKnown': 'Terakhir: {km}', 'job.lowerThanLast': 'Lebih rendah dari angka terakhir ({km}). Periksa angkanya.',
  'job.priority': 'Prioritas', 'job.advisor': 'Service advisor', 'job.concern': 'Keluhan pelanggan',
  'job.concernExample': 'mis. Rem berdecit saat berhenti', 'job.concernHint': 'Yang dilaporkan sopir atau fleet manager. Bisa ditambah nanti.',
  'job.create': 'Buat pekerjaan', 'job.created': 'Pekerjaan #{no} dibuat', 'job.noCustomers': 'Belum ada perusahaan', 'job.noCustomersText': 'Tambahkan perusahaan dan kendaraannya terlebih dahulu.',
  'job.pri.low': 'Rendah', 'job.pri.medium': 'Sedang', 'job.pri.high': 'Tinggi', 'job.pri.urgent': 'Mendesak',

  // Job page header
  'job.jobNo': 'Pekerjaan #{no}', 'job.estimate': 'Estimasi', 'job.invoice': 'Invoice', 'job.closed': 'Ditutup', 'job.notFound': 'Pekerjaan ini sudah tidak ada',
  'job.backToList': 'Kembali ke repair order', 'job.print': 'Cetak', 'job.printSoon': 'Fitur cetak hadir di tahap 5', 'job.more': 'Aksi lain',
  'job.customer': 'Pelanggan', 'job.attn': 'U.p. {name}', 'job.odoIn': 'Masuk', 'job.odoOut': 'Keluar', 'job.customerConcern': 'Keluhan pelanggan',
  'job.noConcerns': 'Belum ada keluhan yang ditulis.', 'job.editConcerns': 'Ubah keluhan', 'job.addConcern': 'Tambah keluhan',
  'job.shopNotes': 'Catatan bengkel (internal)', 'job.shopNotesHint': 'Hanya staf yang melihat, mis. part sedang dipesan, perkiraan datang.',
  'job.recommendations': 'Rekomendasi (dicetak)', 'job.recommendationsHint': 'Saran untuk kunjungan berikutnya, dicetak di invoice.',
  'job.closedNotice': 'Pekerjaan ini ditutup tanpa invoice: {reason}. Buka kembali untuk mengubah.',
  'job.invoicedNotice': 'Pekerjaan ini sudah di-invoice, jadi pekerjaan, harga, keluhan, dan inspeksinya terkunci. Pembayaran, teknisi, dan status kerja masih bisa diubah. Batalkan invoice untuk mengoreksi.',
  'job.pickedUpBadge': 'Sudah diambil', 'job.closeNoInvoice': 'Tutup tanpa invoice', 'job.reopen': 'Buka kembali', 'job.reopened': 'Pekerjaan dibuka kembali',
  'job.deleteEstimate': 'Hapus estimasi', 'job.deleteText': 'Pekerjaan #{no} dan semua isinya akan dihapus. Tidak bisa dibatalkan. Pekerjaan dengan pembayaran atau invoice tidak bisa dihapus.',
  'job.deleteYes': 'Ya, hapus', 'job.closeText': 'Pakai ini untuk estimasi yang tidak jadi, mis. perusahaan menolak semua pekerjaan. Pekerjaan keluar dari papan dan bisa dibuka kembali. Pekerjaan dengan pekerjaan disetujui atau ada uangnya tidak bisa ditutup.',
  'job.closeYes': 'Tutup pekerjaan', 'job.closedToast': 'Pekerjaan ditutup', 'job.reason': 'Alasan',
  'job.tab.services': 'Servis', 'job.tab.concerns': 'Keluhan', 'job.tab.inspections': 'Inspeksi', 'job.tab.activity': 'Aktivitas',

  // Services
  'job.searchBundles': 'Tambah paket servis atau paket harga tetap…', 'job.flat': 'Harga tetap', 'job.bundle': 'Paket', 'job.addService': 'Tambah servis',
  'job.serviceName': 'Nama servis', 'job.add': 'Tambah', 'job.serviceAdded': '{name} ditambahkan', 'job.noServices': 'Belum ada servis',
  'job.noServicesText': 'Tambahkan paket atau paket harga tetap di atas, atau mulai servis kosong lalu tambahkan jasa dan part.',
  'job.technician': 'Teknisi', 'job.noTechnician': 'Tanpa teknisi', 'job.workStatus': 'Status kerja', 'job.serviceMenu': 'Aksi untuk {name}',
  'job.moveUp': 'Pindah ke atas', 'job.moveDown': 'Pindah ke bawah', 'job.serviceDiscount': 'Diskon servis…', 'job.removeFlat': 'Hapus harga tetap',
  'job.makeFlat': 'Jadikan harga tetap', 'job.deleteService': 'Hapus servis', 'job.deleteServiceYes': 'Ya, hapus',
  'job.deleteServiceText': '"{name}" dan {n} barisnya akan dihapus dari pekerjaan ini.',
  'job.serviceNotes': 'Catatan servis (dicetak di invoice)', 'job.checklist': 'Daftar periksa', 'job.nextDue': 'Saat selesai: jadwal berikutnya {when}',
  'job.forConcern': 'Keluhan yang ditangani servis ini', 'job.noConcernLink': 'Tidak terkait keluhan', 'job.forConcernX': 'Untuk: {text}',
  'job.col.type': 'Jenis', 'job.col.qty': 'Jml / jam', 'job.col.amount': 'Jumlah', 'job.col.discount': 'Diskon', 'job.col.net': 'Neto', 'job.col.status': 'Status', 'job.col.actions': 'Aksi',
  'job.type.labor': 'Jasa', 'job.type.part': 'Part', 'job.type.fee': 'Biaya', 'job.type.sublet': 'Sublet',
  'job.newLine.labor': 'Jasa', 'job.newLine.part': 'Part', 'job.newLine.fee': 'Biaya', 'job.newLine.sublet': 'Sublet (pekerjaan luar)',
  'job.noLines': 'Belum ada baris. Cari di katalog di bawah atau tambah baris manual.', 'job.rateHint': '{name} {amount}/jam', 'job.coreHint': 'core {amount}',
  'job.removeLine': 'Hapus {name}', 'job.searchItems': 'Tambah jasa, part, atau biaya dari katalog…', 'job.customLine': '+ Baris manual…',
  'job.flatPrice': 'Harga tetap', 'job.linesWorth': 'nilai baris {amount}', 'job.serviceTotal': 'Total servis', 'job.serviceNet': 'Neto servis',
  'job.outHint.declined': 'Ditolak: tidak ditagih dan tidak dihitung di total.', 'job.outHint.deferred': 'Ditunda: tidak ditagih sekarang; muncul di daftar Ditunda untuk kunjungan berikutnya.',
  'job.qtyRule': 'Jumlah dari 0 sampai 100.000.', 'job.discountRule': 'Ketik persen seperti 10% atau jumlah seperti 50.000.',
  'job.worked': 'Dikerjakan', 'job.hoursWorked': 'Jam dikerjakan', 'job.hoursWorkedHint': 'Jam kerja sebenarnya, diisi service advisor, untuk laporan teknisi.',
  'job.stock.taken': 'Diambil dari stok', 'job.stock.in': 'Ada stok', 'job.stock.only': 'Stok tinggal {n}', 'job.stock.out': 'Stok habis', 'job.stockN': 'stok {n}',
  'job.serviceDiscountFor': 'Diskon untuk {name}', 'job.discountValue': 'Diskon', 'job.discountHint': 'Ketik 10% untuk persen atau 50.000 untuk jumlah. Kosongkan jika tidak ada.',
  'job.appr.pending': 'Menunggu', 'job.appr.approved': 'Disetujui', 'job.appr.deferred': 'Ditunda', 'job.appr.declined': 'Ditolak',
  'job.work.todo': 'Belum', 'job.work.in_progress': 'Dikerjakan', 'job.work.completed': 'Selesai',

  // Approvals
  'job.recordApproval': 'Catat persetujuan', 'job.approvals': 'Persetujuan', 'job.services': 'Servis', 'job.decision': 'Keputusan',
  'job.decide.approved': 'Setujui', 'job.decide.deferred': 'Tunda', 'job.decide.declined': 'Tolak', 'job.decide.pending': 'Kembalikan ke menunggu',
  'job.decideHint.approved': 'Pekerjaan yang disetujui ditagih saat di-invoice.', 'job.decideHint.deferred': 'Ditunda untuk kunjungan berikutnya; tidak ditagih sekarang.',
  'job.decideHint.declined': 'Perusahaan tidak mau pekerjaan ini; tidak ditagih.', 'job.decideHint.pending': 'Batalkan keputusan; servis menunggu persetujuan lagi.',
  'job.method': 'Lewat', 'job.approvedBy': 'Diputuskan oleh', 'job.canApprove': 'boleh menyetujui', 'job.someoneElse': 'Orang lain…', 'job.approverName': 'Nama',
  'job.optional': 'Opsional', 'job.note': 'Catatan', 'job.approvalNoteExample': 'mis. Disetujui lewat telepon, PO menyusul',
  'job.saveDecision': 'Simpan keputusan', 'job.approvalSaved': 'Keputusan disimpan untuk {n} servis', 'job.pickServices': 'Pilih minimal satu servis.',
  'job.whoApproved': 'Sebutkan siapa yang memutuskan.',
  'job.via.in_person': 'Langsung', 'job.via.phone': 'Telepon', 'job.via.whatsapp': 'WhatsApp', 'job.via.email': 'Email', 'job.via.internal': 'Internal',

  // Status card
  'job.orderStatus': 'Status order', 'job.createInvoice': 'Buat invoice', 'job.createInvoiceYes': 'Buat invoice', 'job.dueDate': 'Jatuh tempo',
  'job.fakturNo': 'No. faktur pajak', 'job.voidInvoice': 'Batalkan invoice', 'job.closedOn': 'Ditutup {date}: {reason}', 'job.workflow': 'Alur kerja',
  'job.pickedUp': 'Diambil {date}', 'job.undo': 'Batalkan', 'job.markPickedUp': 'Tandai sudah diambil', 'job.payment': 'Pembayaran',
  'job.termsCash': 'Tunai saat selesai', 'job.termsNet': 'Termin {n} hari',
  'job.wf.estimate': 'Estimasi', 'job.wf.scheduled': 'Dijadwalkan', 'job.wf.arrived': 'Sudah datang', 'job.wf.in_progress': 'Dikerjakan',
  'job.wf.waiting_parts': 'Menunggu part', 'job.wf.completed': 'Selesai', 'job.wf.invoiced': 'Di-invoice', 'job.wf.paid': 'Lunas',
  'job.ps.unpaid': 'Belum dibayar', 'job.ps.partial': 'Dibayar sebagian', 'job.ps.paid': 'Lunas',
  'job.state.estimate': 'Estimasi', 'job.state.closed': 'Ditutup', 'job.state.paid': 'Lunas', 'job.state.overdue': 'Lewat jatuh tempo', 'job.state.partial': 'Dibayar sebagian', 'job.state.unpaid': 'Belum dibayar',

  // Invoice
  'job.stillPending': '{n} servis masih perlu keputusan: {names}. Catat persetujuan dulu.', 'job.noneApproved': 'Setujui minimal satu servis sebelum membuat invoice.',
  'job.billTo': 'Ditagihkan ke', 'job.approvedServices': 'Servis disetujui', 'job.total': 'Total', 'job.netDays': '{n} hari',
  'job.invoiceHint': 'Invoice mendapat nomor invoice berikutnya dan dikunci. Part yang disetujui keluar dari stok. Pekerjaan ditolak dan ditunda tidak ditagih.',
  'job.voidText': '{no} disimpan sebagai BATAL dengan alasan Anda, dan pekerjaan kembali menjadi estimasi agar bisa dikoreksi dan di-invoice lagi dengan nomor baru. Pembayaran menjadi kredit perusahaan dan diterapkan kembali. Hanya Pemilik dan Admin yang bisa.',
  'job.voidYes': 'Batalkan invoice', 'job.voidedToast': 'Invoice dibatalkan', 'job.voidLine': '{no} dibatalkan {date} oleh {who}: {reason}',

  // Totals
  'job.totals': 'Total', 'job.parts': 'Part', 'job.labor': 'Jasa', 'job.sublet': 'Sublet', 'job.itemDiscount': 'Diskon baris', 'job.serviceFees': 'Biaya servis',
  'job.serviceDiscounts': 'Diskon servis', 'job.shopSupplies': 'Bahan habis pakai', 'job.shopSuppliesRate': 'Tarif bahan habis pakai', 'job.removeX': 'Hapus {name}',
  'job.fee': 'Biaya', 'job.discount': 'Diskon', 'job.subtotal': 'Subtotal', 'job.taxLine': '{tax} {rate}% (DPP {base})', 'job.taxExempt': '{tax} (bebas pajak)',
  'job.paidToDate': 'Sudah dibayar', 'job.ofWhichCredit': 'termasuk kredit', 'job.balance': 'Sisa tagihan', 'job.credit': 'Kredit',
  'job.receiptX': 'kuitansi {no}', 'job.deletePayment': 'Hapus pembayaran', 'job.paymentDeleted': 'Pembayaran dihapus',
  'job.profit': 'Perkiraan laba', 'job.grossProfit': 'Laba kotor', 'job.hoursBilledWorked': 'Jam ditagih / dikerjakan',
  'job.profitHint': 'Harga baris dikurangi modal, sebelum diskon servis dan pekerjaan. Pekerjaan ditolak dan ditunda tidak dihitung.',

  // Payments and credits
  'job.recordPayment': 'Catat pembayaran', 'job.recordRefund': 'Catat pengembalian dana', 'job.kind': 'Jenis', 'job.kind.payment': 'Pembayaran', 'job.kind.refund': 'Pengembalian',
  'job.payMethod': 'Metode', 'job.payDate': 'Tanggal', 'job.reference': 'Referensi', 'job.referenceExample': 'mis. Transfer BCA 06/10', 'job.receiptNo': 'No. kuitansi',
  'job.depositNote': 'Pekerjaan ini belum di-invoice, jadi dicatat sebagai uang muka.', 'job.amountRule': 'Masukkan jumlah di atas 0.',
  'job.overBalance': 'Itu lebih dari sisa tagihan ({amount}).', 'job.overPaid': 'Pengembalian tidak boleh lebih dari yang sudah dibayar ({amount}).',
  'job.balanceIs': 'Sisa tagihan: {amount}', 'job.paymentSaved': 'Pembayaran {amount} disimpan', 'job.refundSaved': 'Pengembalian {amount} disimpan',
  'job.pay.transfer': 'Transfer bank', 'job.pay.cash': 'Tunai', 'job.pay.card': 'Kartu', 'job.pay.giro': 'Giro', 'job.pay.other': 'Lainnya',
  'job.credits': 'Kredit perusahaan', 'job.appliedHere': 'Diterapkan ke pekerjaan ini', 'job.noAppliedCredits': 'Belum ada kredit yang diterapkan.', 'job.availableCredits': 'Bisa diterapkan',
  'job.noAvailableCredits': 'Perusahaan ini tidak punya kredit yang belum dipakai.', 'job.applyAmount': 'Jumlah yang diterapkan', 'job.apply': 'Terapkan', 'job.unapply': 'Lepas',
  'job.creditApplied': 'Kredit diterapkan', 'job.creditUnapplied': 'Kredit dilepas', 'job.creditHint': 'Kosongkan jumlah untuk menerapkan sebanyak yang ditagih ({amount}).',
  'job.issueCredit': 'Terbitkan kredit baru', 'job.issueCreditYes': 'Terbitkan kredit', 'job.issueCreditFor': 'Terbitkan kredit untuk {name}', 'job.creditIssued': 'Kredit {amount} diterbitkan',
  'job.creditReasonExample': 'mis. Kompensasi kunjungan ulang', 'job.issueHint': 'Kredit ini milik {name} dan bisa diterapkan ke pekerjaan mana pun milik perusahaan itu.',
  'job.addFee': 'Tambah biaya pekerjaan', 'job.fromCatalog': 'Dari katalog', 'job.customFee': 'Biaya manual', 'job.taxableFee': 'Kena pajak', 'job.feeAdded': 'Biaya ditambahkan',
  'job.addDiscount': 'Tambah diskon pekerjaan', 'job.customDiscount': 'Diskon manual', 'job.discountAdded': 'Diskon ditambahkan',

  // Concerns
  'job.concerns': 'Keluhan', 'job.concernsHint': 'Yang dilaporkan sopir atau fleet manager, dengan kata-kata mereka. Dicetak di estimasi dan invoice.', 'job.concernN': 'Keluhan {n}',

  // Inspections
  'job.startFor': 'Mulai {name} ({service})', 'job.startInspection': 'Mulai inspeksi', 'job.start': 'Mulai', 'job.inspStarted': 'Inspeksi dimulai',
  'job.noInspections': 'Belum ada inspeksi', 'job.noInspectionsText': 'Mulai dari daftar periksa. Servis dari paket yang punya daftar periksa menampilkan tombol mulai di sini.',
  'job.emptyInspection': 'Kosong (tambah poin satu per satu)', 'job.forService': 'Untuk servis', 'job.inspection': 'Inspeksi', 'job.inspStatus': 'Status inspeksi',
  'job.inspMenu': 'Aksi inspeksi', 'job.deleteInspection': 'Hapus inspeksi', 'job.noPointsYet': 'Belum ada poin.', 'job.pickNote': 'Catatan siap pakai…',
  'job.inspNote': 'Catatan', 'job.inspNoteFor': 'Catatan untuk {name}', 'job.isConcern': 'Jadi keluhan', 'job.addAsConcern': 'Jadikan keluhan', 'job.addedAsConcern': 'Ditambahkan ke keluhan',

  // Activity
  'job.act.created': 'Pekerjaan dibuat', 'job.act.invoiced': 'Di-invoice sebagai {no}', 'job.act.voided': '{no} dibatalkan', 'job.act.closed': 'Ditutup tanpa invoice',
  'job.act.reopened': 'Dibuka kembali', 'job.act.serviceAdded': 'Servis ditambahkan', 'job.act.serviceRemoved': 'Servis dihapus', 'job.act.lineAdded': 'Baris ditambahkan',
  'job.act.lineRemoved': 'Baris dihapus', 'job.act.added': 'ditambahkan', 'job.act.removed': 'dihapus', 'job.act.approvalRemoved': 'Keputusan dihapus',
  'job.act.payment': 'Pembayaran', 'job.act.refund': 'Pengembalian', 'job.act.paymentDeleted': 'Pembayaran dihapus', 'job.act.creditApplied': 'Kredit diterapkan',
  'job.act.creditUnapplied': 'Kredit dilepas',
  'job.f.workflow_status': 'Alur kerja', 'job.f.priority': 'Prioritas', 'job.f.odometer_in': 'Odometer masuk', 'job.f.odometer_out': 'Odometer keluar',
  'job.f.shop_notes': 'Catatan bengkel', 'job.f.service_advisor_id': 'Service advisor', 'job.f.recommendations': 'Rekomendasi', 'job.f.archived_at': 'Diambil',
  'job.f.faktur_pajak_number': 'No. faktur pajak', 'job.f.due_date': 'Jatuh tempo', 'job.f.name': 'Nama', 'job.f.notes_external': 'Catatan servis',
  'job.f.technician_id': 'Teknisi', 'job.f.work_status': 'Status kerja', 'job.f.discount_pct': 'Diskon %', 'job.f.discount_amount': 'Diskon',
  'job.f.flat_price': 'Harga tetap', 'job.f.concern_id': 'Keluhan', 'job.f.price': 'Harga', 'job.f.qty': 'Jml', 'job.f.cost': 'Modal', 'job.f.taxable': 'Kena pajak',
  'job.f.description': 'Deskripsi', 'job.f.item_type': 'Jenis', 'job.f.hours_worked': 'Jam dikerjakan', 'job.f.value': 'Nilai', 'job.f.kind': 'Jenis',
  'job.f.amount': 'Jumlah', 'job.f.method': 'Metode', 'job.f.reference': 'Referensi', 'job.f.receipt_number': 'No. kuitansi', 'job.f.paid_at': 'Tanggal',
  'job.f.decision': 'Keputusan', 'job.f.note': 'Catatan', 'job.f.approved_by_name': 'Diputuskan oleh', 'job.f.customer_id': 'Perusahaan', 'job.f.vehicle_id': 'Kendaraan',
  'job.f.tags': 'Tag', 'job.f.checklist_id': 'Daftar periksa', 'job.f.max_amount': 'Maksimum', 'job.f.core_charge': 'Biaya core', 'job.f.show_qty_price': 'Tampilkan jml dan harga',
  'job.f.manual_override': 'Jumlah diketik', 'job.f.order_status': 'Status order', 'job.f.invoice_number': 'No. invoice', 'job.f.invoiced_at': 'Di-invoice',

  // Lists
  'jobs.roSub': 'Estimasi yang belum di-invoice', 'jobs.search': 'Cari no. pekerjaan, perusahaan, atau pelat', 'jobs.f.open': 'Terbuka', 'jobs.f.closed': 'Ditutup',
  'jobs.noEstimates': 'Belum ada repair order', 'jobs.noEstimatesText': 'Buat pekerjaan dari tombol +, atau dari perusahaan atau kendaraan.',
  'jobs.col.job': 'No. pekerjaan', 'jobs.col.created': 'Dibuat', 'jobs.roTotal': '{n} pekerjaan · {amount} dalam estimasi',
  'jobs.invSub': 'Invoice dan sisa tagihannya', 'jobs.searchInv': 'Cari no. invoice, no. pekerjaan, perusahaan, atau pelat', 'jobs.f.unpaid': 'Belum lunas',
  'jobs.noInvoices': 'Belum ada invoice', 'jobs.noInvoicesText': 'Invoice muncul di sini saat estimasi di-invoice.',
  'jobs.col.invoice': 'No. invoice', 'jobs.col.date': 'Tanggal', 'jobs.invTotal': '{n} invoice · {amount} belum dibayar · {overdue} lewat jatuh tempo',
  'jobs.paySub': 'Pembayaran dan pengembalian yang dicatat di pekerjaan', 'jobs.searchPay': 'Cari perusahaan, no. pekerjaan, no. invoice, atau referensi',
  'jobs.noPayments': 'Belum ada pembayaran', 'jobs.noPaymentsText': 'Pembayaran dicatat di halaman pekerjaan.', 'jobs.col.forJob': 'Pekerjaan / invoice', 'jobs.payTotal': '{n} catatan · {amount} diterima',
  'jobs.defSub': 'Pekerjaan yang ditunda perusahaan, untuk ditawarkan lagi di kunjungan berikutnya', 'jobs.searchDef': 'Cari servis, perusahaan, pelat, atau no. pekerjaan',
  'jobs.noDeferred': 'Tidak ada yang ditunda', 'jobs.noDeferredText': 'Servis yang ditandai Ditunda di pekerjaan muncul di sini.', 'jobs.col.service': 'Servis', 'jobs.col.deferredOn': 'Ditunda pada',
  'jobs.noJobsYet': 'Belum ada pekerjaan', 'jobs.noJobsYetText': 'Pekerjaan untuk perusahaan atau kendaraan ini muncul di sini.',
  'jobs.noVehicleInsp': 'Belum ada inspeksi', 'jobs.noVehicleInspText': 'Hasil inspeksi dari pekerjaan kendaraan ini muncul di sini.',
  'search.jobs': 'Pekerjaan',
  'job.inspLocked': 'Pekerjaan ini sudah di-invoice, jadi inspeksinya terkunci. Batalkan invoice untuk mengoreksi.',
  'job.act.concernAdded': 'Keluhan ditambahkan', 'job.act.concernRemoved': 'Keluhan dihapus', 'job.act.concernChanged': 'Keluhan diubah', 'job.act.concernsReordered': 'Urutan keluhan diubah',
  'job.act.inspStarted': 'Inspeksi dimulai', 'job.act.inspDeleted': 'Inspeksi dihapus', 'job.act.pointsAdded': '{n} poin inspeksi ditambahkan', 'job.act.pointAdded': 'Poin inspeksi ditambahkan',
  'job.act.pointRemoved': 'Poin inspeksi dihapus', 'job.act.stockTaken': 'diambil dari stok', 'job.act.stockBack': 'dikembalikan ke stok', 'job.f.inspection_status': 'Status inspeksi',
  'job.discountTooBig': 'Diskon lebih besar dari jumlah baris.', 'job.itemDiscountIncl': 'termasuk diskon baris', 'job.deletePaymentYes': 'Ya, hapus',
  'job.deletePaymentText': 'Hapus pembayaran {method} sebesar {amount} tanggal {date}? Sisa tagihan naik lagi.', 'jobs.movedToCredit': 'Dipindah ke kredit',
  'err.inUse': 'Data ini masih dipakai di tempat lain, jadi tidak bisa dihapus.',
  // Indonesian wording of database rule messages (see errorText)
  "db:This job is closed. Reopen it first.": "Pekerjaan ini ditutup. Buka kembali dulu.",
  "db:Approve, decline or defer every service before invoicing": "Setujui, tolak, atau tunda setiap servis sebelum membuat invoice.",
  "db:Approve at least one service before invoicing": "Setujui minimal satu servis sebelum membuat invoice.",
  "db:This job is invoiced. Void the invoice to make changes.": "Pekerjaan ini sudah di-invoice. Batalkan invoice untuk mengubah.",
  "db:An invoiced job stays Invoiced (or Paid) on the board": "Pekerjaan yang sudah di-invoice tetap berstatus Di-invoice (atau Lunas).",
  "db:This job has approved work. Invoice it, or decline/defer the work first.": "Pekerjaan ini punya servis yang disetujui. Buat invoice, atau tolak/tunda dulu.",
  "db:This job has money on it. Refund the payments or unapply the credits first.": "Ada uang di pekerjaan ini. Kembalikan pembayaran atau lepas kreditnya dulu.",
  "db:Only an estimate can be closed without an invoice": "Hanya estimasi yang bisa ditutup tanpa invoice.",
  "db:A reason is required to close a job without an invoice": "Alasan wajib diisi untuk menutup pekerjaan tanpa invoice.",
  "db:A reason is required to void an invoice": "Alasan wajib diisi untuk membatalkan invoice.",
  "db:Only an owner or admin can record a refund on an issued invoice": "Hanya Pemilik atau Admin yang bisa mencatat pengembalian pada invoice.",
  "db:Only an owner or admin can change a payment on an issued invoice": "Hanya Pemilik atau Admin yang bisa mengubah pembayaran pada invoice.",
  "db:This entry was made by the system and can't be changed": "Catatan ini dibuat sistem dan tidak bisa diubah.",
  "db:This payment belongs to a voided invoice and is kept as history": "Pembayaran ini milik invoice yang dibatalkan dan disimpan sebagai riwayat.",
  "db:Refunds can't be more than the payments received on this job": "Pengembalian tidak boleh lebih dari pembayaran yang diterima di pekerjaan ini.",
  "db:Nothing is due on this job": "Tidak ada tagihan di pekerjaan ini.",
  "db:That is more than the credit available": "Itu lebih dari kredit yang tersedia.",
  "db:This credit is already applied": "Kredit ini sudah diterapkan.",
  "db:Only an owner or admin can take a credit off an issued invoice": "Hanya Pemilik atau Admin yang bisa melepas kredit dari invoice.",
  "db:An invoiced job can't be deleted. Void the invoice first.": "Pekerjaan yang sudah di-invoice tidak bisa dihapus. Batalkan invoice dulu.",
  "db:This vehicle belongs to another company": "Kendaraan ini milik perusahaan lain.",
  "db:Not allowed": "Anda tidak punya izin untuk ini.",
  "db:Only an Owner or Admin can adjust stock": "Hanya Pemilik atau Admin yang bisa menyesuaikan stok.",
  "db:Enter a reason for the adjustment": "Masukkan alasan penyesuaian.",
  "db:This part already has stock entries; use Adjust stock to correct the count": "Part ini sudah punya catatan stok; pakai Sesuaikan stok untuk mengoreksi.",
  "db:That is more than the balance due on this invoice": "Itu lebih dari sisa tagihan invoice ini.",
  "db:Payments received (Rp": "Pembayaran yang diterima lebih dari total invoice. Kembalikan selisihnya dulu.",
  "db:This credit (Rp": "Kredit ini lebih dari sisa tagihan. Terapkan sebagian saja.",
  "db:A credit can only be applied to a job of the same company": "Kredit hanya bisa diterapkan ke pekerjaan perusahaan yang sama.",
  "db:Only an unused, manually issued credit can be deleted": "Hanya kredit manual yang belum dipakai yang bisa dihapus.",
  // Printing (labels follow the print language)
  'pr.back': 'Kembali ke pekerjaan', 'pr.estimateUi': 'Estimasi', 'pr.invoiceUi': 'Invoice', 'pr.notInvoiced': 'Pekerjaan ini belum di-invoice',
  'pr.estimate': 'ESTIMASI', 'pr.invoice': 'INVOICE', 'pr.invoiceNo': 'No. invoice', 'pr.estimateNo': 'No. estimasi', 'pr.jobNo': 'No. pekerjaan', 'pr.date': 'Tanggal',
  'pr.due': 'Jatuh tempo', 'pr.faktur': 'No. faktur pajak', 'pr.billTo': 'Ditagihkan kepada', 'pr.customer': 'Pelanggan', 'pr.attn': 'U.p. {name}', 'pr.vehicle': 'Kendaraan',
  'pr.odometer': 'Odometer', 'pr.concerns': 'Keluhan pelanggan', 'pr.description': 'Uraian', 'pr.qty': 'Jml', 'pr.unitPrice': 'Harga satuan',
  'pr.discount': 'Diskon', 'pr.amount': 'Jumlah', 'pr.awaiting': 'Menunggu persetujuan', 'pr.hrs': 'jam', 'pr.coreCharge': 'Biaya core · {name}',
  'pr.serviceDiscount': 'Diskon servis', 'pr.flatPrice': 'Harga paket', 'pr.serviceTotal': 'Total servis', 'pr.noWork': 'Belum ada pekerjaan di dokumen ini.',
  'pr.recommendations': 'Rekomendasi', 'pr.notIncluded': 'Tidak termasuk dalam estimasi ini', 'pr.st.declined': 'ditolak', 'pr.st.deferred': 'ditunda',
  'pr.payTo': 'Pembayaran ke', 'pr.nonPkp': 'Bengkel bukan PKP, sehingga tidak dikenakan PPN.', 'pr.parts': 'Part', 'pr.labor': 'Jasa', 'pr.sublet': 'Sublet',
  'pr.fees': 'Biaya', 'pr.serviceDiscounts': 'Diskon servis', 'pr.shopSupplies': 'Bahan habis pakai', 'pr.subtotal': 'Subtotal', 'pr.tax': '{tax} {rate}% (DPP {base})',
  'pr.total': 'Total', 'pr.paid': 'Sudah dibayar', 'pr.deposit': 'Uang muka diterima', 'pr.balance': 'Sisa tagihan', 'pr.receivedBy': 'Diterima oleh', 'pr.approvedBy': 'Disetujui oleh',
  'pr.shopSign': 'Hormat kami', 'pr.estimateFoot': 'Estimasi ini bukan invoice. Harga dapat berubah bila ditemukan pekerjaan tambahan.', 'pr.invoiceFoot': 'Mohon cantumkan nomor invoice saat melakukan pembayaran.',
}
