// Screen text for stage 9a/9b: dashboard and reports (English / Bahasa Indonesia).
export const reportsEn = {
  // Dashboard
  'dash.today': 'Today', 'dash.money': 'Money', 'dash.attention': 'Needs attention',
  'dash.bookings': 'Bookings today', 'dash.requests': '{n} booking request(s) waiting', 'dash.noRequests': 'No requests waiting',
  'dash.inShop': 'In the shop', 'dash.nothingInShop': 'No open jobs in progress',
  'dash.waitingParts': 'Waiting on parts', 'dash.waitingPartsNote': 'Open jobs with parts ordered that haven\'t all arrived',
  'dash.readyInv': 'Ready to invoice', 'dash.readyNote': 'Work completed, not invoiced yet',
  'dash.invoicedMtd': 'Invoiced this month', 'dash.nInvoices': '{n} invoice(s)', 'dash.vsLast': '{pct} vs last month to date ({amount})',
  'dash.receivedMtd': 'Received this month', 'dash.receivedNote': 'Payments minus refunds',
  'dash.owed': 'Owed by companies', 'dash.openInvoices': '{n} invoice(s) not fully paid',
  'dash.overdue': 'Overdue', 'dash.overdueNote': '{n} invoice(s) · {amount} over 90 days', 'dash.noneOverdue': 'Nothing past its due date',
  'dash.service': 'Service due', 'dash.serviceDetail': '{over} overdue · {soon} due soon',
  'dash.lowStock': 'Parts low or out', 'dash.lowStockDetail': 'At or below the reorder point',
  'dash.bills': 'Supplier bills', 'dash.billsDetail': '{overdue} overdue · {soon} due in 7 days',
  'dash.cores': 'Cores', 'dash.coresDetail': '{take} to take off vehicles · {send} to send back',
  'dash.returns': 'Returns to suppliers', 'dash.returnsDetail': 'Not refunded yet',
  'dash.estimates': 'Open estimates', 'dash.estimatesDetail': 'Not scheduled or started yet',
  'dash.allClear': 'All clear',
  'dash.chartTitle': 'Last 6 months', 'dash.invoiced': 'Invoiced', 'dash.received': 'Received', 'dash.month': 'Month',
  'dash.showTable': 'Show figures', 'dash.hideTable': 'Hide figures', 'dash.chartEmpty': 'No invoices or payments in the last 6 months yet.',
  'dash.chartHint': 'Invoiced = invoices issued in the month (voided ones left out). Received = payments in the month minus refunds.',
  // Reports area
  'rep.tab.sales': 'Sales', 'rep.tab.aging': 'Receivables aging', 'rep.tab.payments': 'Payments received',
  'rep.noAccessTitle': 'Reports are for managers', 'rep.noAccessText': 'Your role doesn\'t include reports. An Owner or Admin can change this in Settings → Users & access.',
  'rep.moreSoon': 'More reports (profit, technicians, fleet spend, inventory, service compliance) arrive in stage 9b.',
  'rep.period': 'Period', 'rep.from': 'From', 'rep.to': 'To', 'rep.company': 'Company', 'rep.allCompanies': 'All companies',
  'rep.p.this_month': 'This month', 'rep.p.last_month': 'Last month', 'rep.p.last_30': 'Last 30 days', 'rep.p.this_year': 'This year',
  'rep.p.last_year': 'Last year', 'rep.p.custom': 'Choose dates…',
  'rep.groupBy': 'Group by', 'rep.g.auto': 'By day or month', 'rep.g.day': 'Day', 'rep.g.month': 'Month', 'rep.g.company': 'Company',
  'rep.g.invoices': 'Each invoice', 'rep.g.method': 'Method', 'rep.g.list': 'Each payment',
  'rep.csv': 'Download CSV', 'rep.empty': 'Nothing in this period', 'rep.total': 'Total', 'rep.jobNo': 'Job {no}', 'rep.paidUp': 'Paid',
  'rep.m.parts': 'Parts', 'rep.m.labor': 'Labor', 'rep.m.sublet': 'Sublet', 'rep.m.fees': 'Fees', 'rep.m.discounts': 'Discounts',
  'rep.m.subtotal': 'Before tax', 'rep.m.tax': 'Tax', 'rep.m.total': 'Total',
  'rep.col.invoice': 'Invoice', 'rep.col.date': 'Date', 'rep.col.job': 'Job', 'rep.col.company': 'Company', 'rep.col.plate': 'Plate',
  'rep.col.paid': 'Paid', 'rep.col.balance': 'Still owed', 'rep.col.invoices': 'Invoices', 'rep.col.due': 'Due', 'rep.col.daysOverdue': 'Days past due',
  'rep.col.bucket': 'Aging', 'rep.col.owed': 'Owed', 'rep.col.kind': 'Type', 'rep.col.method': 'Method', 'rep.col.reference': 'Reference',
  'rep.col.amount': 'Amount', 'rep.col.entries': 'Entries',
  // Sales
  'rep.sales.title': 'Sales', 'rep.sales.sub': 'Invoices issued in the period, split into parts, labor, sublet, fees and discounts.',
  'rep.sales.total': 'Total invoiced', 'rep.sales.nInvoices': '{n} invoice(s)', 'rep.sales.beforeTax': 'Parts + labor + sublet + fees − discounts',
  'rep.sales.emptyText': 'No invoices were issued in this period. Try a longer period or another company.',
  'rep.sales.hint': 'Counted on the invoice date (shop time). Voided invoices are left out, so a past month can go down if one of its invoices is voided later; a re-issued invoice counts on its new date. Parts include core charges. Line discounts are already taken off parts and labor; the Discounts column is service and job discounts.',
  'rep.sales.voids': '{n} invoice(s) worth {amount} were voided in this period and are not counted.', 'rep.sales.voidedOn': 'voided {date} (issued {issued})',
  'rep.show': 'Show', 'rep.hide': 'Hide', 'rep.aging.creditOnly': 'Nothing owed, credit only',
  // Aging
  'rep.aging.title': 'Receivables aging', 'rep.aging.sub': 'What each company still owes today, by how long it is past its due date.',
  'rep.aging.owed': 'Owed in total', 'rep.aging.nInvoices': '{n} invoice(s)', 'rep.aging.overdue': 'Past due', 'rep.aging.share': '{pct}% of what is owed',
  'rep.aging.credit': 'Unused credit', 'rep.aging.creditNote': 'Can be applied to these invoices',
  'rep.aging.noneTitle': 'Nothing owed', 'rep.aging.noneText': 'Every invoice is paid in full.',
  'rep.aging.showInvoices': 'Show invoices for {name}', 'rep.aging.daysOver': '{n} days past due', 'rep.aging.dueOn': 'due {date}', 'rep.aging.ofTotal': 'of {total}',
  'rep.aging.hint': 'As of today. Days past due count from the invoice\'s due date (invoice date + the company\'s payment terms). Click a company to see its invoices.',
  'rep.b.current': 'Not yet due', 'rep.b.d1_30': '1–30 days', 'rep.b.d31_60': '31–60 days', 'rep.b.d61_90': '61–90 days', 'rep.b.d90': 'Over 90 days',
  // Payments
  'rep.pay.title': 'Payments received', 'rep.pay.sub': 'Money in from companies, and money paid back to them, in the period.',
  'rep.pay.allMethods': 'All methods', 'rep.pay.net': 'Net received', 'rep.pay.in': 'Received', 'rep.pay.out': 'Paid back',
  'rep.pay.nEntries': '{n} entries', 'rep.pay.outNote': 'Refunds and credit paid back as money',
  'rep.pay.emptyText': 'No payments or refunds in this period.', 'rep.pay.fromCredit': 'Company credit',
  'rep.pay.hint': 'Counted on the payment date (shop time). When an invoice is voided its payments move to company credit; that move isn\'t money, so it isn\'t listed.',
  'rep.kind.payment': 'Payment', 'rep.kind.refund': 'Refund', 'rep.kind.credit_refund': 'Credit paid back',
  // ===== stage 9b
  'rep.tab.profit': 'Profit', 'rep.tab.technicians': 'Technicians', 'rep.tab.fleet': 'Fleet spend', 'rep.tab.inventory': 'Inventory', 'rep.tab.service': 'Service compliance',
  'rep.costsTitle': 'This report shows cost prices', 'rep.costsText': 'Your role can see reports but not cost prices. An Owner or Admin can add "View costs" in Settings → Users & access.',
  'rep.m.cost': 'Parts & sublet cost', 'rep.m.gross': 'Gross profit', 'rep.m.margin': 'Margin', 'rep.m.sales': 'Sales before tax',
  // Profit
  'rep.profit.title': 'Profit', 'rep.profit.sub': 'What the invoices in the period earned after the cost of their parts and sublet work.',
  'rep.profit.salesNote': '{n} invoice(s)', 'rep.profit.costNote': 'Cost prices on the invoice lines',
  'rep.profit.grossNote': 'Before wages and overheads', 'rep.profit.partsMargin': 'Parts margin', 'rep.profit.subletMargin': 'Sublet margin',
  'rep.profit.noCost': '{n} part or sublet line(s) on {inv} invoice(s) have no cost price, so they count as pure profit and the margin is overstated.',
  'rep.profit.noCostBadge': '{n} line(s) without cost', 'rep.profit.onlyNoCost': 'Only invoices with missing costs',
  'rep.profit.emptyText': 'No invoices were issued in this period.',
  'rep.profit.hint': 'Cost = the cost price on each part and sublet line when the job was invoiced × quantity. Core charges are passed on at cost. Labor and fees have no cost here because wages aren\'t recorded in Axle, so gross profit is before wages, rent and other overheads. Service and job discounts lower profit. Voided invoices are left out.',
  'rep.col.cost': 'Cost', 'rep.col.parts': 'Parts', 'rep.col.partsCost': 'Parts cost', 'rep.col.sublet': 'Sublet', 'rep.col.subletCost': 'Sublet cost', 'rep.col.noCost': 'Lines without cost',
  // Technicians
  'rep.tech.title': 'Technicians', 'rep.tech.sub': 'Work each technician did on the invoices issued in the period.',
  'rep.tech.labor': 'Labor sold', 'rep.tech.hoursSold': 'Hours charged', 'rep.tech.hoursWorked': 'Hours worked', 'rep.tech.efficiency': 'Efficiency',
  'rep.tech.laborNote': '{n} service(s) on {jobs} job(s)', 'rep.tech.workedNote': 'Where "Hours worked" was filled in',
  'rep.tech.effNote': 'Hours charged ÷ hours worked', 'rep.tech.effNone': 'No hours worked entered yet',
  'rep.tech.unassigned': 'No technician', 'rep.tech.perHour': 'Per hour charged', 'rep.tech.jobs': 'Jobs', 'rep.tech.services': 'Services',
  'rep.tech.col': 'Technician', 'rep.tech.show': 'Show work by {name}', 'rep.tech.service': 'Service',
  'rep.tech.emptyText': 'No invoiced work in this period.',
  'rep.tech.hint': 'Counted on the invoice date. Labor sold is before service and job discounts, the same as Labor in the Sales report. Hours charged = hours on the labor lines. Hours worked = what was typed in "Hours worked" on those lines. Efficiency only uses lines where hours worked was filled in; over 100% means the work took less time than was charged. A flat-priced service\'s labor is its share of the flat price, as on the invoice.',
  // Fleet
  'rep.fleet.title': 'Fleet spend', 'rep.fleet.sub': 'What each company\'s vehicles cost to maintain in the period.',
  'rep.fleet.spent': 'Spent', 'rep.fleet.spentNote': 'Including tax · {n} invoice(s)', 'rep.fleet.vehicles': 'Vehicles serviced',
  'rep.fleet.perVehicle': 'Average per vehicle', 'rep.fleet.perVehicleNote': 'Before tax',
  'rep.fleet.other': 'Other', 'rep.fleet.otherNote': 'Sublet + fees − discounts', 'rep.fleet.visits': 'Visits',
  'rep.fleet.kmDriven': 'Km between visits', 'rep.fleet.perKm': 'Rp per km',
  'rep.fleet.openVehicle': 'Open {plate} (service history and schedules)', 'rep.g.vehicle': 'Vehicle', 'rep.fleet.show': 'Show visits of {plate}', 'rep.col.km': 'Km',
  'rep.fleet.emptyText': 'No invoices were issued in this period.',
  'rep.fleet.hint': 'Counted on the invoice date. Km between visits = the highest minus the lowest km reading on this period\'s invoices. Rp per km = what was spent before tax after the first visit ÷ those km (needs two visits with km readings). Other = sublet + fees − service and job discounts.',
  // Inventory
  'rep.inv.title': 'Inventory', 'rep.inv.sub': 'What is on the shelf, what it is worth, and what was used in the period.',
  'rep.inv.value': 'Stock value', 'rep.inv.valueNote': 'On hand × catalog cost', 'rep.inv.inStock': 'Items in stock',
  'rep.inv.inStockNote': '{n} item(s) kept in stock', 'rep.inv.low': 'Low or out', 'rep.inv.lowNote': 'At or below the reorder point',
  'rep.inv.used': 'Used in period', 'rep.inv.usedNote': '{n} item(s) used on jobs',
  'rep.inv.v.value': 'By value', 'rep.inv.v.used': 'Used in period', 'rep.inv.v.slow': 'Idle for 90+ days', 'rep.inv.v.reorder': 'To reorder',
  'rep.inv.view': 'Show', 'rep.inv.allCategories': 'All categories', 'rep.inv.category': 'Category', 'rep.inv.noCategory': 'No category',
  'rep.col.item': 'Item', 'rep.col.code': 'Code', 'rep.col.brand': 'Brand', 'rep.col.onHand': 'On hand', 'rep.col.unitCost': 'Cost', 'rep.col.value': 'Value', 'rep.col.usedQty': 'Used',
  'rep.col.usedValue': 'Used value', 'rep.col.received': 'Received', 'rep.col.lastUsed': 'Last used', 'rep.col.reorderAt': 'Reorder at', 'rep.col.supplier': 'Supplier',
  'rep.inv.never': 'Never', 'rep.inv.inactive': 'Inactive', 'rep.inv.daysAgo': '{n} days ago',
  'rep.inv.emptyValue': 'Nothing is in stock.', 'rep.inv.emptyUsed': 'No stock was used on jobs in this period.',
  'rep.inv.emptySlow': 'Everything in stock was used or restocked in the last 90 days.', 'rep.inv.emptyReorder': 'Nothing is at or below its reorder point.',
  'rep.inv.slowValue': '{amount} is sitting in {n} item(s) that haven\'t been used or restocked for 90 days or more.',
  'rep.inv.hint': 'Stock on hand and its value are as of now, at today\'s catalog cost. Used = taken off for jobs in the period, valued at the cost on the job line; parts that went back to the shelf because an invoice was voided don\'t count (if the job is invoiced again, they count on the new date). Received = delivered on purchase orders in the period.',
  // Service compliance
  'rep.svc.title': 'Service compliance', 'rep.svc.sub': 'Whether scheduled maintenance is being kept up, per company and vehicle.',
  'rep.svc.compliance': 'Up to date', 'rep.svc.complianceNote': 'Schedules not overdue · {n} active', 'rep.svc.overdue': 'Overdue', 'rep.svc.dueSoon': 'Due soon',
  'rep.svc.noSchedule': 'Vehicles without a schedule', 'rep.svc.noScheduleNote': 'Their maintenance isn\'t being tracked',
  'rep.svc.doneTitle': 'Done in the period', 'rep.svc.doneNote': '{late} late · {onTime} on time',
  'rep.svc.v.company': 'By company', 'rep.svc.v.attention': 'Overdue & due soon', 'rep.svc.v.done': 'Done in the period', 'rep.svc.v.none': 'Vehicles without a schedule',
  'rep.svc.noScheduleCol': 'No schedule', 'rep.svc.status': 'Status', 'rep.svc.kmLateCol': 'Km late', 'rep.svc.daysLateCol': 'Days late', 'rep.svc.vehicles': 'Vehicles', 'rep.svc.schedules': 'Schedules', 'rep.svc.ok': 'Fine', 'rep.svc.schedule': 'Schedule', 'rep.svc.dueAt': 'Due',
  'rep.svc.over': 'Over by', 'rep.svc.doneAt': 'Done', 'rep.svc.result': 'Result', 'rep.svc.onTime': 'On time', 'rep.svc.late': 'Late',
  'rep.svc.first': 'First time', 'rep.svc.unknown': 'Can\'t tell', 'rep.svc.kmLate': '{n} km late', 'rep.svc.daysLate': '{n} days late',
  'rep.svc.kmOver': '{n} km over', 'rep.svc.daysOver': '{n} days over', 'rep.svc.inDays': 'in {n} days', 'rep.svc.inKm': 'in {n} km',
  'rep.svc.showCompany': 'Show schedules needing attention at {name}', 'rep.svc.allGood': 'Nothing overdue or due soon',
  'rep.svc.emptySchedulesTitle': 'No service schedules yet', 'rep.svc.emptyNoneTitle': 'Every vehicle has a schedule', 'rep.svc.emptySchedules': 'No service schedules yet. Add them on a vehicle (Customers → vehicle → Service schedule).',
  'rep.svc.emptyAttention': 'Nothing is overdue or due soon.', 'rep.svc.emptyDone': 'No scheduled services were completed in this period.',
  'rep.svc.emptyNone': 'Every vehicle in use has a service schedule.', 'rep.svc.periodNote': 'The period only applies to "Done in the period".',
  'rep.svc.hint': 'Status is as of today, with the same "due soon" settings as the reminders (Settings → Shop). Sold and inactive vehicles are left out. On time / late is recorded when a scheduled service is completed, from this update on: late means it was done after its due date or past its due km; done exactly at the due point counts as on time.',
}

export const reportsId = {
  'dash.today': 'Hari ini', 'dash.money': 'Keuangan', 'dash.attention': 'Perlu perhatian',
  'dash.bookings': 'Janji servis hari ini', 'dash.requests': '{n} permintaan janji menunggu', 'dash.noRequests': 'Tidak ada permintaan menunggu',
  'dash.inShop': 'Di bengkel', 'dash.nothingInShop': 'Tidak ada pekerjaan yang sedang berjalan',
  'dash.waitingParts': 'Menunggu part', 'dash.waitingPartsNote': 'Pekerjaan terbuka dengan part dipesan yang belum semua datang',
  'dash.readyInv': 'Siap dibuatkan invoice', 'dash.readyNote': 'Pekerjaan selesai, belum ada invoice',
  'dash.invoicedMtd': 'Invoice bulan ini', 'dash.nInvoices': '{n} invoice', 'dash.vsLast': '{pct} dibanding bulan lalu sampai tanggal yang sama ({amount})',
  'dash.receivedMtd': 'Diterima bulan ini', 'dash.receivedNote': 'Pembayaran dikurangi refund',
  'dash.owed': 'Piutang perusahaan', 'dash.openInvoices': '{n} invoice belum lunas',
  'dash.overdue': 'Lewat jatuh tempo', 'dash.overdueNote': '{n} invoice · {amount} lebih dari 90 hari', 'dash.noneOverdue': 'Tidak ada yang lewat jatuh tempo',
  'dash.service': 'Servis jatuh tempo', 'dash.serviceDetail': '{over} terlambat · {soon} segera',
  'dash.lowStock': 'Part menipis atau habis', 'dash.lowStockDetail': 'Di atau di bawah titik pesan ulang',
  'dash.bills': 'Tagihan supplier', 'dash.billsDetail': '{overdue} lewat jatuh tempo · {soon} jatuh tempo 7 hari',
  'dash.cores': 'Core', 'dash.coresDetail': '{take} masih di kendaraan · {send} siap dikirim balik',
  'dash.returns': 'Retur ke supplier', 'dash.returnsDetail': 'Belum direfund',
  'dash.estimates': 'Estimasi terbuka', 'dash.estimatesDetail': 'Belum dijadwalkan atau dimulai',
  'dash.allClear': 'Aman',
  'dash.chartTitle': '6 bulan terakhir', 'dash.invoiced': 'Invoice', 'dash.received': 'Diterima', 'dash.month': 'Bulan',
  'dash.showTable': 'Tampilkan angka', 'dash.hideTable': 'Sembunyikan angka', 'dash.chartEmpty': 'Belum ada invoice atau pembayaran dalam 6 bulan terakhir.',
  'dash.chartHint': 'Invoice = invoice yang terbit di bulan itu (yang dibatalkan tidak dihitung). Diterima = pembayaran di bulan itu dikurangi refund.',
  'rep.tab.sales': 'Penjualan', 'rep.tab.aging': 'Umur piutang', 'rep.tab.payments': 'Pembayaran diterima',
  'rep.noAccessTitle': 'Laporan untuk manajer', 'rep.noAccessText': 'Peran Anda tidak termasuk laporan. Pemilik atau Admin bisa mengubahnya di Pengaturan → Pengguna & akses.',
  'rep.moreSoon': 'Laporan lain (laba, teknisi, biaya armada, inventaris, kepatuhan servis) hadir di tahap 9b.',
  'rep.period': 'Periode', 'rep.from': 'Dari', 'rep.to': 'Sampai', 'rep.company': 'Perusahaan', 'rep.allCompanies': 'Semua perusahaan',
  'rep.p.this_month': 'Bulan ini', 'rep.p.last_month': 'Bulan lalu', 'rep.p.last_30': '30 hari terakhir', 'rep.p.this_year': 'Tahun ini',
  'rep.p.last_year': 'Tahun lalu', 'rep.p.custom': 'Pilih tanggal…',
  'rep.groupBy': 'Kelompokkan', 'rep.g.auto': 'Per hari atau bulan', 'rep.g.day': 'Hari', 'rep.g.month': 'Bulan', 'rep.g.company': 'Perusahaan',
  'rep.g.invoices': 'Per invoice', 'rep.g.method': 'Metode', 'rep.g.list': 'Per pembayaran',
  'rep.csv': 'Unduh CSV', 'rep.empty': 'Tidak ada data di periode ini', 'rep.total': 'Total', 'rep.jobNo': 'Pekerjaan {no}', 'rep.paidUp': 'Lunas',
  'rep.m.parts': 'Part', 'rep.m.labor': 'Jasa', 'rep.m.sublet': 'Sublet', 'rep.m.fees': 'Biaya', 'rep.m.discounts': 'Diskon',
  'rep.m.subtotal': 'Sebelum pajak', 'rep.m.tax': 'Pajak', 'rep.m.total': 'Total',
  'rep.col.invoice': 'Invoice', 'rep.col.date': 'Tanggal', 'rep.col.job': 'Pekerjaan', 'rep.col.company': 'Perusahaan', 'rep.col.plate': 'Plat',
  'rep.col.paid': 'Dibayar', 'rep.col.balance': 'Sisa tagihan', 'rep.col.invoices': 'Invoice', 'rep.col.due': 'Jatuh tempo', 'rep.col.daysOverdue': 'Hari terlambat',
  'rep.col.bucket': 'Umur', 'rep.col.owed': 'Piutang', 'rep.col.kind': 'Jenis', 'rep.col.method': 'Metode', 'rep.col.reference': 'Referensi',
  'rep.col.amount': 'Jumlah', 'rep.col.entries': 'Transaksi',
  'rep.sales.title': 'Penjualan', 'rep.sales.sub': 'Invoice yang terbit di periode ini, dipisah menjadi part, jasa, sublet, biaya, dan diskon.',
  'rep.sales.total': 'Total invoice', 'rep.sales.nInvoices': '{n} invoice', 'rep.sales.beforeTax': 'Part + jasa + sublet + biaya − diskon',
  'rep.sales.emptyText': 'Tidak ada invoice yang terbit di periode ini. Coba periode lebih panjang atau perusahaan lain.',
  'rep.sales.hint': 'Dihitung pada tanggal invoice (waktu bengkel). Invoice yang dibatalkan tidak dihitung, jadi angka bulan lalu bisa turun bila salah satu invoicenya dibatalkan kemudian; invoice yang diterbitkan ulang dihitung pada tanggal barunya. Part termasuk biaya core. Diskon per baris sudah dikurangkan dari part dan jasa; kolom Diskon adalah diskon servis dan pekerjaan.',
  'rep.sales.voids': '{n} invoice senilai {amount} dibatalkan di periode ini dan tidak dihitung.', 'rep.sales.voidedOn': 'dibatalkan {date} (terbit {issued})',
  'rep.show': 'Lihat', 'rep.hide': 'Sembunyikan', 'rep.aging.creditOnly': 'Tidak ada piutang, hanya kredit',
  'rep.aging.title': 'Umur piutang', 'rep.aging.sub': 'Sisa tagihan tiap perusahaan hari ini, menurut berapa lama lewat jatuh tempo.',
  'rep.aging.owed': 'Total piutang', 'rep.aging.nInvoices': '{n} invoice', 'rep.aging.overdue': 'Lewat jatuh tempo', 'rep.aging.share': '{pct}% dari piutang',
  'rep.aging.credit': 'Kredit belum dipakai', 'rep.aging.creditNote': 'Bisa dipakai untuk invoice ini',
  'rep.aging.noneTitle': 'Tidak ada piutang', 'rep.aging.noneText': 'Semua invoice sudah lunas.',
  'rep.aging.showInvoices': 'Tampilkan invoice {name}', 'rep.aging.daysOver': 'terlambat {n} hari', 'rep.aging.dueOn': 'jatuh tempo {date}', 'rep.aging.ofTotal': 'dari {total}',
  'rep.aging.hint': 'Per hari ini. Hari terlambat dihitung dari jatuh tempo invoice (tanggal invoice + termin perusahaan). Klik perusahaan untuk melihat invoicenya.',
  'rep.b.current': 'Belum jatuh tempo', 'rep.b.d1_30': '1–30 hari', 'rep.b.d31_60': '31–60 hari', 'rep.b.d61_90': '61–90 hari', 'rep.b.d90': 'Lebih dari 90 hari',
  'rep.pay.title': 'Pembayaran diterima', 'rep.pay.sub': 'Uang masuk dari perusahaan, dan uang yang dikembalikan ke mereka, di periode ini.',
  'rep.pay.allMethods': 'Semua metode', 'rep.pay.net': 'Diterima bersih', 'rep.pay.in': 'Diterima', 'rep.pay.out': 'Dikembalikan',
  'rep.pay.nEntries': '{n} transaksi', 'rep.pay.outNote': 'Refund dan kredit yang dikembalikan sebagai uang',
  'rep.pay.emptyText': 'Tidak ada pembayaran atau refund di periode ini.', 'rep.pay.fromCredit': 'Kredit perusahaan',
  'rep.pay.hint': 'Dihitung pada tanggal pembayaran (waktu bengkel). Saat invoice dibatalkan, pembayarannya pindah ke kredit perusahaan; perpindahan itu bukan uang, jadi tidak dicantumkan.',
  'rep.kind.payment': 'Pembayaran', 'rep.kind.refund': 'Refund', 'rep.kind.credit_refund': 'Kredit dikembalikan',
  'db:Choose a start and end date': 'Pilih tanggal mulai dan selesai.',
  'db:The end date is before the start date': 'Tanggal selesai sebelum tanggal mulai.',
  'db:Choose a period of at most 5 years': 'Pilih periode paling lama 5 tahun.',
  // ===== tahap 9b
  'rep.tab.profit': 'Laba', 'rep.tab.technicians': 'Teknisi', 'rep.tab.fleet': 'Biaya armada', 'rep.tab.inventory': 'Inventaris', 'rep.tab.service': 'Kepatuhan servis',
  'rep.costsTitle': 'Laporan ini menampilkan harga pokok', 'rep.costsText': 'Peran Anda bisa melihat laporan tetapi tidak harga pokok. Pemilik atau Admin bisa menambahkan "Lihat harga pokok" di Pengaturan → Pengguna & akses.',
  'rep.m.cost': 'Harga pokok part & sublet', 'rep.m.gross': 'Laba kotor', 'rep.m.margin': 'Margin', 'rep.m.sales': 'Penjualan sebelum pajak',
  'rep.profit.title': 'Laba', 'rep.profit.sub': 'Hasil invoice di periode ini setelah dikurangi harga pokok part dan pekerjaan sublet.',
  'rep.profit.salesNote': '{n} invoice', 'rep.profit.costNote': 'Harga pokok di baris invoice',
  'rep.profit.grossNote': 'Sebelum gaji dan biaya operasional', 'rep.profit.partsMargin': 'Margin part', 'rep.profit.subletMargin': 'Margin sublet',
  'rep.profit.noCost': '{n} baris part atau sublet di {inv} invoice tidak punya harga pokok, sehingga dihitung laba penuh dan margin terlihat lebih tinggi.',
  'rep.profit.noCostBadge': '{n} baris tanpa harga pokok', 'rep.profit.onlyNoCost': 'Hanya invoice dengan harga pokok kosong',
  'rep.profit.emptyText': 'Tidak ada invoice yang terbit di periode ini.',
  'rep.profit.hint': 'Harga pokok = harga pokok di setiap baris part dan sublet saat pekerjaan dibuatkan invoice × jumlah. Biaya core diteruskan sesuai harga pokok. Jasa dan biaya tidak punya harga pokok di sini karena gaji tidak dicatat di Axle, jadi laba kotor dihitung sebelum gaji, sewa, dan biaya operasional lain. Diskon servis dan pekerjaan mengurangi laba. Invoice yang dibatalkan tidak dihitung.',
  'rep.col.cost': 'Harga pokok', 'rep.col.parts': 'Part', 'rep.col.partsCost': 'Harga pokok part', 'rep.col.sublet': 'Sublet', 'rep.col.subletCost': 'Harga pokok sublet', 'rep.col.noCost': 'Baris tanpa harga pokok',
  'rep.tech.title': 'Teknisi', 'rep.tech.sub': 'Pekerjaan tiap teknisi pada invoice yang terbit di periode ini.',
  'rep.tech.labor': 'Jasa terjual', 'rep.tech.hoursSold': 'Jam ditagih', 'rep.tech.hoursWorked': 'Jam dikerjakan', 'rep.tech.efficiency': 'Efisiensi',
  'rep.tech.laborNote': '{n} servis di {jobs} pekerjaan', 'rep.tech.workedNote': 'Bila "Jam dikerjakan" diisi',
  'rep.tech.effNote': 'Jam ditagih ÷ jam dikerjakan', 'rep.tech.effNone': 'Jam dikerjakan belum diisi',
  'rep.tech.unassigned': 'Tanpa teknisi', 'rep.tech.perHour': 'Per jam ditagih', 'rep.tech.jobs': 'Pekerjaan', 'rep.tech.services': 'Servis',
  'rep.tech.col': 'Teknisi', 'rep.tech.show': 'Tampilkan pekerjaan {name}', 'rep.tech.service': 'Servis',
  'rep.tech.emptyText': 'Tidak ada pekerjaan yang dibuatkan invoice di periode ini.',
  'rep.tech.hint': 'Dihitung pada tanggal invoice. Jasa terjual dihitung sebelum diskon servis dan pekerjaan, sama dengan Jasa di laporan Penjualan. Jam ditagih = jam di baris jasa. Jam dikerjakan = isian "Jam dikerjakan" di baris tersebut. Efisiensi hanya memakai baris yang jam dikerjakannya diisi; di atas 100% berarti pekerjaan lebih cepat dari jam yang ditagih. Jasa pada servis harga paket adalah bagiannya dari harga paket, seperti di invoice.',
  'rep.fleet.title': 'Biaya armada', 'rep.fleet.sub': 'Biaya perawatan kendaraan tiap perusahaan di periode ini.',
  'rep.fleet.spent': 'Total biaya', 'rep.fleet.spentNote': 'Termasuk pajak · {n} invoice', 'rep.fleet.vehicles': 'Kendaraan diservis',
  'rep.fleet.perVehicle': 'Rata-rata per kendaraan', 'rep.fleet.perVehicleNote': 'Sebelum pajak',
  'rep.fleet.other': 'Lainnya', 'rep.fleet.otherNote': 'Sublet + biaya − diskon', 'rep.fleet.visits': 'Kunjungan',
  'rep.fleet.kmDriven': 'Km antar kunjungan', 'rep.fleet.perKm': 'Rp per km',
  'rep.fleet.openVehicle': 'Buka {plate} (riwayat servis dan jadwal)', 'rep.g.vehicle': 'Kendaraan', 'rep.fleet.show': 'Tampilkan kunjungan {plate}', 'rep.col.km': 'Km',
  'rep.fleet.emptyText': 'Tidak ada invoice yang terbit di periode ini.',
  'rep.fleet.hint': 'Dihitung pada tanggal invoice. Km antar kunjungan = km tertinggi dikurangi km terendah di invoice periode ini. Rp per km = biaya sebelum pajak setelah kunjungan pertama ÷ km tersebut (perlu dua kunjungan dengan km tercatat). Lainnya = sublet + biaya − diskon servis dan pekerjaan.',
  'rep.inv.title': 'Inventaris', 'rep.inv.sub': 'Apa yang ada di rak, berapa nilainya, dan apa yang terpakai di periode ini.',
  'rep.inv.value': 'Nilai stok', 'rep.inv.valueNote': 'Stok × harga pokok katalog', 'rep.inv.inStock': 'Barang tersedia',
  'rep.inv.inStockNote': '{n} barang disimpan di stok', 'rep.inv.low': 'Menipis atau habis', 'rep.inv.lowNote': 'Di atau di bawah titik pesan ulang',
  'rep.inv.used': 'Terpakai di periode', 'rep.inv.usedNote': '{n} barang dipakai untuk pekerjaan',
  'rep.inv.v.value': 'Menurut nilai', 'rep.inv.v.used': 'Terpakai di periode', 'rep.inv.v.slow': 'Diam 90+ hari', 'rep.inv.v.reorder': 'Perlu dipesan',
  'rep.inv.view': 'Tampilkan', 'rep.inv.allCategories': 'Semua kategori', 'rep.inv.category': 'Kategori', 'rep.inv.noCategory': 'Tanpa kategori',
  'rep.col.item': 'Barang', 'rep.col.code': 'Kode', 'rep.col.brand': 'Merek', 'rep.col.onHand': 'Stok', 'rep.col.unitCost': 'Harga pokok', 'rep.col.value': 'Nilai', 'rep.col.usedQty': 'Terpakai',
  'rep.col.usedValue': 'Nilai terpakai', 'rep.col.received': 'Diterima', 'rep.col.lastUsed': 'Terakhir dipakai', 'rep.col.reorderAt': 'Pesan ulang di', 'rep.col.supplier': 'Supplier',
  'rep.inv.never': 'Belum pernah', 'rep.inv.inactive': 'Nonaktif', 'rep.inv.daysAgo': '{n} hari lalu',
  'rep.inv.emptyValue': 'Tidak ada barang di stok.', 'rep.inv.emptyUsed': 'Tidak ada stok yang dipakai untuk pekerjaan di periode ini.',
  'rep.inv.emptySlow': 'Semua barang di stok dipakai atau diisi ulang dalam 90 hari terakhir.', 'rep.inv.emptyReorder': 'Tidak ada barang di atau di bawah titik pesan ulang.',
  'rep.inv.slowValue': '{amount} tertahan di {n} barang yang tidak dipakai atau diisi ulang 90 hari atau lebih.',
  'rep.inv.hint': 'Stok dan nilainya per saat ini, dengan harga pokok katalog hari ini. Terpakai = diambil untuk pekerjaan di periode ini, dinilai dengan harga pokok di baris pekerjaan; part yang kembali ke rak karena invoice dibatalkan tidak dihitung (bila pekerjaan dibuatkan invoice lagi, dihitung pada tanggal barunya). Diterima = datang dari purchase order di periode ini.',
  'rep.svc.title': 'Kepatuhan servis', 'rep.svc.sub': 'Apakah perawatan berkala dijalankan, per perusahaan dan kendaraan.',
  'rep.svc.compliance': 'Tepat jadwal', 'rep.svc.complianceNote': 'Jadwal yang tidak lewat jatuh tempo · {n} aktif', 'rep.svc.overdue': 'Lewat jatuh tempo', 'rep.svc.dueSoon': 'Segera',
  'rep.svc.noSchedule': 'Kendaraan tanpa jadwal', 'rep.svc.noScheduleNote': 'Perawatannya tidak dipantau',
  'rep.svc.doneTitle': 'Dikerjakan di periode', 'rep.svc.doneNote': '{late} terlambat · {onTime} tepat waktu',
  'rep.svc.v.company': 'Per perusahaan', 'rep.svc.v.attention': 'Terlambat & segera', 'rep.svc.v.done': 'Dikerjakan di periode', 'rep.svc.v.none': 'Kendaraan tanpa jadwal',
  'rep.svc.noScheduleCol': 'Tanpa jadwal', 'rep.svc.status': 'Status', 'rep.svc.kmLateCol': 'Km terlambat', 'rep.svc.daysLateCol': 'Hari terlambat', 'rep.svc.vehicles': 'Kendaraan', 'rep.svc.schedules': 'Jadwal', 'rep.svc.ok': 'Aman', 'rep.svc.schedule': 'Jadwal', 'rep.svc.dueAt': 'Jatuh tempo',
  'rep.svc.over': 'Lewat', 'rep.svc.doneAt': 'Dikerjakan', 'rep.svc.result': 'Hasil', 'rep.svc.onTime': 'Tepat waktu', 'rep.svc.late': 'Terlambat',
  'rep.svc.first': 'Pertama kali', 'rep.svc.unknown': 'Tidak diketahui', 'rep.svc.kmLate': 'terlambat {n} km', 'rep.svc.daysLate': 'terlambat {n} hari',
  'rep.svc.kmOver': 'lewat {n} km', 'rep.svc.daysOver': 'lewat {n} hari', 'rep.svc.inDays': '{n} hari lagi', 'rep.svc.inKm': '{n} km lagi',
  'rep.svc.showCompany': 'Tampilkan jadwal yang perlu perhatian di {name}', 'rep.svc.allGood': 'Tidak ada yang terlambat atau segera',
  'rep.svc.emptySchedulesTitle': 'Belum ada jadwal servis', 'rep.svc.emptyNoneTitle': 'Semua kendaraan punya jadwal', 'rep.svc.emptySchedules': 'Belum ada jadwal servis. Tambahkan di kendaraan (Pelanggan → kendaraan → Jadwal servis).',
  'rep.svc.emptyAttention': 'Tidak ada yang terlambat atau segera.', 'rep.svc.emptyDone': 'Tidak ada servis berkala yang selesai di periode ini.',
  'rep.svc.emptyNone': 'Semua kendaraan yang dipakai punya jadwal servis.', 'rep.svc.periodNote': 'Periode hanya berlaku untuk "Dikerjakan di periode".',
  'rep.svc.hint': 'Status per hari ini, dengan pengaturan "segera" yang sama dengan pengingat (Pengaturan → Bengkel). Kendaraan terjual dan nonaktif tidak dihitung. Tepat waktu / terlambat dicatat saat servis berkala diselesaikan, mulai pembaruan ini: terlambat berarti dikerjakan setelah tanggal jatuh tempo atau melewati km jatuh tempo; tepat di titik jatuh tempo dihitung tepat waktu.',
}
